// Copyright 2020 Infostellar, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: stellarstation/api/v1/orbit/orbit.proto

package orbit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Unparsed TLE data for a satellite - https://en.wikipedia.org/wiki/Two-line_element_set
type Tle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The first line of the TLE. Not a title line.
	Line_1 string `protobuf:"bytes,1,opt,name=line_1,json=line1,proto3" json:"line_1,omitempty"`
	// The second line of the TLE.
	Line_2        string `protobuf:"bytes,2,opt,name=line_2,json=line2,proto3" json:"line_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tle) Reset() {
	*x = Tle{}
	mi := &file_stellarstation_api_v1_orbit_orbit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tle) ProtoMessage() {}

func (x *Tle) ProtoReflect() protoreflect.Message {
	mi := &file_stellarstation_api_v1_orbit_orbit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tle.ProtoReflect.Descriptor instead.
func (*Tle) Descriptor() ([]byte, []int) {
	return file_stellarstation_api_v1_orbit_orbit_proto_rawDescGZIP(), []int{0}
}

func (x *Tle) GetLine_1() string {
	if x != nil {
		return x.Line_1
	}
	return ""
}

func (x *Tle) GetLine_2() string {
	if x != nil {
		return x.Line_2
	}
	return ""
}

var File_stellarstation_api_v1_orbit_orbit_proto protoreflect.FileDescriptor

const file_stellarstation_api_v1_orbit_orbit_proto_rawDesc = "" +
	"\n" +
	"'stellarstation/api/v1/orbit/orbit.proto\x12\x1bstellarstation.api.v1.orbit\"3\n" +
	"\x03Tle\x12\x15\n" +
	"\x06line_1\x18\x01 \x01(\tR\x05line1\x12\x15\n" +
	"\x06line_2\x18\x02 \x01(\tR\x05line2Bi\n" +
	"\x1fcom.stellarstation.api.v1.orbitB\n" +
	"OrbitProtoP\x01Z8github.com/infostellarinc/go-stellarstation/api/v1/orbitb\x06proto3"

var (
	file_stellarstation_api_v1_orbit_orbit_proto_rawDescOnce sync.Once
	file_stellarstation_api_v1_orbit_orbit_proto_rawDescData []byte
)

func file_stellarstation_api_v1_orbit_orbit_proto_rawDescGZIP() []byte {
	file_stellarstation_api_v1_orbit_orbit_proto_rawDescOnce.Do(func() {
		file_stellarstation_api_v1_orbit_orbit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stellarstation_api_v1_orbit_orbit_proto_rawDesc), len(file_stellarstation_api_v1_orbit_orbit_proto_rawDesc)))
	})
	return file_stellarstation_api_v1_orbit_orbit_proto_rawDescData
}

var file_stellarstation_api_v1_orbit_orbit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stellarstation_api_v1_orbit_orbit_proto_goTypes = []any{
	(*Tle)(nil), // 0: stellarstation.api.v1.orbit.Tle
}
var file_stellarstation_api_v1_orbit_orbit_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stellarstation_api_v1_orbit_orbit_proto_init() }
func file_stellarstation_api_v1_orbit_orbit_proto_init() {
	if File_stellarstation_api_v1_orbit_orbit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellarstation_api_v1_orbit_orbit_proto_rawDesc), len(file_stellarstation_api_v1_orbit_orbit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stellarstation_api_v1_orbit_orbit_proto_goTypes,
		DependencyIndexes: file_stellarstation_api_v1_orbit_orbit_proto_depIdxs,
		MessageInfos:      file_stellarstation_api_v1_orbit_orbit_proto_msgTypes,
	}.Build()
	File_stellarstation_api_v1_orbit_orbit_proto = out.File
	file_stellarstation_api_v1_orbit_orbit_proto_goTypes = nil
	file_stellarstation_api_v1_orbit_orbit_proto_depIdxs = nil
}
