// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stellarstation/api/v1/stellarstation.proto

package stellarstation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A type of framing of a binary payload used in satellite communicaation.
type Framing int32

const (
	// No framing done in the API. All payloads are assumed to be pre-framed and ready for
	// transmission to the satellite or API client with no additional processing.
	Framing_BITSTREAM Framing = 0
	// AX.25 (Amateur X.25) framing - https://en.wikipedia.org/wiki/AX.25
	Framing_AX25 Framing = 1
	// No framing or demodulation done in the API. Raw IQ data is sent to the API client with no
	// additional processing.
	Framing_IQ Framing = 2
)

var Framing_name = map[int32]string{
	0: "BITSTREAM",
	1: "AX25",
	2: "IQ",
}
var Framing_value = map[string]int32{
	"BITSTREAM": 0,
	"AX25":      1,
	"IQ":        2,
}

func (x Framing) String() string {
	return proto.EnumName(Framing_name, int32(x))
}
func (Framing) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{0}
}

// Status of a plan.
type Plan_Status int32

const (
	// The plan has been scheduled and will be executed at `aos_time`.
	Plan_RESERVED Plan_Status = 0
	// The plan is currently executing.
	Plan_EXECUTING Plan_Status = 1
	// The plan has executed successfully.
	Plan_SUCCEEDED Plan_Status = 2
	// The plan has executed but was not successful.
	Plan_FAILED Plan_Status = 3
	// The plan has been cancelled and will not be executed.
	Plan_CANCELLED Plan_Status = 4
)

var Plan_Status_name = map[int32]string{
	0: "RESERVED",
	1: "EXECUTING",
	2: "SUCCEEDED",
	3: "FAILED",
	4: "CANCELLED",
}
var Plan_Status_value = map[string]int32{
	"RESERVED":  0,
	"EXECUTING": 1,
	"SUCCEEDED": 2,
	"FAILED":    3,
	"CANCELLED": 4,
}

func (x Plan_Status) String() string {
	return proto.EnumName(Plan_Status_name, int32(x))
}
func (Plan_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{7, 0}
}

// Request for the `OpenSatelliteStream` method.
type SatelliteStreamRequest struct {
	// The ID of the satellite to open a stream with. The ID of a satellite can be found on the
	// StellarStation Console page for the satellite.
	SatelliteId string `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	// The `SatelliteStreamResponse.stream_id` from a previously opened stream to resume. If the
	// specified stream has already expired or been closed, the stream is closed with a `ABORTED`
	// error.
	StreamId string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// A request to send on the satellite stream. Currently only command sending to the satellite is
	// supported. The request does not need to be filled on the first request to
	// `OpenSatelliteStream`.
	//
	// Types that are valid to be assigned to Request:
	//	*SatelliteStreamRequest_SendSatelliteCommandsRequest
	Request              isSatelliteStreamRequest_Request `protobuf_oneof:"Request"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *SatelliteStreamRequest) Reset()         { *m = SatelliteStreamRequest{} }
func (m *SatelliteStreamRequest) String() string { return proto.CompactTextString(m) }
func (*SatelliteStreamRequest) ProtoMessage()    {}
func (*SatelliteStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{0}
}
func (m *SatelliteStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatelliteStreamRequest.Unmarshal(m, b)
}
func (m *SatelliteStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatelliteStreamRequest.Marshal(b, m, deterministic)
}
func (dst *SatelliteStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatelliteStreamRequest.Merge(dst, src)
}
func (m *SatelliteStreamRequest) XXX_Size() int {
	return xxx_messageInfo_SatelliteStreamRequest.Size(m)
}
func (m *SatelliteStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatelliteStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatelliteStreamRequest proto.InternalMessageInfo

func (m *SatelliteStreamRequest) GetSatelliteId() string {
	if m != nil {
		return m.SatelliteId
	}
	return ""
}

func (m *SatelliteStreamRequest) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

type isSatelliteStreamRequest_Request interface {
	isSatelliteStreamRequest_Request()
}

type SatelliteStreamRequest_SendSatelliteCommandsRequest struct {
	SendSatelliteCommandsRequest *SendSatelliteCommandsRequest `protobuf:"bytes,3,opt,name=send_satellite_commands_request,json=sendSatelliteCommandsRequest,proto3,oneof"`
}

func (*SatelliteStreamRequest_SendSatelliteCommandsRequest) isSatelliteStreamRequest_Request() {}

func (m *SatelliteStreamRequest) GetRequest() isSatelliteStreamRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SatelliteStreamRequest) GetSendSatelliteCommandsRequest() *SendSatelliteCommandsRequest {
	if x, ok := m.GetRequest().(*SatelliteStreamRequest_SendSatelliteCommandsRequest); ok {
		return x.SendSatelliteCommandsRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SatelliteStreamRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SatelliteStreamRequest_OneofMarshaler, _SatelliteStreamRequest_OneofUnmarshaler, _SatelliteStreamRequest_OneofSizer, []interface{}{
		(*SatelliteStreamRequest_SendSatelliteCommandsRequest)(nil),
	}
}

func _SatelliteStreamRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SatelliteStreamRequest)
	// Request
	switch x := m.Request.(type) {
	case *SatelliteStreamRequest_SendSatelliteCommandsRequest:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SendSatelliteCommandsRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SatelliteStreamRequest.Request has unexpected type %T", x)
	}
	return nil
}

func _SatelliteStreamRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SatelliteStreamRequest)
	switch tag {
	case 3: // Request.send_satellite_commands_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SendSatelliteCommandsRequest)
		err := b.DecodeMessage(msg)
		m.Request = &SatelliteStreamRequest_SendSatelliteCommandsRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SatelliteStreamRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SatelliteStreamRequest)
	// Request
	switch x := m.Request.(type) {
	case *SatelliteStreamRequest_SendSatelliteCommandsRequest:
		s := proto.Size(x.SendSatelliteCommandsRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A request to send commands to a satellite.
type SendSatelliteCommandsRequest struct {
	// The framing to be applied to `command` before transmission. If `command` has already been
	// framed, this should be set to BITSTREAM and no additional processing will take place before
	// modulation. When applying framing, each `command` will be treated as a single frame. Framing
	// parameters used will be the ones registered for the satellite in the StellarStation Console.
	//
	// Currently IQ is not allowed for `output_framing`.
	OutputFraming Framing `protobuf:"varint,1,opt,name=output_framing,json=outputFraming,proto3,enum=stellarstation.api.v1.Framing" json:"output_framing,omitempty"`
	// The command frames to send to the satellite. All commands will be transmitted in sequence
	// immediately, during which time telemetry will not be received. After all commands have been
	// transmitted, telemetry receive will be immediately re-enabled. Them aximum size of each command
	// is 2MB. If a command larger than 2MB is received, the stream will be closed with a
	// `RESOURCE_EXHAUSTED` error.
	Command              [][]byte `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSatelliteCommandsRequest) Reset()         { *m = SendSatelliteCommandsRequest{} }
func (m *SendSatelliteCommandsRequest) String() string { return proto.CompactTextString(m) }
func (*SendSatelliteCommandsRequest) ProtoMessage()    {}
func (*SendSatelliteCommandsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{1}
}
func (m *SendSatelliteCommandsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSatelliteCommandsRequest.Unmarshal(m, b)
}
func (m *SendSatelliteCommandsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSatelliteCommandsRequest.Marshal(b, m, deterministic)
}
func (dst *SendSatelliteCommandsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSatelliteCommandsRequest.Merge(dst, src)
}
func (m *SendSatelliteCommandsRequest) XXX_Size() int {
	return xxx_messageInfo_SendSatelliteCommandsRequest.Size(m)
}
func (m *SendSatelliteCommandsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSatelliteCommandsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSatelliteCommandsRequest proto.InternalMessageInfo

func (m *SendSatelliteCommandsRequest) GetOutputFraming() Framing {
	if m != nil {
		return m.OutputFraming
	}
	return Framing_BITSTREAM
}

func (m *SendSatelliteCommandsRequest) GetCommand() [][]byte {
	if m != nil {
		return m.Command
	}
	return nil
}

// A response from the `OpenSatelliteStream` method.
type SatelliteStreamResponse struct {
	// The ID of this stream, which can be used in a subsequent call to `OpenSatelliteStream` to
	// resume this stream on interruption (e.g., if a network failure causes the connection to be
	// closed mid-stream). Telemetry received on a previously opened stream with no current listener
	// will be buffered for a maximum of 1 minute, and the stream itself will be cancelled and no more
	// buffering will occur if no client resumes the stream with `OpenSatelliteStream` within 10
	// minutes.
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// A response on the stream. Currently the only type of response is telemetry received from the
	// satellite.
	//
	// Types that are valid to be assigned to Response:
	//	*SatelliteStreamResponse_ReceiveTelemetryResponse
	Response             isSatelliteStreamResponse_Response `protobuf_oneof:"Response"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *SatelliteStreamResponse) Reset()         { *m = SatelliteStreamResponse{} }
func (m *SatelliteStreamResponse) String() string { return proto.CompactTextString(m) }
func (*SatelliteStreamResponse) ProtoMessage()    {}
func (*SatelliteStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{2}
}
func (m *SatelliteStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatelliteStreamResponse.Unmarshal(m, b)
}
func (m *SatelliteStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatelliteStreamResponse.Marshal(b, m, deterministic)
}
func (dst *SatelliteStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatelliteStreamResponse.Merge(dst, src)
}
func (m *SatelliteStreamResponse) XXX_Size() int {
	return xxx_messageInfo_SatelliteStreamResponse.Size(m)
}
func (m *SatelliteStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SatelliteStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SatelliteStreamResponse proto.InternalMessageInfo

func (m *SatelliteStreamResponse) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

type isSatelliteStreamResponse_Response interface {
	isSatelliteStreamResponse_Response()
}

type SatelliteStreamResponse_ReceiveTelemetryResponse struct {
	ReceiveTelemetryResponse *ReceiveTelemetryResponse `protobuf:"bytes,2,opt,name=receive_telemetry_response,json=receiveTelemetryResponse,proto3,oneof"`
}

func (*SatelliteStreamResponse_ReceiveTelemetryResponse) isSatelliteStreamResponse_Response() {}

func (m *SatelliteStreamResponse) GetResponse() isSatelliteStreamResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SatelliteStreamResponse) GetReceiveTelemetryResponse() *ReceiveTelemetryResponse {
	if x, ok := m.GetResponse().(*SatelliteStreamResponse_ReceiveTelemetryResponse); ok {
		return x.ReceiveTelemetryResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SatelliteStreamResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SatelliteStreamResponse_OneofMarshaler, _SatelliteStreamResponse_OneofUnmarshaler, _SatelliteStreamResponse_OneofSizer, []interface{}{
		(*SatelliteStreamResponse_ReceiveTelemetryResponse)(nil),
	}
}

func _SatelliteStreamResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SatelliteStreamResponse)
	// Response
	switch x := m.Response.(type) {
	case *SatelliteStreamResponse_ReceiveTelemetryResponse:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReceiveTelemetryResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SatelliteStreamResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _SatelliteStreamResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SatelliteStreamResponse)
	switch tag {
	case 2: // Response.receive_telemetry_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReceiveTelemetryResponse)
		err := b.DecodeMessage(msg)
		m.Response = &SatelliteStreamResponse_ReceiveTelemetryResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SatelliteStreamResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SatelliteStreamResponse)
	// Response
	switch x := m.Response.(type) {
	case *SatelliteStreamResponse_ReceiveTelemetryResponse:
		s := proto.Size(x.ReceiveTelemetryResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A response from a satellite containing telemetry.
type ReceiveTelemetryResponse struct {
	// The telemetry received.
	Telemetry            *Telemetry `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReceiveTelemetryResponse) Reset()         { *m = ReceiveTelemetryResponse{} }
func (m *ReceiveTelemetryResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveTelemetryResponse) ProtoMessage()    {}
func (*ReceiveTelemetryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{3}
}
func (m *ReceiveTelemetryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveTelemetryResponse.Unmarshal(m, b)
}
func (m *ReceiveTelemetryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveTelemetryResponse.Marshal(b, m, deterministic)
}
func (dst *ReceiveTelemetryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveTelemetryResponse.Merge(dst, src)
}
func (m *ReceiveTelemetryResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveTelemetryResponse.Size(m)
}
func (m *ReceiveTelemetryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveTelemetryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveTelemetryResponse proto.InternalMessageInfo

func (m *ReceiveTelemetryResponse) GetTelemetry() *Telemetry {
	if m != nil {
		return m.Telemetry
	}
	return nil
}

// A chunk or frame of telemetry data that has been received from a satellite.
type Telemetry struct {
	// The framing of this telemetry data. If `RAW`, this telemetry will be an arbitrarily sized
	// chunk of the bitstream.
	Framing Framing `protobuf:"varint,1,opt,name=framing,proto3,enum=stellarstation.api.v1.Framing" json:"framing,omitempty"`
	// The payload of this telemetry.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The actual downlink frequency, in Hz, used when receiving `data`, including adjustments for
	// doppler shift.
	DownlinkFrequencyHz uint64 `protobuf:"varint,3,opt,name=downlink_frequency_hz,json=downlinkFrequencyHz,proto3" json:"downlink_frequency_hz,omitempty"`
	// Timestamp when the first byte of `data` was received.
	TimeFirstByteReceived *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time_first_byte_received,json=timeFirstByteReceived,proto3" json:"time_first_byte_received,omitempty"`
	// Timestamp when the last byte of `data` was received.
	TimeLastByteReceived *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time_last_byte_received,json=timeLastByteReceived,proto3" json:"time_last_byte_received,omitempty"`
	// The binary header of the telemetry frame, if `framing` is not `RAW`.
	//
	// * AX25 - This is either Address + Control, or Address + Control + PID. The checksum is not
	//          returned.
	FrameHeader          []byte   `protobuf:"bytes,6,opt,name=frame_header,json=frameHeader,proto3" json:"frame_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Telemetry) Reset()         { *m = Telemetry{} }
func (m *Telemetry) String() string { return proto.CompactTextString(m) }
func (*Telemetry) ProtoMessage()    {}
func (*Telemetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{4}
}
func (m *Telemetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telemetry.Unmarshal(m, b)
}
func (m *Telemetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telemetry.Marshal(b, m, deterministic)
}
func (dst *Telemetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telemetry.Merge(dst, src)
}
func (m *Telemetry) XXX_Size() int {
	return xxx_messageInfo_Telemetry.Size(m)
}
func (m *Telemetry) XXX_DiscardUnknown() {
	xxx_messageInfo_Telemetry.DiscardUnknown(m)
}

var xxx_messageInfo_Telemetry proto.InternalMessageInfo

func (m *Telemetry) GetFraming() Framing {
	if m != nil {
		return m.Framing
	}
	return Framing_BITSTREAM
}

func (m *Telemetry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Telemetry) GetDownlinkFrequencyHz() uint64 {
	if m != nil {
		return m.DownlinkFrequencyHz
	}
	return 0
}

func (m *Telemetry) GetTimeFirstByteReceived() *timestamp.Timestamp {
	if m != nil {
		return m.TimeFirstByteReceived
	}
	return nil
}

func (m *Telemetry) GetTimeLastByteReceived() *timestamp.Timestamp {
	if m != nil {
		return m.TimeLastByteReceived
	}
	return nil
}

func (m *Telemetry) GetFrameHeader() []byte {
	if m != nil {
		return m.FrameHeader
	}
	return nil
}

// Request for the `ListGroundstationPlans` method.
type ListGroundStationPlansRequest struct {
	// The ID of the ground station to list plans for. The ID can be found on the StellarStation
	// Console page for the ground station.
	GroundStationId string `protobuf:"bytes,1,opt,name=ground_station_id,json=groundStationId,proto3" json:"ground_station_id,omitempty"`
	// The start time of the range of plans to list (inclusive). Only plans with an Acquisition of
	// Signal (AOS) at or after this time will be returned. It is an error for the duration between
	// `aos_after` and `aos_before` to be longer than 31 days.
	AosAfter *timestamp.Timestamp `protobuf:"bytes,2,opt,name=aos_after,json=aosAfter,proto3" json:"aos_after,omitempty"`
	// The end time of the range of plans to list (exclusive). Only plans with an Acquisition of
	// Signal (AOS) before this time will be returned. It is an error for the duration between
	// `aos_after` and `aos_before` to be longer than 31 days.
	AosBefore            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=aos_before,json=aosBefore,proto3" json:"aos_before,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListGroundStationPlansRequest) Reset()         { *m = ListGroundStationPlansRequest{} }
func (m *ListGroundStationPlansRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroundStationPlansRequest) ProtoMessage()    {}
func (*ListGroundStationPlansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{5}
}
func (m *ListGroundStationPlansRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroundStationPlansRequest.Unmarshal(m, b)
}
func (m *ListGroundStationPlansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroundStationPlansRequest.Marshal(b, m, deterministic)
}
func (dst *ListGroundStationPlansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroundStationPlansRequest.Merge(dst, src)
}
func (m *ListGroundStationPlansRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroundStationPlansRequest.Size(m)
}
func (m *ListGroundStationPlansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroundStationPlansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroundStationPlansRequest proto.InternalMessageInfo

func (m *ListGroundStationPlansRequest) GetGroundStationId() string {
	if m != nil {
		return m.GroundStationId
	}
	return ""
}

func (m *ListGroundStationPlansRequest) GetAosAfter() *timestamp.Timestamp {
	if m != nil {
		return m.AosAfter
	}
	return nil
}

func (m *ListGroundStationPlansRequest) GetAosBefore() *timestamp.Timestamp {
	if m != nil {
		return m.AosBefore
	}
	return nil
}

// A response from the `ListGroundstationPlans` method.
type ListGroundStationPlansResponse struct {
	// The requested list of plans for the ground station.
	Plan                 []*Plan  `protobuf:"bytes,1,rep,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroundStationPlansResponse) Reset()         { *m = ListGroundStationPlansResponse{} }
func (m *ListGroundStationPlansResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroundStationPlansResponse) ProtoMessage()    {}
func (*ListGroundStationPlansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{6}
}
func (m *ListGroundStationPlansResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroundStationPlansResponse.Unmarshal(m, b)
}
func (m *ListGroundStationPlansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroundStationPlansResponse.Marshal(b, m, deterministic)
}
func (dst *ListGroundStationPlansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroundStationPlansResponse.Merge(dst, src)
}
func (m *ListGroundStationPlansResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroundStationPlansResponse.Size(m)
}
func (m *ListGroundStationPlansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroundStationPlansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroundStationPlansResponse proto.InternalMessageInfo

func (m *ListGroundStationPlansResponse) GetPlan() []*Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

// A scheduled pass. The plan will be executed on its ground station to communicate with its satellite
// during a time range between AOS and LOS, unless explicitly cancelled.
type Plan struct {
	// The ID of this plan.
	PlanId string `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// The status of this plan.
	Status Plan_Status `protobuf:"varint,2,opt,name=status,proto3,enum=stellarstation.api.v1.Plan_Status" json:"status,omitempty"`
	// The TLE used to compute this plan. Always has exactly two items corresponding to line 1 and
	// line 2 of the 2-line TLE format.
	//
	// https://en.wikipedia.org/wiki/Two-line_element_set
	TleLine []string `protobuf:"bytes,3,rep,name=tle_line,json=tleLine,proto3" json:"tle_line,omitempty"`
	// The time of AOS between the ground station and satellite in this plan.
	AosTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=aos_time,json=aosTime,proto3" json:"aos_time,omitempty"`
	// The time of LOS between the ground station and satellite in this plan.
	LosTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=los_time,json=losTime,proto3" json:"los_time,omitempty"`
	// The center frequency, in Hz, for downlinking in this plan. 0 if downlink is not available in
	// this plan.
	DownlinkCenterFrequencyHz uint64 `protobuf:"varint,6,opt,name=downlink_center_frequency_hz,json=downlinkCenterFrequencyHz,proto3" json:"downlink_center_frequency_hz,omitempty"`
	// The center frequency, in Hz, for uplinking in this plan. 0 if uplink is not available in this
	// plan.
	UplinkCenterFrequencyHz uint64 `protobuf:"varint,7,opt,name=uplink_center_frequency_hz,json=uplinkCenterFrequencyHz,proto3" json:"uplink_center_frequency_hz,omitempty"`
	// The max elevation of the plan, in degrees.
	MaxElevationDegrees float64 `protobuf:"fixed64,8,opt,name=max_elevation_degrees,json=maxElevationDegrees,proto3" json:"max_elevation_degrees,omitempty"`
	// The time of max elevation during the plan.
	MaxElevationTime     *timestamp.Timestamp `protobuf:"bytes,9,opt,name=max_elevation_time,json=maxElevationTime,proto3" json:"max_elevation_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_dcdbf0a40554e53c, []int{7}
}
func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (dst *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(dst, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

func (m *Plan) GetStatus() Plan_Status {
	if m != nil {
		return m.Status
	}
	return Plan_RESERVED
}

func (m *Plan) GetTleLine() []string {
	if m != nil {
		return m.TleLine
	}
	return nil
}

func (m *Plan) GetAosTime() *timestamp.Timestamp {
	if m != nil {
		return m.AosTime
	}
	return nil
}

func (m *Plan) GetLosTime() *timestamp.Timestamp {
	if m != nil {
		return m.LosTime
	}
	return nil
}

func (m *Plan) GetDownlinkCenterFrequencyHz() uint64 {
	if m != nil {
		return m.DownlinkCenterFrequencyHz
	}
	return 0
}

func (m *Plan) GetUplinkCenterFrequencyHz() uint64 {
	if m != nil {
		return m.UplinkCenterFrequencyHz
	}
	return 0
}

func (m *Plan) GetMaxElevationDegrees() float64 {
	if m != nil {
		return m.MaxElevationDegrees
	}
	return 0
}

func (m *Plan) GetMaxElevationTime() *timestamp.Timestamp {
	if m != nil {
		return m.MaxElevationTime
	}
	return nil
}

func init() {
	proto.RegisterType((*SatelliteStreamRequest)(nil), "stellarstation.api.v1.SatelliteStreamRequest")
	proto.RegisterType((*SendSatelliteCommandsRequest)(nil), "stellarstation.api.v1.SendSatelliteCommandsRequest")
	proto.RegisterType((*SatelliteStreamResponse)(nil), "stellarstation.api.v1.SatelliteStreamResponse")
	proto.RegisterType((*ReceiveTelemetryResponse)(nil), "stellarstation.api.v1.ReceiveTelemetryResponse")
	proto.RegisterType((*Telemetry)(nil), "stellarstation.api.v1.Telemetry")
	proto.RegisterType((*ListGroundStationPlansRequest)(nil), "stellarstation.api.v1.ListGroundStationPlansRequest")
	proto.RegisterType((*ListGroundStationPlansResponse)(nil), "stellarstation.api.v1.ListGroundStationPlansResponse")
	proto.RegisterType((*Plan)(nil), "stellarstation.api.v1.Plan")
	proto.RegisterEnum("stellarstation.api.v1.Framing", Framing_name, Framing_value)
	proto.RegisterEnum("stellarstation.api.v1.Plan_Status", Plan_Status_name, Plan_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StellarStationServiceClient is the client API for StellarStationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StellarStationServiceClient interface {
	// Lists the plans for a particular ground station.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `ground_station_id`,
	// `aos_after`, or `aos_before` are missing, or the duration between the two times is longer than
	// 31 days.
	ListGroundStationPlans(ctx context.Context, in *ListGroundStationPlansRequest, opts ...grpc.CallOption) (*ListGroundStationPlansResponse, error)
	// Open a stream to a satellite. The returned stream is bi-directional - it can be used by the
	// client to send commands to the satellite and data received from the satellite will be returned
	// as it is made available. All telemetry received from the satellite on reserved passes from this
	// point on will be returned as soon as this method is called. If
	// `SatelliteStreamRequest.stream_id` is specified, any messages that have been buffered for the
	// stream will be returned as well.
	//
	// The stream can be left open for any amount of time and telemetry will be received as available
	// and returned. When the client is done with the stream, it should close it successfully. If the
	// stream is cancelled with an unexpected error at any point, telemetry received before the next
	// call to `OpenSatelliteStream` to resume the stream will be buffered up to 1 minute, and if no
	// call to `OpenSatelliteStream` is made with `stream_id` specified to resume the stream, it will
	// expire in 10 minutes and a call to `OpenSatelliteStream` with that `stream_id` will be closed
	// with a `ABORTED` error.
	//
	// If the satellite is not found or the client is not authorized for it, the stream will be closed
	// with a `NOT_FOUND` error.
	OpenSatelliteStream(ctx context.Context, opts ...grpc.CallOption) (StellarStationService_OpenSatelliteStreamClient, error)
}

type stellarStationServiceClient struct {
	cc *grpc.ClientConn
}

func NewStellarStationServiceClient(cc *grpc.ClientConn) StellarStationServiceClient {
	return &stellarStationServiceClient{cc}
}

func (c *stellarStationServiceClient) ListGroundStationPlans(ctx context.Context, in *ListGroundStationPlansRequest, opts ...grpc.CallOption) (*ListGroundStationPlansResponse, error) {
	out := new(ListGroundStationPlansResponse)
	err := c.cc.Invoke(ctx, "/stellarstation.api.v1.StellarStationService/ListGroundStationPlans", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stellarStationServiceClient) OpenSatelliteStream(ctx context.Context, opts ...grpc.CallOption) (StellarStationService_OpenSatelliteStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StellarStationService_serviceDesc.Streams[0], "/stellarstation.api.v1.StellarStationService/OpenSatelliteStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &stellarStationServiceOpenSatelliteStreamClient{stream}
	return x, nil
}

type StellarStationService_OpenSatelliteStreamClient interface {
	Send(*SatelliteStreamRequest) error
	Recv() (*SatelliteStreamResponse, error)
	grpc.ClientStream
}

type stellarStationServiceOpenSatelliteStreamClient struct {
	grpc.ClientStream
}

func (x *stellarStationServiceOpenSatelliteStreamClient) Send(m *SatelliteStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stellarStationServiceOpenSatelliteStreamClient) Recv() (*SatelliteStreamResponse, error) {
	m := new(SatelliteStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StellarStationServiceServer is the server API for StellarStationService service.
type StellarStationServiceServer interface {
	// Lists the plans for a particular ground station.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `ground_station_id`,
	// `aos_after`, or `aos_before` are missing, or the duration between the two times is longer than
	// 31 days.
	ListGroundStationPlans(context.Context, *ListGroundStationPlansRequest) (*ListGroundStationPlansResponse, error)
	// Open a stream to a satellite. The returned stream is bi-directional - it can be used by the
	// client to send commands to the satellite and data received from the satellite will be returned
	// as it is made available. All telemetry received from the satellite on reserved passes from this
	// point on will be returned as soon as this method is called. If
	// `SatelliteStreamRequest.stream_id` is specified, any messages that have been buffered for the
	// stream will be returned as well.
	//
	// The stream can be left open for any amount of time and telemetry will be received as available
	// and returned. When the client is done with the stream, it should close it successfully. If the
	// stream is cancelled with an unexpected error at any point, telemetry received before the next
	// call to `OpenSatelliteStream` to resume the stream will be buffered up to 1 minute, and if no
	// call to `OpenSatelliteStream` is made with `stream_id` specified to resume the stream, it will
	// expire in 10 minutes and a call to `OpenSatelliteStream` with that `stream_id` will be closed
	// with a `ABORTED` error.
	//
	// If the satellite is not found or the client is not authorized for it, the stream will be closed
	// with a `NOT_FOUND` error.
	OpenSatelliteStream(StellarStationService_OpenSatelliteStreamServer) error
}

func RegisterStellarStationServiceServer(s *grpc.Server, srv StellarStationServiceServer) {
	s.RegisterService(&_StellarStationService_serviceDesc, srv)
}

func _StellarStationService_ListGroundStationPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroundStationPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellarStationServiceServer).ListGroundStationPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellarstation.api.v1.StellarStationService/ListGroundStationPlans",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellarStationServiceServer).ListGroundStationPlans(ctx, req.(*ListGroundStationPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StellarStationService_OpenSatelliteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StellarStationServiceServer).OpenSatelliteStream(&stellarStationServiceOpenSatelliteStreamServer{stream})
}

type StellarStationService_OpenSatelliteStreamServer interface {
	Send(*SatelliteStreamResponse) error
	Recv() (*SatelliteStreamRequest, error)
	grpc.ServerStream
}

type stellarStationServiceOpenSatelliteStreamServer struct {
	grpc.ServerStream
}

func (x *stellarStationServiceOpenSatelliteStreamServer) Send(m *SatelliteStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stellarStationServiceOpenSatelliteStreamServer) Recv() (*SatelliteStreamRequest, error) {
	m := new(SatelliteStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _StellarStationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stellarstation.api.v1.StellarStationService",
	HandlerType: (*StellarStationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGroundStationPlans",
			Handler:    _StellarStationService_ListGroundStationPlans_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenSatelliteStream",
			Handler:       _StellarStationService_OpenSatelliteStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stellarstation/api/v1/stellarstation.proto",
}

func init() {
	proto.RegisterFile("stellarstation/api/v1/stellarstation.proto", fileDescriptor_stellarstation_dcdbf0a40554e53c)
}

var fileDescriptor_stellarstation_dcdbf0a40554e53c = []byte{
	// 953 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xdd, 0x6e, 0xe2, 0x56,
	0x10, 0xc7, 0x63, 0x42, 0x01, 0x0f, 0x49, 0x4a, 0x4f, 0xca, 0xc6, 0x61, 0xd3, 0x5d, 0xd6, 0x57,
	0x28, 0x52, 0xa1, 0xeb, 0x6d, 0xd4, 0x2f, 0xa9, 0x15, 0x1f, 0xce, 0x82, 0x44, 0x77, 0x13, 0x9b,
	0xad, 0x56, 0x7b, 0x63, 0x9d, 0xe0, 0x81, 0xb5, 0xea, 0x0f, 0x6a, 0x1f, 0x68, 0xb2, 0xaa, 0xd4,
	0xab, 0x3e, 0x44, 0x1f, 0xa3, 0xea, 0x03, 0xf4, 0x35, 0x7a, 0xdb, 0x37, 0xa9, 0xce, 0xb1, 0x0d,
	0x21, 0x89, 0xc9, 0xee, 0x9d, 0xcf, 0xcc, 0xfc, 0xe6, 0xcc, 0x8c, 0xff, 0x83, 0x81, 0xe3, 0x88,
	0xa1, 0xeb, 0xd2, 0x30, 0x62, 0x94, 0x39, 0x81, 0xdf, 0xa2, 0x33, 0xa7, 0xb5, 0x78, 0xda, 0x5a,
	0xb7, 0x36, 0x67, 0x61, 0xc0, 0x02, 0x52, 0xbd, 0x61, 0xa5, 0x33, 0xa7, 0xb9, 0x78, 0x5a, 0x7b,
	0x3c, 0x0d, 0x82, 0xa9, 0x8b, 0x2d, 0x11, 0x74, 0x31, 0x9f, 0xb4, 0x98, 0xe3, 0x61, 0xc4, 0xa8,
	0x37, 0x8b, 0x39, 0xf5, 0x3f, 0x09, 0x1e, 0x98, 0x94, 0xb3, 0x0e, 0x43, 0x93, 0x85, 0x48, 0x3d,
	0x03, 0x7f, 0x99, 0x63, 0xc4, 0xc8, 0x13, 0xd8, 0x89, 0x52, 0x8f, 0xe5, 0xd8, 0x8a, 0x54, 0x97,
	0x1a, 0xb2, 0x51, 0x5e, 0xda, 0x06, 0x36, 0x79, 0x08, 0x72, 0x24, 0x18, 0xee, 0xcf, 0x09, 0x7f,
	0x29, 0x36, 0x0c, 0x6c, 0xf2, 0x1b, 0x3c, 0x8e, 0xd0, 0xb7, 0xad, 0x55, 0x92, 0x71, 0xe0, 0x79,
	0xd4, 0xb7, 0x23, 0x2b, 0x8c, 0xaf, 0x50, 0xb6, 0xeb, 0x52, 0xa3, 0xac, 0x3d, 0x6b, 0xde, 0x59,
	0x7c, 0xd3, 0x44, 0xdf, 0x5e, 0xd6, 0xd6, 0x4d, 0xd8, 0xa4, 0xba, 0xfe, 0x96, 0x71, 0x14, 0x6d,
	0xf0, 0x77, 0x64, 0x28, 0x26, 0x8f, 0xea, 0xef, 0x70, 0xb4, 0x29, 0x15, 0xd1, 0x61, 0x2f, 0x98,
	0xb3, 0xd9, 0x9c, 0x59, 0x93, 0x90, 0x7a, 0x8e, 0x3f, 0x15, 0xad, 0xee, 0x69, 0x8f, 0x32, 0xea,
	0x3a, 0x8d, 0xa3, 0x8c, 0xdd, 0x98, 0x4a, 0x8e, 0x44, 0x81, 0x62, 0xd2, 0xa0, 0x92, 0xab, 0x6f,
	0x37, 0x76, 0x8c, 0xf4, 0xa8, 0xfe, 0x2d, 0xc1, 0xc1, 0xad, 0x21, 0x47, 0xb3, 0xc0, 0x8f, 0x70,
	0x7d, 0x84, 0xd2, 0x8d, 0x11, 0x06, 0x50, 0x0b, 0x71, 0x8c, 0xce, 0x02, 0x2d, 0x86, 0x2e, 0x7a,
	0xc8, 0xc2, 0x2b, 0x2b, 0x4c, 0x50, 0x31, 0xf0, 0xb2, 0xd6, 0xca, 0xa8, 0xd2, 0x88, 0xc1, 0x51,
	0xca, 0xa5, 0x37, 0xf6, 0xb7, 0x0c, 0x25, 0xcc, 0xf0, 0x75, 0x00, 0x4a, 0xe9, 0xb3, 0xfa, 0x06,
	0x94, 0xac, 0x1c, 0xe4, 0x7b, 0x90, 0x97, 0x05, 0x89, 0xaa, 0xcb, 0x5a, 0x3d, 0xa3, 0x8e, 0x15,
	0xbc, 0x42, 0xd4, 0x7f, 0x73, 0x20, 0x2f, 0x1d, 0xe4, 0x6b, 0x28, 0x7e, 0xd8, 0xe4, 0xd3, 0x70,
	0x42, 0x20, 0x6f, 0x53, 0x46, 0xc5, 0x28, 0x76, 0x0c, 0xf1, 0x4c, 0x34, 0xa8, 0xda, 0xc1, 0xaf,
	0xbe, 0xeb, 0xf8, 0x3f, 0x5b, 0x13, 0xa1, 0x34, 0x7f, 0x7c, 0x65, 0xbd, 0x7d, 0x27, 0xd4, 0x96,
	0x37, 0xf6, 0x53, 0xe7, 0x69, 0xea, 0xeb, 0xbf, 0x23, 0x26, 0x28, 0x7c, 0x33, 0xac, 0x89, 0x13,
	0x46, 0xcc, 0xba, 0xb8, 0x62, 0x68, 0x25, 0x33, 0xb2, 0x95, 0xbc, 0x68, 0xaf, 0xd6, 0x8c, 0x57,
	0xa9, 0x99, 0xae, 0x52, 0x73, 0x94, 0xae, 0x92, 0x51, 0xe5, 0xec, 0x29, 0x47, 0x3b, 0x57, 0x0c,
	0x93, 0xa1, 0xd9, 0xe4, 0x1c, 0x0e, 0x44, 0x52, 0x97, 0xde, 0xca, 0xf9, 0xd1, 0xbd, 0x39, 0x3f,
	0xe5, 0xe8, 0x90, 0xde, 0x48, 0xf9, 0x04, 0x76, 0x78, 0xeb, 0x68, 0xbd, 0x45, 0x6a, 0x63, 0xa8,
	0x14, 0x44, 0xdf, 0x65, 0x61, 0xeb, 0x0b, 0x93, 0xfa, 0x8f, 0x04, 0x9f, 0x0d, 0x9d, 0x88, 0x3d,
	0x0f, 0x83, 0xb9, 0x6f, 0x9b, 0xf1, 0x00, 0xcf, 0x5c, 0xea, 0x2f, 0xf5, 0x7e, 0x0c, 0x9f, 0x4c,
	0x85, 0xd3, 0x4a, 0xc6, 0xbb, 0x92, 0xde, 0xc7, 0xd3, 0xeb, 0xd4, 0xc0, 0x26, 0x5f, 0x81, 0x4c,
	0x83, 0xc8, 0xa2, 0x13, 0x86, 0x61, 0x22, 0xb8, 0x4d, 0x55, 0x97, 0x68, 0x10, 0xb5, 0x79, 0x2c,
	0xf9, 0x06, 0x80, 0x83, 0x17, 0x38, 0x09, 0x42, 0x4c, 0x16, 0x7d, 0x13, 0xc9, 0xaf, 0xe9, 0x88,
	0x60, 0xf5, 0x1c, 0x1e, 0x65, 0x35, 0x90, 0xc8, 0xaf, 0x05, 0xf9, 0x99, 0x4b, 0x7d, 0x45, 0xaa,
	0x6f, 0x37, 0xca, 0xda, 0xc3, 0x0c, 0xb5, 0x70, 0xc6, 0x10, 0x81, 0xea, 0x5f, 0x79, 0xc8, 0xf3,
	0x23, 0x39, 0x80, 0x22, 0x37, 0xac, 0x3a, 0x2e, 0xf0, 0xe3, 0xc0, 0x26, 0xdf, 0x42, 0x81, 0xe3,
	0xf3, 0x48, 0x74, 0xb9, 0xa7, 0xa9, 0x1b, 0x92, 0x36, 0x4d, 0x11, 0x69, 0x24, 0x04, 0x39, 0x84,
	0x12, 0x73, 0xd1, 0x72, 0x1d, 0x9f, 0x77, 0xba, 0xdd, 0x90, 0x8d, 0x22, 0x73, 0x71, 0xe8, 0xf8,
	0x48, 0x4e, 0x80, 0x8f, 0xc4, 0xe2, 0x2f, 0xf3, 0x3d, 0x84, 0x54, 0xa4, 0x41, 0xc4, 0x4f, 0x1c,
	0x73, 0x53, 0xec, 0x7e, 0xad, 0x14, 0xdd, 0x04, 0xfb, 0x01, 0x8e, 0x96, 0xd2, 0x1f, 0xa3, 0xcf,
	0x30, 0x5c, 0xdf, 0x80, 0x82, 0xd8, 0x80, 0xc3, 0x34, 0xa6, 0x2b, 0x42, 0xae, 0xef, 0xc1, 0x77,
	0x50, 0x9b, 0xcf, 0x32, 0xf1, 0xa2, 0xc0, 0x0f, 0xe2, 0x88, 0xdb, 0xb0, 0x06, 0x55, 0x8f, 0x5e,
	0x5a, 0xe8, 0xe2, 0x22, 0x96, 0x95, 0x8d, 0xd3, 0x10, 0x31, 0x52, 0x4a, 0x75, 0xa9, 0x21, 0x19,
	0xfb, 0x1e, 0xbd, 0xd4, 0x53, 0x5f, 0x2f, 0x76, 0x91, 0x3e, 0x90, 0x75, 0x46, 0xb4, 0x2c, 0xdf,
	0xdb, 0x72, 0xe5, 0x7a, 0x32, 0x6e, 0x56, 0x5f, 0x42, 0x21, 0x7e, 0x2d, 0x64, 0x07, 0x4a, 0x86,
	0x6e, 0xea, 0xc6, 0x4f, 0x7a, 0xaf, 0xb2, 0x45, 0x76, 0x41, 0xd6, 0x5f, 0xeb, 0xdd, 0x57, 0xa3,
	0xc1, 0x8b, 0xe7, 0x15, 0x89, 0x1f, 0xcd, 0x57, 0xdd, 0xae, 0xae, 0xf7, 0xf4, 0x5e, 0x25, 0x47,
	0x00, 0x0a, 0xa7, 0xed, 0xc1, 0x50, 0xef, 0x55, 0xb6, 0xb9, 0xab, 0xdb, 0x7e, 0xd1, 0xd5, 0x87,
	0xfc, 0x98, 0x3f, 0x3e, 0x86, 0x62, 0xfa, 0xd3, 0xbe, 0x0b, 0x72, 0x67, 0x30, 0x32, 0x47, 0x86,
	0xde, 0xfe, 0xb1, 0xb2, 0x45, 0x4a, 0x90, 0x6f, 0xbf, 0xd6, 0x4e, 0x2a, 0x12, 0x29, 0x40, 0x6e,
	0x70, 0x5e, 0xc9, 0x69, 0x7f, 0xe6, 0xa0, 0x6a, 0xc6, 0x7a, 0x49, 0x04, 0x6b, 0x62, 0xb8, 0x70,
	0xc6, 0x48, 0xfe, 0x90, 0xe0, 0xc1, 0xdd, 0x6a, 0x26, 0x5f, 0x66, 0x48, 0x6c, 0xe3, 0xf6, 0xd6,
	0x4e, 0x3e, 0x90, 0x4a, 0x56, 0xe6, 0x12, 0xf6, 0x5f, 0xce, 0xd0, 0xbf, 0xf1, 0x19, 0x22, 0x9f,
	0x67, 0x7d, 0x7b, 0xef, 0xfc, 0x4f, 0x50, 0x6b, 0xbe, 0x6f, 0x78, 0x7c, 0x6b, 0x43, 0xfa, 0x42,
	0xea, 0x74, 0xe0, 0x70, 0x1c, 0x78, 0x77, 0x83, 0x9d, 0x7d, 0x73, 0xcd, 0x7c, 0xc6, 0xdf, 0xf4,
	0x99, 0xf4, 0x66, 0x6f, 0x3d, 0xfa, 0xa2, 0x20, 0x24, 0xf0, 0xec, 0xff, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xb2, 0x5e, 0x08, 0x13, 0x09, 0x00, 0x00,
}
