// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stellarstation/api/v1/stellarstation.proto

package v1 // import "github.com/infostellarinc/go-stellarstation/api/v1"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A type of framing of a binary payload used in satellite communicaation.
type Framing int32

const (
	// No framing done in the API. All payloads are assumed to be pre-framed and ready for
	// transmission to the satellite or API client with no additional processing.
	Framing_BITSTREAM Framing = 0
	// AX.25 (Amateur X.25) framing - https://en.wikipedia.org/wiki/AX.25
	Framing_AX25 Framing = 1
	// No framing or demodulation done in the API. Raw IQ data is sent to the API client with no
	// additional processing.
	Framing_IQ Framing = 2
	// A decoded PNG image frame.
	Framing_IMAGE_PNG Framing = 3
)

var Framing_name = map[int32]string{
	0: "BITSTREAM",
	1: "AX25",
	2: "IQ",
	3: "IMAGE_PNG",
}
var Framing_value = map[string]int32{
	"BITSTREAM": 0,
	"AX25":      1,
	"IQ":        2,
	"IMAGE_PNG": 3,
}

func (x Framing) String() string {
	return proto.EnumName(Framing_name, int32(x))
}
func (Framing) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{0}
}

// A description of the status of a plan.
type Plan_Status int32

const (
	// The plan is reserved for execution in the future at `aos_time`.
	Plan_RESERVED Plan_Status = 0
	// The plan is currently executing and will end in the future at `los_time`.
	Plan_EXECUTING Plan_Status = 1
	// The plan already finished executing successfully.
	Plan_SUCCEEDED Plan_Status = 2
	// The plan failed to execute correctly.
	Plan_FAILED Plan_Status = 3
	// The plan was canceled. This can be explicitly by calling `CancelPlan` or implicit due to
	// cancellation by the ground station in the plan (i.e., due to bad weather).
	Plan_CANCELED Plan_Status = 4
)

var Plan_Status_name = map[int32]string{
	0: "RESERVED",
	1: "EXECUTING",
	2: "SUCCEEDED",
	3: "FAILED",
	4: "CANCELED",
}
var Plan_Status_value = map[string]int32{
	"RESERVED":  0,
	"EXECUTING": 1,
	"SUCCEEDED": 2,
	"FAILED":    3,
	"CANCELED":  4,
}

func (x Plan_Status) String() string {
	return proto.EnumName(Plan_Status_name, int32(x))
}
func (Plan_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{12, 0}
}

// Request for the `OpenSatelliteStream` method.
type SatelliteStreamRequest struct {
	// The ID of the satellite to open a stream with. The ID of a satellite can be found on the
	// StellarStation Console page for the satellite.
	SatelliteId string `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	// The `SatelliteStreamResponse.stream_id` from a previously opened stream to resume. If the
	// specified stream has already expired or been closed, the stream is closed with a `ABORTED`
	// error.
	StreamId string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// A request to send on the satellite stream. Currently only command sending to the satellite is
	// supported. The request does not need to be filled on the first request to
	// `OpenSatelliteStream`.
	//
	// Types that are valid to be assigned to Request:
	//	*SatelliteStreamRequest_SendSatelliteCommandsRequest
	Request isSatelliteStreamRequest_Request `protobuf_oneof:"Request"`
	// The `Framing` types to accept, for satellites that have been configured for multiple framings
	// (e.g., IQ + AX25). If empty, all framings produced by the satellite will be returned.
	AcceptedFraming      []Framing `protobuf:"varint,4,rep,packed,name=accepted_framing,json=acceptedFraming,proto3,enum=stellarstation.api.v1.Framing" json:"accepted_framing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SatelliteStreamRequest) Reset()         { *m = SatelliteStreamRequest{} }
func (m *SatelliteStreamRequest) String() string { return proto.CompactTextString(m) }
func (*SatelliteStreamRequest) ProtoMessage()    {}
func (*SatelliteStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{0}
}
func (m *SatelliteStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatelliteStreamRequest.Unmarshal(m, b)
}
func (m *SatelliteStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatelliteStreamRequest.Marshal(b, m, deterministic)
}
func (dst *SatelliteStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatelliteStreamRequest.Merge(dst, src)
}
func (m *SatelliteStreamRequest) XXX_Size() int {
	return xxx_messageInfo_SatelliteStreamRequest.Size(m)
}
func (m *SatelliteStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SatelliteStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SatelliteStreamRequest proto.InternalMessageInfo

func (m *SatelliteStreamRequest) GetSatelliteId() string {
	if m != nil {
		return m.SatelliteId
	}
	return ""
}

func (m *SatelliteStreamRequest) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

type isSatelliteStreamRequest_Request interface {
	isSatelliteStreamRequest_Request()
}

type SatelliteStreamRequest_SendSatelliteCommandsRequest struct {
	SendSatelliteCommandsRequest *SendSatelliteCommandsRequest `protobuf:"bytes,3,opt,name=send_satellite_commands_request,json=sendSatelliteCommandsRequest,proto3,oneof"`
}

func (*SatelliteStreamRequest_SendSatelliteCommandsRequest) isSatelliteStreamRequest_Request() {}

func (m *SatelliteStreamRequest) GetRequest() isSatelliteStreamRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *SatelliteStreamRequest) GetSendSatelliteCommandsRequest() *SendSatelliteCommandsRequest {
	if x, ok := m.GetRequest().(*SatelliteStreamRequest_SendSatelliteCommandsRequest); ok {
		return x.SendSatelliteCommandsRequest
	}
	return nil
}

func (m *SatelliteStreamRequest) GetAcceptedFraming() []Framing {
	if m != nil {
		return m.AcceptedFraming
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SatelliteStreamRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SatelliteStreamRequest_OneofMarshaler, _SatelliteStreamRequest_OneofUnmarshaler, _SatelliteStreamRequest_OneofSizer, []interface{}{
		(*SatelliteStreamRequest_SendSatelliteCommandsRequest)(nil),
	}
}

func _SatelliteStreamRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SatelliteStreamRequest)
	// Request
	switch x := m.Request.(type) {
	case *SatelliteStreamRequest_SendSatelliteCommandsRequest:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SendSatelliteCommandsRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SatelliteStreamRequest.Request has unexpected type %T", x)
	}
	return nil
}

func _SatelliteStreamRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SatelliteStreamRequest)
	switch tag {
	case 3: // Request.send_satellite_commands_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SendSatelliteCommandsRequest)
		err := b.DecodeMessage(msg)
		m.Request = &SatelliteStreamRequest_SendSatelliteCommandsRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SatelliteStreamRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SatelliteStreamRequest)
	// Request
	switch x := m.Request.(type) {
	case *SatelliteStreamRequest_SendSatelliteCommandsRequest:
		s := proto.Size(x.SendSatelliteCommandsRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A request to send commands to a satellite.
//
// Next ID: 1
type SendSatelliteCommandsRequest struct {
	// The command frames to send to the satellite. All commands will be transmitted in sequence
	// immediately, during which time telemetry will not be received. After all commands have been
	// transmitted, telemetry receive will be immediately re-enabled. The maximum size of each command
	// is 2MB. If a command larger than 2MB is received, the stream will be closed with a
	// `RESOURCE_EXHAUSTED` error.
	Command              [][]byte `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSatelliteCommandsRequest) Reset()         { *m = SendSatelliteCommandsRequest{} }
func (m *SendSatelliteCommandsRequest) String() string { return proto.CompactTextString(m) }
func (*SendSatelliteCommandsRequest) ProtoMessage()    {}
func (*SendSatelliteCommandsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{1}
}
func (m *SendSatelliteCommandsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSatelliteCommandsRequest.Unmarshal(m, b)
}
func (m *SendSatelliteCommandsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSatelliteCommandsRequest.Marshal(b, m, deterministic)
}
func (dst *SendSatelliteCommandsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSatelliteCommandsRequest.Merge(dst, src)
}
func (m *SendSatelliteCommandsRequest) XXX_Size() int {
	return xxx_messageInfo_SendSatelliteCommandsRequest.Size(m)
}
func (m *SendSatelliteCommandsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSatelliteCommandsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSatelliteCommandsRequest proto.InternalMessageInfo

func (m *SendSatelliteCommandsRequest) GetCommand() [][]byte {
	if m != nil {
		return m.Command
	}
	return nil
}

// A response from the `OpenSatelliteStream` method.
type SatelliteStreamResponse struct {
	// The ID of this stream, which can be used in a subsequent call to `OpenSatelliteStream` to
	// resume this stream on interruption (e.g., if a network failure causes the connection to be
	// closed mid-stream). Telemetry received on a previously opened stream with no current listener
	// will be buffered for a maximum of 1 minute, and the stream itself will be cancelled and no more
	// buffering will occur if no client resumes the stream with `OpenSatelliteStream` within 10
	// minutes.
	StreamId string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// A response on the stream. Currently the only type of response is telemetry received from the
	// satellite.
	//
	// Types that are valid to be assigned to Response:
	//	*SatelliteStreamResponse_ReceiveTelemetryResponse
	Response             isSatelliteStreamResponse_Response `protobuf_oneof:"Response"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *SatelliteStreamResponse) Reset()         { *m = SatelliteStreamResponse{} }
func (m *SatelliteStreamResponse) String() string { return proto.CompactTextString(m) }
func (*SatelliteStreamResponse) ProtoMessage()    {}
func (*SatelliteStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{2}
}
func (m *SatelliteStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SatelliteStreamResponse.Unmarshal(m, b)
}
func (m *SatelliteStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SatelliteStreamResponse.Marshal(b, m, deterministic)
}
func (dst *SatelliteStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SatelliteStreamResponse.Merge(dst, src)
}
func (m *SatelliteStreamResponse) XXX_Size() int {
	return xxx_messageInfo_SatelliteStreamResponse.Size(m)
}
func (m *SatelliteStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SatelliteStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SatelliteStreamResponse proto.InternalMessageInfo

func (m *SatelliteStreamResponse) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

type isSatelliteStreamResponse_Response interface {
	isSatelliteStreamResponse_Response()
}

type SatelliteStreamResponse_ReceiveTelemetryResponse struct {
	ReceiveTelemetryResponse *ReceiveTelemetryResponse `protobuf:"bytes,2,opt,name=receive_telemetry_response,json=receiveTelemetryResponse,proto3,oneof"`
}

func (*SatelliteStreamResponse_ReceiveTelemetryResponse) isSatelliteStreamResponse_Response() {}

func (m *SatelliteStreamResponse) GetResponse() isSatelliteStreamResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SatelliteStreamResponse) GetReceiveTelemetryResponse() *ReceiveTelemetryResponse {
	if x, ok := m.GetResponse().(*SatelliteStreamResponse_ReceiveTelemetryResponse); ok {
		return x.ReceiveTelemetryResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SatelliteStreamResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SatelliteStreamResponse_OneofMarshaler, _SatelliteStreamResponse_OneofUnmarshaler, _SatelliteStreamResponse_OneofSizer, []interface{}{
		(*SatelliteStreamResponse_ReceiveTelemetryResponse)(nil),
	}
}

func _SatelliteStreamResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SatelliteStreamResponse)
	// Response
	switch x := m.Response.(type) {
	case *SatelliteStreamResponse_ReceiveTelemetryResponse:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReceiveTelemetryResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SatelliteStreamResponse.Response has unexpected type %T", x)
	}
	return nil
}

func _SatelliteStreamResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SatelliteStreamResponse)
	switch tag {
	case 2: // Response.receive_telemetry_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReceiveTelemetryResponse)
		err := b.DecodeMessage(msg)
		m.Response = &SatelliteStreamResponse_ReceiveTelemetryResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SatelliteStreamResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SatelliteStreamResponse)
	// Response
	switch x := m.Response.(type) {
	case *SatelliteStreamResponse_ReceiveTelemetryResponse:
		s := proto.Size(x.ReceiveTelemetryResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// A response from a satellite containing telemetry.
type ReceiveTelemetryResponse struct {
	// The telemetry received.
	Telemetry            *Telemetry `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReceiveTelemetryResponse) Reset()         { *m = ReceiveTelemetryResponse{} }
func (m *ReceiveTelemetryResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveTelemetryResponse) ProtoMessage()    {}
func (*ReceiveTelemetryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{3}
}
func (m *ReceiveTelemetryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveTelemetryResponse.Unmarshal(m, b)
}
func (m *ReceiveTelemetryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveTelemetryResponse.Marshal(b, m, deterministic)
}
func (dst *ReceiveTelemetryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveTelemetryResponse.Merge(dst, src)
}
func (m *ReceiveTelemetryResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveTelemetryResponse.Size(m)
}
func (m *ReceiveTelemetryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveTelemetryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveTelemetryResponse proto.InternalMessageInfo

func (m *ReceiveTelemetryResponse) GetTelemetry() *Telemetry {
	if m != nil {
		return m.Telemetry
	}
	return nil
}

// A chunk or frame of telemetry data that has been received from a satellite.
type Telemetry struct {
	// The framing of this telemetry data. If `RAW`, this telemetry will be an arbitrarily sized
	// chunk of the bitstream.
	Framing Framing `protobuf:"varint,1,opt,name=framing,proto3,enum=stellarstation.api.v1.Framing" json:"framing,omitempty"`
	// The payload of this telemetry.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The actual downlink frequency, in Hz, used when receiving `data`, including adjustments for
	// doppler shift.
	DownlinkFrequencyHz uint64 `protobuf:"varint,3,opt,name=downlink_frequency_hz,json=downlinkFrequencyHz,proto3" json:"downlink_frequency_hz,omitempty"`
	// Timestamp when the first byte of `data` was received.
	TimeFirstByteReceived *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time_first_byte_received,json=timeFirstByteReceived,proto3" json:"time_first_byte_received,omitempty"`
	// Timestamp when the last byte of `data` was received.
	TimeLastByteReceived *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time_last_byte_received,json=timeLastByteReceived,proto3" json:"time_last_byte_received,omitempty"`
	// The binary header of the telemetry frame, if `framing` is not `RAW`.
	//
	// * AX25 - This is either Address + Control, or Address + Control + PID. The checksum is not
	//          returned.
	FrameHeader          []byte   `protobuf:"bytes,6,opt,name=frame_header,json=frameHeader,proto3" json:"frame_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Telemetry) Reset()         { *m = Telemetry{} }
func (m *Telemetry) String() string { return proto.CompactTextString(m) }
func (*Telemetry) ProtoMessage()    {}
func (*Telemetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{4}
}
func (m *Telemetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telemetry.Unmarshal(m, b)
}
func (m *Telemetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telemetry.Marshal(b, m, deterministic)
}
func (dst *Telemetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telemetry.Merge(dst, src)
}
func (m *Telemetry) XXX_Size() int {
	return xxx_messageInfo_Telemetry.Size(m)
}
func (m *Telemetry) XXX_DiscardUnknown() {
	xxx_messageInfo_Telemetry.DiscardUnknown(m)
}

var xxx_messageInfo_Telemetry proto.InternalMessageInfo

func (m *Telemetry) GetFraming() Framing {
	if m != nil {
		return m.Framing
	}
	return Framing_BITSTREAM
}

func (m *Telemetry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Telemetry) GetDownlinkFrequencyHz() uint64 {
	if m != nil {
		return m.DownlinkFrequencyHz
	}
	return 0
}

func (m *Telemetry) GetTimeFirstByteReceived() *timestamp.Timestamp {
	if m != nil {
		return m.TimeFirstByteReceived
	}
	return nil
}

func (m *Telemetry) GetTimeLastByteReceived() *timestamp.Timestamp {
	if m != nil {
		return m.TimeLastByteReceived
	}
	return nil
}

func (m *Telemetry) GetFrameHeader() []byte {
	if m != nil {
		return m.FrameHeader
	}
	return nil
}

// Request for the `CancelPlan` method.
type CancelPlanRequest struct {
	// The id of the plan to cancel, i.e., the value of `Plan.id`.
	PlanId               string   `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPlanRequest) Reset()         { *m = CancelPlanRequest{} }
func (m *CancelPlanRequest) String() string { return proto.CompactTextString(m) }
func (*CancelPlanRequest) ProtoMessage()    {}
func (*CancelPlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{5}
}
func (m *CancelPlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPlanRequest.Unmarshal(m, b)
}
func (m *CancelPlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPlanRequest.Marshal(b, m, deterministic)
}
func (dst *CancelPlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPlanRequest.Merge(dst, src)
}
func (m *CancelPlanRequest) XXX_Size() int {
	return xxx_messageInfo_CancelPlanRequest.Size(m)
}
func (m *CancelPlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPlanRequest proto.InternalMessageInfo

func (m *CancelPlanRequest) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

// Response for the `CancelPlan` method.
type CancelPlanResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelPlanResponse) Reset()         { *m = CancelPlanResponse{} }
func (m *CancelPlanResponse) String() string { return proto.CompactTextString(m) }
func (*CancelPlanResponse) ProtoMessage()    {}
func (*CancelPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{6}
}
func (m *CancelPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelPlanResponse.Unmarshal(m, b)
}
func (m *CancelPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelPlanResponse.Marshal(b, m, deterministic)
}
func (dst *CancelPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelPlanResponse.Merge(dst, src)
}
func (m *CancelPlanResponse) XXX_Size() int {
	return xxx_messageInfo_CancelPlanResponse.Size(m)
}
func (m *CancelPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelPlanResponse proto.InternalMessageInfo

// Request for the `ListUpcomingAvailablePasses` method.
type ListUpcomingAvailablePassesRequest struct {
	// The ID of the satellite to list passes for. The ID of a satellite can be found on the
	// StellarStation Console page for the satellite.
	SatelliteId          string   `protobuf:"bytes,1,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUpcomingAvailablePassesRequest) Reset()         { *m = ListUpcomingAvailablePassesRequest{} }
func (m *ListUpcomingAvailablePassesRequest) String() string { return proto.CompactTextString(m) }
func (*ListUpcomingAvailablePassesRequest) ProtoMessage()    {}
func (*ListUpcomingAvailablePassesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{7}
}
func (m *ListUpcomingAvailablePassesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUpcomingAvailablePassesRequest.Unmarshal(m, b)
}
func (m *ListUpcomingAvailablePassesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUpcomingAvailablePassesRequest.Marshal(b, m, deterministic)
}
func (dst *ListUpcomingAvailablePassesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUpcomingAvailablePassesRequest.Merge(dst, src)
}
func (m *ListUpcomingAvailablePassesRequest) XXX_Size() int {
	return xxx_messageInfo_ListUpcomingAvailablePassesRequest.Size(m)
}
func (m *ListUpcomingAvailablePassesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUpcomingAvailablePassesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUpcomingAvailablePassesRequest proto.InternalMessageInfo

func (m *ListUpcomingAvailablePassesRequest) GetSatelliteId() string {
	if m != nil {
		return m.SatelliteId
	}
	return ""
}

// Response for the `ListUpcomingAvailablePasses` method.
type ListUpcomingAvailablePassesResponse struct {
	// The upcoming, schedulable passes for the satellite.
	Pass                 []*Pass  `protobuf:"bytes,1,rep,name=pass,proto3" json:"pass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUpcomingAvailablePassesResponse) Reset()         { *m = ListUpcomingAvailablePassesResponse{} }
func (m *ListUpcomingAvailablePassesResponse) String() string { return proto.CompactTextString(m) }
func (*ListUpcomingAvailablePassesResponse) ProtoMessage()    {}
func (*ListUpcomingAvailablePassesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{8}
}
func (m *ListUpcomingAvailablePassesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUpcomingAvailablePassesResponse.Unmarshal(m, b)
}
func (m *ListUpcomingAvailablePassesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUpcomingAvailablePassesResponse.Marshal(b, m, deterministic)
}
func (dst *ListUpcomingAvailablePassesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUpcomingAvailablePassesResponse.Merge(dst, src)
}
func (m *ListUpcomingAvailablePassesResponse) XXX_Size() int {
	return xxx_messageInfo_ListUpcomingAvailablePassesResponse.Size(m)
}
func (m *ListUpcomingAvailablePassesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUpcomingAvailablePassesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUpcomingAvailablePassesResponse proto.InternalMessageInfo

func (m *ListUpcomingAvailablePassesResponse) GetPass() []*Pass {
	if m != nil {
		return m.Pass
	}
	return nil
}

// Request for the `ReservePass` method.
type ReservePassRequest struct {
	// The token that specifies the pass, as returned in `Pass.reservation_token`.
	ReservationToken     string   `protobuf:"bytes,1,opt,name=reservation_token,json=reservationToken,proto3" json:"reservation_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservePassRequest) Reset()         { *m = ReservePassRequest{} }
func (m *ReservePassRequest) String() string { return proto.CompactTextString(m) }
func (*ReservePassRequest) ProtoMessage()    {}
func (*ReservePassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{9}
}
func (m *ReservePassRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservePassRequest.Unmarshal(m, b)
}
func (m *ReservePassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservePassRequest.Marshal(b, m, deterministic)
}
func (dst *ReservePassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservePassRequest.Merge(dst, src)
}
func (m *ReservePassRequest) XXX_Size() int {
	return xxx_messageInfo_ReservePassRequest.Size(m)
}
func (m *ReservePassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservePassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservePassRequest proto.InternalMessageInfo

func (m *ReservePassRequest) GetReservationToken() string {
	if m != nil {
		return m.ReservationToken
	}
	return ""
}

// Response for the `ReservePass` method.
type ReservePassResponse struct {
	// The reserved plan.
	Plan                 *Plan    `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservePassResponse) Reset()         { *m = ReservePassResponse{} }
func (m *ReservePassResponse) String() string { return proto.CompactTextString(m) }
func (*ReservePassResponse) ProtoMessage()    {}
func (*ReservePassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{10}
}
func (m *ReservePassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservePassResponse.Unmarshal(m, b)
}
func (m *ReservePassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservePassResponse.Marshal(b, m, deterministic)
}
func (dst *ReservePassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservePassResponse.Merge(dst, src)
}
func (m *ReservePassResponse) XXX_Size() int {
	return xxx_messageInfo_ReservePassResponse.Size(m)
}
func (m *ReservePassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservePassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReservePassResponse proto.InternalMessageInfo

func (m *ReservePassResponse) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

// A pass during which a satellite can be communicated with from a given ground station.
type Pass struct {
	// A unique token for this pass that can be used for scheduling it.
	ReservationToken string `protobuf:"bytes,1,opt,name=reservation_token,json=reservationToken,proto3" json:"reservation_token,omitempty"`
	// The time of Acquisition of Signal (AOS) between the ground station and satellite in this pass.
	AosTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=aos_time,json=aosTime,proto3" json:"aos_time,omitempty"`
	// The time of Loss of Signal (LOS) between the ground station and satellite in this pass.
	LosTime *timestamp.Timestamp `protobuf:"bytes,3,opt,name=los_time,json=losTime,proto3" json:"los_time,omitempty"`
	// The latitude, in degrees, of the ground station's location.
	GroundStationLatitude float64 `protobuf:"fixed64,4,opt,name=ground_station_latitude,json=groundStationLatitude,proto3" json:"ground_station_latitude,omitempty"`
	// The longitude, in degrees, of the ground station's location.
	GroundStationLongitude float64 `protobuf:"fixed64,5,opt,name=ground_station_longitude,json=groundStationLongitude,proto3" json:"ground_station_longitude,omitempty"`
	// The ISO 3166-1 alpha-2 2-letter country code for the ground station's location.
	// See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
	GroundStationCountryCode string `protobuf:"bytes,6,opt,name=ground_station_country_code,json=groundStationCountryCode,proto3" json:"ground_station_country_code,omitempty"`
	// The max elevation during the pass, in degrees.
	MaxElevationDegrees float64 `protobuf:"fixed64,7,opt,name=max_elevation_degrees,json=maxElevationDegrees,proto3" json:"max_elevation_degrees,omitempty"`
	// The time of the max elevation during the pass.
	MaxElevationTime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=max_elevation_time,json=maxElevationTime,proto3" json:"max_elevation_time,omitempty"`
	// The center frequency, in Hz, for downlinking in this pass. 0 if downlink is not available in
	// this pass.
	DownlinkCenterFrequencyHz uint64 `protobuf:"varint,9,opt,name=downlink_center_frequency_hz,json=downlinkCenterFrequencyHz,proto3" json:"downlink_center_frequency_hz,omitempty"`
	// The center frequency, in Hz, for uplinking in this pass. 0 if uplink is not available in
	// this pass.
	UplinkCenterFrequencyHz uint64   `protobuf:"varint,10,opt,name=uplink_center_frequency_hz,json=uplinkCenterFrequencyHz,proto3" json:"uplink_center_frequency_hz,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Pass) Reset()         { *m = Pass{} }
func (m *Pass) String() string { return proto.CompactTextString(m) }
func (*Pass) ProtoMessage()    {}
func (*Pass) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{11}
}
func (m *Pass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pass.Unmarshal(m, b)
}
func (m *Pass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pass.Marshal(b, m, deterministic)
}
func (dst *Pass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pass.Merge(dst, src)
}
func (m *Pass) XXX_Size() int {
	return xxx_messageInfo_Pass.Size(m)
}
func (m *Pass) XXX_DiscardUnknown() {
	xxx_messageInfo_Pass.DiscardUnknown(m)
}

var xxx_messageInfo_Pass proto.InternalMessageInfo

func (m *Pass) GetReservationToken() string {
	if m != nil {
		return m.ReservationToken
	}
	return ""
}

func (m *Pass) GetAosTime() *timestamp.Timestamp {
	if m != nil {
		return m.AosTime
	}
	return nil
}

func (m *Pass) GetLosTime() *timestamp.Timestamp {
	if m != nil {
		return m.LosTime
	}
	return nil
}

func (m *Pass) GetGroundStationLatitude() float64 {
	if m != nil {
		return m.GroundStationLatitude
	}
	return 0
}

func (m *Pass) GetGroundStationLongitude() float64 {
	if m != nil {
		return m.GroundStationLongitude
	}
	return 0
}

func (m *Pass) GetGroundStationCountryCode() string {
	if m != nil {
		return m.GroundStationCountryCode
	}
	return ""
}

func (m *Pass) GetMaxElevationDegrees() float64 {
	if m != nil {
		return m.MaxElevationDegrees
	}
	return 0
}

func (m *Pass) GetMaxElevationTime() *timestamp.Timestamp {
	if m != nil {
		return m.MaxElevationTime
	}
	return nil
}

func (m *Pass) GetDownlinkCenterFrequencyHz() uint64 {
	if m != nil {
		return m.DownlinkCenterFrequencyHz
	}
	return 0
}

func (m *Pass) GetUplinkCenterFrequencyHz() uint64 {
	if m != nil {
		return m.UplinkCenterFrequencyHz
	}
	return 0
}

// A plan, specifying a time range within which a satellite will be communicated with.
type Plan struct {
	// The unique ID of the plan.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The id of the satellite to be tracked in the plan.
	SatelliteId string `protobuf:"bytes,2,opt,name=satellite_id,json=satelliteId,proto3" json:"satellite_id,omitempty"`
	// The status of this plan.
	Status Plan_Status `protobuf:"varint,3,opt,name=status,proto3,enum=stellarstation.api.v1.Plan_Status" json:"status,omitempty"`
	// The time of Acquisition of Signal (AOS) between the ground station and satellite in this plan.
	AosTime *timestamp.Timestamp `protobuf:"bytes,4,opt,name=aos_time,json=aosTime,proto3" json:"aos_time,omitempty"`
	// The time of Loss of Signal (LOS) between the ground station and satellite in this plan.
	LosTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=los_time,json=losTime,proto3" json:"los_time,omitempty"`
	// The latitude, in degrees, of the ground station's location.
	GroundStationLatitude float64 `protobuf:"fixed64,6,opt,name=ground_station_latitude,json=groundStationLatitude,proto3" json:"ground_station_latitude,omitempty"`
	// The longitude, in degrees, of the ground station's location.
	GroundStationLongitude float64 `protobuf:"fixed64,7,opt,name=ground_station_longitude,json=groundStationLongitude,proto3" json:"ground_station_longitude,omitempty"`
	// The ISO 3166-1 alpha-2 2-letter country code for the ground station's location.
	// See https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
	GroundStationCountryCode string `protobuf:"bytes,8,opt,name=ground_station_country_code,json=groundStationCountryCode,proto3" json:"ground_station_country_code,omitempty"`
	// The max elevation during the plan, in degrees.
	MaxElevationDegrees float64 `protobuf:"fixed64,9,opt,name=max_elevation_degrees,json=maxElevationDegrees,proto3" json:"max_elevation_degrees,omitempty"`
	// The time of the max elevation during the plan.
	MaxElevationTime *timestamp.Timestamp `protobuf:"bytes,10,opt,name=max_elevation_time,json=maxElevationTime,proto3" json:"max_elevation_time,omitempty"`
	// The center frequency, in Hz, for downlinking in this plan. 0 if downlink is not available in
	// this plan.
	DownlinkCenterFrequencyHz uint64 `protobuf:"varint,11,opt,name=downlink_center_frequency_hz,json=downlinkCenterFrequencyHz,proto3" json:"downlink_center_frequency_hz,omitempty"`
	// The center frequency, in Hz, for uplinking in this plan. 0 if uplink is not available in
	// this plan.
	UplinkCenterFrequencyHz uint64   `protobuf:"varint,12,opt,name=uplink_center_frequency_hz,json=uplinkCenterFrequencyHz,proto3" json:"uplink_center_frequency_hz,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_stellarstation_c4691b40f7c28426, []int{12}
}
func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (dst *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(dst, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetSatelliteId() string {
	if m != nil {
		return m.SatelliteId
	}
	return ""
}

func (m *Plan) GetStatus() Plan_Status {
	if m != nil {
		return m.Status
	}
	return Plan_RESERVED
}

func (m *Plan) GetAosTime() *timestamp.Timestamp {
	if m != nil {
		return m.AosTime
	}
	return nil
}

func (m *Plan) GetLosTime() *timestamp.Timestamp {
	if m != nil {
		return m.LosTime
	}
	return nil
}

func (m *Plan) GetGroundStationLatitude() float64 {
	if m != nil {
		return m.GroundStationLatitude
	}
	return 0
}

func (m *Plan) GetGroundStationLongitude() float64 {
	if m != nil {
		return m.GroundStationLongitude
	}
	return 0
}

func (m *Plan) GetGroundStationCountryCode() string {
	if m != nil {
		return m.GroundStationCountryCode
	}
	return ""
}

func (m *Plan) GetMaxElevationDegrees() float64 {
	if m != nil {
		return m.MaxElevationDegrees
	}
	return 0
}

func (m *Plan) GetMaxElevationTime() *timestamp.Timestamp {
	if m != nil {
		return m.MaxElevationTime
	}
	return nil
}

func (m *Plan) GetDownlinkCenterFrequencyHz() uint64 {
	if m != nil {
		return m.DownlinkCenterFrequencyHz
	}
	return 0
}

func (m *Plan) GetUplinkCenterFrequencyHz() uint64 {
	if m != nil {
		return m.UplinkCenterFrequencyHz
	}
	return 0
}

func init() {
	proto.RegisterType((*SatelliteStreamRequest)(nil), "stellarstation.api.v1.SatelliteStreamRequest")
	proto.RegisterType((*SendSatelliteCommandsRequest)(nil), "stellarstation.api.v1.SendSatelliteCommandsRequest")
	proto.RegisterType((*SatelliteStreamResponse)(nil), "stellarstation.api.v1.SatelliteStreamResponse")
	proto.RegisterType((*ReceiveTelemetryResponse)(nil), "stellarstation.api.v1.ReceiveTelemetryResponse")
	proto.RegisterType((*Telemetry)(nil), "stellarstation.api.v1.Telemetry")
	proto.RegisterType((*CancelPlanRequest)(nil), "stellarstation.api.v1.CancelPlanRequest")
	proto.RegisterType((*CancelPlanResponse)(nil), "stellarstation.api.v1.CancelPlanResponse")
	proto.RegisterType((*ListUpcomingAvailablePassesRequest)(nil), "stellarstation.api.v1.ListUpcomingAvailablePassesRequest")
	proto.RegisterType((*ListUpcomingAvailablePassesResponse)(nil), "stellarstation.api.v1.ListUpcomingAvailablePassesResponse")
	proto.RegisterType((*ReservePassRequest)(nil), "stellarstation.api.v1.ReservePassRequest")
	proto.RegisterType((*ReservePassResponse)(nil), "stellarstation.api.v1.ReservePassResponse")
	proto.RegisterType((*Pass)(nil), "stellarstation.api.v1.Pass")
	proto.RegisterType((*Plan)(nil), "stellarstation.api.v1.Plan")
	proto.RegisterEnum("stellarstation.api.v1.Framing", Framing_name, Framing_value)
	proto.RegisterEnum("stellarstation.api.v1.Plan_Status", Plan_Status_name, Plan_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StellarStationServiceClient is the client API for StellarStationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StellarStationServiceClient interface {
	// Cancel a previously reserved upcoming plan. Cancelling the plan will cause it to not be
	// executed. This action cannot be undone, but it is still possible to reserve the corresponding
	// pass again by calling `ListUpcomingAvailablePasses` and `ReservePass` as usual - this will
	// cause a new plan to be reserved. The plan cannot be cancelled less than ten minutes before
	// AOS.
	//
	// Canceling a plan may incur a charge based on the time left to AOS. See our cancellation policy
	// for details.
	//
	// If the plan is not found, the request will return a `NOT_FOUND` error.
	//
	// If the plan has already been canceled or is less than ten minutes away from its AOS, the
	// request will return a `FAILED_PRECONDITION` error.
	//
	// If the plan is ongoing or has already finished executing, the request will return a
	// `OUT_OF_RANGE` error.
	CancelPlan(ctx context.Context, in *CancelPlanRequest, opts ...grpc.CallOption) (*CancelPlanResponse, error)
	// Lists upcoming passes for a satellite. Passes that can be scheduled for the satellite with an
	// Acquisition of Signal (AOS) within 14 days from now will be returned. This method does not
	// reserve passes in any way - it is possible for a pass that is returned by this method to be
	// unschedulable when actually trying to schedule because a conflict appeared during that time.
	//
	// If the satellite is not found or the client is not authorized for it, the request will return
	// a `NOT_FOUND` error.
	ListUpcomingAvailablePasses(ctx context.Context, in *ListUpcomingAvailablePassesRequest, opts ...grpc.CallOption) (*ListUpcomingAvailablePassesResponse, error)
	// Open a stream to a satellite. The returned stream is bi-directional - it can be used by the
	// client to send commands to the satellite and data received from the satellite will be returned
	// as it is made available. All telemetry received from the satellite on reserved passes from this
	// point on will be returned as soon as this method is called. If
	// `SatelliteStreamRequest.stream_id` is specified, any messages that have been buffered for the
	// stream will be returned as well.
	//
	// The stream can be left open for any amount of time and telemetry will be received as available
	// and returned. When the client is done with the stream, it should close it successfully. If the
	// stream is cancelled with an unexpected error at any point, telemetry received before the next
	// call to `OpenSatelliteStream` to resume the stream will be buffered up to 1 minute, and if no
	// call to `OpenSatelliteStream` is made with `stream_id` specified to resume the stream, it will
	// expire in 10 minutes and a call to `OpenSatelliteStream` with that `stream_id` will be closed
	// with a `ABORTED` error.
	//
	// If the satellite is not found or the client is not authorized for it, the stream will be closed
	// with a `NOT_FOUND` error.
	OpenSatelliteStream(ctx context.Context, opts ...grpc.CallOption) (StellarStationService_OpenSatelliteStreamClient, error)
	// Reserves a pass for later execution as a plan. The pass must be specified by a
	// `reservation_token` returned in another method like `ListUpcomingAvailablePasses` and its
	// `aos_time` must be at least one hour in the future.
	//
	// If the `reservation_token` is invalid, the request will return an `INVALID_ARGUMENT` error.
	//
	// If the requested pass cannot be scheduled due to a conflict with existing plans or other
	// scheduling constraints, the request will return a `FAILED_PRECONDITION` error. This includes
	// if the pass `aos_time` is less than one hour in the future.
	//
	// Note that the reservation_token may have become unreservable since it was fetched. If that's
	// the case, the call to `ReservePass` will fail with a 'FAILED_PRECONDITION' error and
	// `ListUpcomingAvailablePasses` should be called again to get a fresh list of reservable passes.
	// The pass must be scheduled at least one hour in advance of `aos_time` or it will be rejected.
	ReservePass(ctx context.Context, in *ReservePassRequest, opts ...grpc.CallOption) (*ReservePassResponse, error)
}

type stellarStationServiceClient struct {
	cc *grpc.ClientConn
}

func NewStellarStationServiceClient(cc *grpc.ClientConn) StellarStationServiceClient {
	return &stellarStationServiceClient{cc}
}

func (c *stellarStationServiceClient) CancelPlan(ctx context.Context, in *CancelPlanRequest, opts ...grpc.CallOption) (*CancelPlanResponse, error) {
	out := new(CancelPlanResponse)
	err := c.cc.Invoke(ctx, "/stellarstation.api.v1.StellarStationService/CancelPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stellarStationServiceClient) ListUpcomingAvailablePasses(ctx context.Context, in *ListUpcomingAvailablePassesRequest, opts ...grpc.CallOption) (*ListUpcomingAvailablePassesResponse, error) {
	out := new(ListUpcomingAvailablePassesResponse)
	err := c.cc.Invoke(ctx, "/stellarstation.api.v1.StellarStationService/ListUpcomingAvailablePasses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stellarStationServiceClient) OpenSatelliteStream(ctx context.Context, opts ...grpc.CallOption) (StellarStationService_OpenSatelliteStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StellarStationService_serviceDesc.Streams[0], "/stellarstation.api.v1.StellarStationService/OpenSatelliteStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &stellarStationServiceOpenSatelliteStreamClient{stream}
	return x, nil
}

type StellarStationService_OpenSatelliteStreamClient interface {
	Send(*SatelliteStreamRequest) error
	Recv() (*SatelliteStreamResponse, error)
	grpc.ClientStream
}

type stellarStationServiceOpenSatelliteStreamClient struct {
	grpc.ClientStream
}

func (x *stellarStationServiceOpenSatelliteStreamClient) Send(m *SatelliteStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stellarStationServiceOpenSatelliteStreamClient) Recv() (*SatelliteStreamResponse, error) {
	m := new(SatelliteStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stellarStationServiceClient) ReservePass(ctx context.Context, in *ReservePassRequest, opts ...grpc.CallOption) (*ReservePassResponse, error) {
	out := new(ReservePassResponse)
	err := c.cc.Invoke(ctx, "/stellarstation.api.v1.StellarStationService/ReservePass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StellarStationServiceServer is the server API for StellarStationService service.
type StellarStationServiceServer interface {
	// Cancel a previously reserved upcoming plan. Cancelling the plan will cause it to not be
	// executed. This action cannot be undone, but it is still possible to reserve the corresponding
	// pass again by calling `ListUpcomingAvailablePasses` and `ReservePass` as usual - this will
	// cause a new plan to be reserved. The plan cannot be cancelled less than ten minutes before
	// AOS.
	//
	// Canceling a plan may incur a charge based on the time left to AOS. See our cancellation policy
	// for details.
	//
	// If the plan is not found, the request will return a `NOT_FOUND` error.
	//
	// If the plan has already been canceled or is less than ten minutes away from its AOS, the
	// request will return a `FAILED_PRECONDITION` error.
	//
	// If the plan is ongoing or has already finished executing, the request will return a
	// `OUT_OF_RANGE` error.
	CancelPlan(context.Context, *CancelPlanRequest) (*CancelPlanResponse, error)
	// Lists upcoming passes for a satellite. Passes that can be scheduled for the satellite with an
	// Acquisition of Signal (AOS) within 14 days from now will be returned. This method does not
	// reserve passes in any way - it is possible for a pass that is returned by this method to be
	// unschedulable when actually trying to schedule because a conflict appeared during that time.
	//
	// If the satellite is not found or the client is not authorized for it, the request will return
	// a `NOT_FOUND` error.
	ListUpcomingAvailablePasses(context.Context, *ListUpcomingAvailablePassesRequest) (*ListUpcomingAvailablePassesResponse, error)
	// Open a stream to a satellite. The returned stream is bi-directional - it can be used by the
	// client to send commands to the satellite and data received from the satellite will be returned
	// as it is made available. All telemetry received from the satellite on reserved passes from this
	// point on will be returned as soon as this method is called. If
	// `SatelliteStreamRequest.stream_id` is specified, any messages that have been buffered for the
	// stream will be returned as well.
	//
	// The stream can be left open for any amount of time and telemetry will be received as available
	// and returned. When the client is done with the stream, it should close it successfully. If the
	// stream is cancelled with an unexpected error at any point, telemetry received before the next
	// call to `OpenSatelliteStream` to resume the stream will be buffered up to 1 minute, and if no
	// call to `OpenSatelliteStream` is made with `stream_id` specified to resume the stream, it will
	// expire in 10 minutes and a call to `OpenSatelliteStream` with that `stream_id` will be closed
	// with a `ABORTED` error.
	//
	// If the satellite is not found or the client is not authorized for it, the stream will be closed
	// with a `NOT_FOUND` error.
	OpenSatelliteStream(StellarStationService_OpenSatelliteStreamServer) error
	// Reserves a pass for later execution as a plan. The pass must be specified by a
	// `reservation_token` returned in another method like `ListUpcomingAvailablePasses` and its
	// `aos_time` must be at least one hour in the future.
	//
	// If the `reservation_token` is invalid, the request will return an `INVALID_ARGUMENT` error.
	//
	// If the requested pass cannot be scheduled due to a conflict with existing plans or other
	// scheduling constraints, the request will return a `FAILED_PRECONDITION` error. This includes
	// if the pass `aos_time` is less than one hour in the future.
	//
	// Note that the reservation_token may have become unreservable since it was fetched. If that's
	// the case, the call to `ReservePass` will fail with a 'FAILED_PRECONDITION' error and
	// `ListUpcomingAvailablePasses` should be called again to get a fresh list of reservable passes.
	// The pass must be scheduled at least one hour in advance of `aos_time` or it will be rejected.
	ReservePass(context.Context, *ReservePassRequest) (*ReservePassResponse, error)
}

func RegisterStellarStationServiceServer(s *grpc.Server, srv StellarStationServiceServer) {
	s.RegisterService(&_StellarStationService_serviceDesc, srv)
}

func _StellarStationService_CancelPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellarStationServiceServer).CancelPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellarstation.api.v1.StellarStationService/CancelPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellarStationServiceServer).CancelPlan(ctx, req.(*CancelPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StellarStationService_ListUpcomingAvailablePasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUpcomingAvailablePassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellarStationServiceServer).ListUpcomingAvailablePasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellarstation.api.v1.StellarStationService/ListUpcomingAvailablePasses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellarStationServiceServer).ListUpcomingAvailablePasses(ctx, req.(*ListUpcomingAvailablePassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StellarStationService_OpenSatelliteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StellarStationServiceServer).OpenSatelliteStream(&stellarStationServiceOpenSatelliteStreamServer{stream})
}

type StellarStationService_OpenSatelliteStreamServer interface {
	Send(*SatelliteStreamResponse) error
	Recv() (*SatelliteStreamRequest, error)
	grpc.ServerStream
}

type stellarStationServiceOpenSatelliteStreamServer struct {
	grpc.ServerStream
}

func (x *stellarStationServiceOpenSatelliteStreamServer) Send(m *SatelliteStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stellarStationServiceOpenSatelliteStreamServer) Recv() (*SatelliteStreamRequest, error) {
	m := new(SatelliteStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StellarStationService_ReservePass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReservePassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StellarStationServiceServer).ReservePass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stellarstation.api.v1.StellarStationService/ReservePass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StellarStationServiceServer).ReservePass(ctx, req.(*ReservePassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StellarStationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stellarstation.api.v1.StellarStationService",
	HandlerType: (*StellarStationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelPlan",
			Handler:    _StellarStationService_CancelPlan_Handler,
		},
		{
			MethodName: "ListUpcomingAvailablePasses",
			Handler:    _StellarStationService_ListUpcomingAvailablePasses_Handler,
		},
		{
			MethodName: "ReservePass",
			Handler:    _StellarStationService_ReservePass_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenSatelliteStream",
			Handler:       _StellarStationService_OpenSatelliteStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stellarstation/api/v1/stellarstation.proto",
}

func init() {
	proto.RegisterFile("stellarstation/api/v1/stellarstation.proto", fileDescriptor_stellarstation_c4691b40f7c28426)
}

var fileDescriptor_stellarstation_c4691b40f7c28426 = []byte{
	// 1164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x97, 0xdd, 0x72, 0xda, 0x46,
	0x14, 0xc7, 0x2d, 0xc0, 0x7c, 0x1c, 0x68, 0x4a, 0xd6, 0x71, 0xac, 0xe0, 0x4c, 0x43, 0xd4, 0x1b,
	0x92, 0x36, 0xd0, 0x90, 0x49, 0xc7, 0x49, 0xa7, 0xed, 0x60, 0x2c, 0xdb, 0xcc, 0x38, 0xae, 0x23,
	0xe1, 0x4c, 0x26, 0x37, 0x9a, 0xb5, 0xb4, 0x60, 0x4d, 0x84, 0x44, 0xb5, 0x0b, 0xb5, 0x33, 0x7d,
	0x8c, 0x3e, 0x46, 0xef, 0xfa, 0x1e, 0xbd, 0xee, 0x65, 0x5f, 0xa1, 0x6f, 0xd0, 0xd9, 0xd5, 0x0a,
	0xf3, 0x61, 0x61, 0xc7, 0x69, 0xef, 0xd0, 0x9e, 0xf3, 0x3b, 0x7b, 0xf6, 0xec, 0xff, 0xec, 0x2e,
	0xf0, 0x98, 0x32, 0xe2, 0x79, 0x38, 0xa4, 0x0c, 0x33, 0x37, 0xf0, 0x1b, 0x78, 0xe8, 0x36, 0xc6,
	0x4f, 0x1b, 0xb3, 0xa3, 0xf5, 0x61, 0x18, 0xb0, 0x00, 0xad, 0xcf, 0x8d, 0xe2, 0xa1, 0x5b, 0x1f,
	0x3f, 0xad, 0x3c, 0xe8, 0x07, 0x41, 0xdf, 0x23, 0x0d, 0xe1, 0x74, 0x32, 0xea, 0x35, 0x98, 0x3b,
	0x20, 0x94, 0xe1, 0xc1, 0x30, 0xe2, 0xb4, 0xdf, 0x53, 0x70, 0xd7, 0xc4, 0x9c, 0x75, 0x19, 0x31,
	0x59, 0x48, 0xf0, 0xc0, 0x20, 0x3f, 0x8f, 0x08, 0x65, 0xe8, 0x21, 0x94, 0x68, 0x6c, 0xb1, 0x5c,
	0x47, 0x55, 0xaa, 0x4a, 0xad, 0x60, 0x14, 0x27, 0x63, 0x1d, 0x07, 0x6d, 0x42, 0x81, 0x0a, 0x86,
	0xdb, 0x53, 0xc2, 0x9e, 0x8f, 0x06, 0x3a, 0x0e, 0xfa, 0x15, 0x1e, 0x50, 0xe2, 0x3b, 0xd6, 0x45,
	0x10, 0x3b, 0x18, 0x0c, 0xb0, 0xef, 0x50, 0x2b, 0x8c, 0xa6, 0x50, 0xd3, 0x55, 0xa5, 0x56, 0x6c,
	0x3e, 0xab, 0x5f, 0x9a, 0x7c, 0xdd, 0x24, 0xbe, 0x33, 0xc9, 0xad, 0x2d, 0x59, 0x99, 0xdd, 0xfe,
	0x8a, 0x71, 0x9f, 0x2e, 0xb1, 0xa3, 0x0e, 0x94, 0xb1, 0x6d, 0x93, 0x21, 0x23, 0x8e, 0xd5, 0x0b,
	0xf1, 0xc0, 0xf5, 0xfb, 0x6a, 0xa6, 0x9a, 0xae, 0xdd, 0x6a, 0x7e, 0x91, 0x30, 0xdd, 0x6e, 0xe4,
	0x65, 0x7c, 0x1e, 0x73, 0x72, 0x60, 0xbb, 0x00, 0x39, 0x19, 0x55, 0xdb, 0x82, 0xfb, 0xcb, 0xb2,
	0x42, 0x2a, 0xe4, 0xe4, 0x22, 0xd5, 0x54, 0x35, 0x5d, 0x2b, 0x19, 0xf1, 0xa7, 0xf6, 0x87, 0x02,
	0x1b, 0x0b, 0x85, 0xa6, 0xc3, 0xc0, 0xa7, 0x64, 0xb6, 0x8c, 0xca, 0x5c, 0x19, 0x03, 0xa8, 0x84,
	0xc4, 0x26, 0xee, 0x98, 0x58, 0x8c, 0x78, 0x64, 0x40, 0x58, 0x78, 0x6e, 0x85, 0x12, 0x15, 0x45,
	0x2f, 0x36, 0x1b, 0x09, 0x4b, 0x32, 0x22, 0xb0, 0x1b, 0x73, 0xf1, 0x8c, 0xfb, 0x2b, 0x86, 0x1a,
	0x26, 0xd8, 0xb6, 0x01, 0xf2, 0xf1, 0x6f, 0xed, 0x1d, 0xa8, 0x49, 0x31, 0xd0, 0x0f, 0x50, 0x98,
	0x24, 0x24, 0xb2, 0x2e, 0x36, 0xab, 0x09, 0x79, 0x5c, 0xc0, 0x17, 0x88, 0xf6, 0x57, 0x0a, 0x0a,
	0x13, 0x03, 0xda, 0x82, 0x5c, 0xbc, 0x4d, 0x3c, 0xd6, 0xd5, 0xdb, 0x14, 0xbb, 0x23, 0x04, 0x19,
	0x07, 0x33, 0x2c, 0x4a, 0x51, 0x32, 0xc4, 0x6f, 0xd4, 0x84, 0x75, 0x27, 0xf8, 0xc5, 0xf7, 0x5c,
	0xff, 0xbd, 0xd5, 0x13, 0x6a, 0xf3, 0xed, 0x73, 0xeb, 0xf4, 0x83, 0x50, 0x5c, 0xc6, 0x58, 0x8b,
	0x8d, 0xbb, 0xb1, 0x6d, 0xff, 0x03, 0x32, 0x41, 0xe5, 0xdd, 0x61, 0xf5, 0xdc, 0x90, 0x32, 0xeb,
	0xe4, 0x9c, 0x11, 0x4b, 0xd6, 0xc8, 0x51, 0x33, 0x62, 0x79, 0x95, 0x7a, 0xd4, 0x4e, 0xf5, 0xb8,
	0x9d, 0xea, 0xdd, 0xb8, 0x9d, 0x8c, 0x75, 0xce, 0xee, 0x72, 0x74, 0xfb, 0x9c, 0x11, 0x59, 0x34,
	0x07, 0xbd, 0x86, 0x0d, 0x11, 0xd4, 0xc3, 0x0b, 0x31, 0x57, 0xaf, 0x8c, 0x79, 0x87, 0xa3, 0x07,
	0x78, 0x2e, 0xe4, 0x43, 0x28, 0xf1, 0xa5, 0x13, 0xeb, 0x94, 0x60, 0x87, 0x84, 0x6a, 0x56, 0xac,
	0xbb, 0x28, 0xc6, 0xf6, 0xc5, 0x90, 0xf6, 0x35, 0xdc, 0x6e, 0x63, 0xdf, 0x26, 0xde, 0x91, 0x87,
	0xfd, 0x58, 0x9b, 0x1b, 0x90, 0x1b, 0x7a, 0xd8, 0xbf, 0xd0, 0x58, 0x96, 0x7f, 0x76, 0x1c, 0xed,
	0x0e, 0xa0, 0x69, 0x6f, 0xb9, 0xf5, 0x7b, 0xa0, 0x1d, 0xb8, 0x94, 0x1d, 0x0f, 0xed, 0x80, 0x97,
	0xb9, 0x35, 0xc6, 0xae, 0x87, 0x4f, 0x3c, 0x72, 0x84, 0x29, 0x25, 0xf4, 0xfa, 0x87, 0x84, 0xf6,
	0x06, 0xbe, 0x5c, 0x1a, 0x48, 0xca, 0xa9, 0x01, 0x99, 0x21, 0xa6, 0x54, 0x55, 0xaa, 0xe9, 0x5a,
	0xb1, 0xb9, 0x99, 0xb0, 0xfb, 0x1c, 0x32, 0x84, 0xa3, 0xd6, 0x02, 0x64, 0x10, 0x4a, 0xc2, 0xb1,
	0x88, 0x14, 0x27, 0xf4, 0x15, 0xdc, 0x0e, 0xc5, 0xa8, 0xc0, 0x2c, 0x16, 0xbc, 0x27, 0xbe, 0xcc,
	0xaa, 0x3c, 0x65, 0xe8, 0xf2, 0x71, 0x6d, 0x17, 0xd6, 0x66, 0x42, 0x4c, 0xa5, 0xe2, 0x61, 0x5f,
	0x8a, 0x3a, 0x31, 0x15, 0x5e, 0x2d, 0xe1, 0xa8, 0xfd, 0x99, 0x81, 0x0c, 0x8f, 0xf0, 0x51, 0xb3,
	0xa3, 0xe7, 0x90, 0xc7, 0x01, 0xb5, 0xf8, 0x26, 0xcb, 0x3e, 0x5e, 0x26, 0x86, 0x1c, 0x0e, 0x28,
	0xff, 0xe2, 0x98, 0x17, 0x63, 0xe9, 0xab, 0x31, 0x4f, 0x62, 0xdf, 0xc2, 0x46, 0x3f, 0x0c, 0x46,
	0xfc, 0x40, 0x8e, 0xd6, 0x61, 0x79, 0x98, 0xb9, 0x6c, 0xe4, 0x10, 0xa1, 0x6e, 0xc5, 0x58, 0x8f,
	0xcc, 0x66, 0x64, 0x3d, 0x90, 0x46, 0xb4, 0x05, 0xea, 0x3c, 0x17, 0xf8, 0xfd, 0x08, 0x5c, 0x15,
	0xe0, 0xdd, 0x59, 0x30, 0xb6, 0xa2, 0xef, 0x61, 0x73, 0x8e, 0xb4, 0x83, 0x91, 0xcf, 0x8f, 0x2f,
	0x3b, 0x70, 0x88, 0xd0, 0x6d, 0xc1, 0x50, 0x67, 0xe0, 0x76, 0xe4, 0xd0, 0x0e, 0x1c, 0xc2, 0x7b,
	0x78, 0x80, 0xcf, 0x2c, 0xe2, 0x11, 0x59, 0x4d, 0x87, 0xf4, 0x43, 0x42, 0xa8, 0x9a, 0x13, 0xb3,
	0xae, 0x0d, 0xf0, 0x99, 0x1e, 0xdb, 0x76, 0x22, 0x13, 0xda, 0x07, 0x34, 0xcb, 0x88, 0x2a, 0xe5,
	0xaf, 0xac, 0x52, 0x79, 0x3a, 0x98, 0x28, 0xd7, 0x8f, 0x70, 0x7f, 0x72, 0x82, 0xd8, 0xc4, 0x67,
	0x24, 0x9c, 0x3d, 0x48, 0x0a, 0xe2, 0x20, 0xb9, 0x17, 0xfb, 0xb4, 0x85, 0xcb, 0xf4, 0x71, 0xf2,
	0x1d, 0x54, 0x46, 0xc3, 0x44, 0x1c, 0x04, 0xbe, 0x11, 0x79, 0x2c, 0xc0, 0xda, 0xdf, 0xab, 0x90,
	0xe1, 0xfa, 0x42, 0xb7, 0x20, 0x35, 0xe9, 0xaa, 0x94, 0xeb, 0x2c, 0xf4, 0x5b, 0x6a, 0xf1, 0x52,
	0x7e, 0x09, 0x59, 0x5e, 0xef, 0x11, 0x15, 0xea, 0xb8, 0xd5, 0xd4, 0x96, 0xe8, 0xb7, 0x6e, 0x0a,
	0x4f, 0x43, 0x12, 0x33, 0x92, 0xcc, 0xdc, 0x4c, 0x92, 0xab, 0xff, 0x89, 0x24, 0xb3, 0x37, 0x95,
	0x64, 0xee, 0x53, 0x24, 0x99, 0xbf, 0xa9, 0x24, 0x0b, 0x1f, 0x2b, 0x49, 0xf8, 0x1f, 0x24, 0x59,
	0xfc, 0x34, 0x49, 0x96, 0x96, 0x4b, 0xf2, 0x10, 0xb2, 0x91, 0x58, 0x50, 0x09, 0xf2, 0x86, 0x6e,
	0xea, 0xc6, 0x1b, 0x7d, 0xa7, 0xbc, 0x82, 0x3e, 0x83, 0x82, 0xfe, 0x56, 0x6f, 0x1f, 0x77, 0x3b,
	0x87, 0x7b, 0x65, 0x85, 0x7f, 0x9a, 0xc7, 0xed, 0xb6, 0xae, 0xef, 0xe8, 0x3b, 0xe5, 0x14, 0x02,
	0xc8, 0xee, 0xb6, 0x3a, 0x07, 0xfa, 0x4e, 0x39, 0xcd, 0xb9, 0x76, 0xeb, 0xb0, 0xad, 0xf3, 0xaf,
	0xcc, 0xe3, 0x17, 0x90, 0x93, 0x57, 0x39, 0x67, 0xb6, 0x3b, 0x5d, 0xb3, 0x6b, 0xe8, 0xad, 0x57,
	0xe5, 0x15, 0x94, 0x87, 0x4c, 0xeb, 0x6d, 0xf3, 0x79, 0x59, 0x41, 0x59, 0x48, 0x75, 0x5e, 0x97,
	0x53, 0xdc, 0xa1, 0xf3, 0xaa, 0xb5, 0xa7, 0x5b, 0x47, 0x87, 0x7b, 0xe5, 0x74, 0xf3, 0x9f, 0x34,
	0xac, 0x9b, 0x91, 0xa6, 0xe5, 0x26, 0x99, 0x24, 0x1c, 0xbb, 0x36, 0x41, 0x18, 0xe0, 0xe2, 0x2a,
	0x43, 0xb5, 0x04, 0xe5, 0x2f, 0xdc, 0x8d, 0x95, 0x47, 0xd7, 0xf0, 0x94, 0x97, 0xc3, 0x6f, 0x0a,
	0x6c, 0x2e, 0xb9, 0xcf, 0xd0, 0x8b, 0x84, 0x50, 0x57, 0x5f, 0xa6, 0x95, 0x97, 0x37, 0x41, 0x65,
	0x5a, 0x67, 0xb0, 0xf6, 0xd3, 0x90, 0xf8, 0x73, 0x4f, 0x4c, 0xf4, 0x24, 0xe9, 0x6d, 0x7d, 0xe9,
	0x9b, 0xbf, 0x52, 0xbf, 0xae, 0x7b, 0x34, 0x6b, 0x4d, 0xf9, 0x46, 0x41, 0x0e, 0x14, 0xa7, 0x2e,
	0x51, 0xf4, 0x28, 0xf1, 0x2d, 0x3a, 0x7f, 0x57, 0x57, 0x1e, 0x5f, 0xc7, 0x55, 0xbe, 0x4a, 0x7b,
	0x70, 0xcf, 0x0e, 0x06, 0x97, 0x03, 0xdb, 0x6b, 0xe6, 0xcc, 0xf0, 0x11, 0xef, 0xa6, 0x23, 0xe5,
	0x5d, 0xb3, 0xef, 0xb2, 0xd3, 0xd1, 0x49, 0xdd, 0x0e, 0x06, 0x0d, 0xd7, 0xef, 0x05, 0x12, 0x76,
	0x7d, 0xbb, 0xd1, 0x0f, 0x9e, 0x5c, 0xfa, 0xef, 0xea, 0x24, 0x2b, 0x5a, 0xf1, 0xd9, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x62, 0x97, 0x00, 0x56, 0x7d, 0x0d, 0x00, 0x00,
}
