// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stellarstation/api/v1/transport.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	monitoring "github.com/infostellarinc/go-stellarstation/api/v1/monitoring"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A type of framing of a binary payload used in satellite communication.
type Framing int32

const (
	// No framing done in the API. All payloads are assumed to be pre-framed and ready for
	// transmission to the satellite or API client with no additional processing.
	Framing_BITSTREAM Framing = 0
	// AX.25 (Amateur X.25) framing - https://en.wikipedia.org/wiki/AX.25
	Framing_AX25 Framing = 1
	// No framing or demodulation done in the API. Raw IQ data is sent to the API client with no
	// additional processing.
	Framing_IQ Framing = 2
	// A decoded PNG image frame.
	Framing_IMAGE_PNG Framing = 3
	// A decoded JPEG image.
	Framing_IMAGE_JPEG Framing = 4
	// Completely arbitrary, freeform text contained in a frame.
	Framing_FREE_TEXT_UTF8 Framing = 5
	// A waterfall diagram. This is actually for the whole plan and does not correspond to an
	// individual frame.
	Framing_WATERFALL Framing = 6
)

var Framing_name = map[int32]string{
	0: "BITSTREAM",
	1: "AX25",
	2: "IQ",
	3: "IMAGE_PNG",
	4: "IMAGE_JPEG",
	5: "FREE_TEXT_UTF8",
	6: "WATERFALL",
}

var Framing_value = map[string]int32{
	"BITSTREAM":      0,
	"AX25":           1,
	"IQ":             2,
	"IMAGE_PNG":      3,
	"IMAGE_JPEG":     4,
	"FREE_TEXT_UTF8": 5,
	"WATERFALL":      6,
}

func (x Framing) String() string {
	return proto.EnumName(Framing_name, int32(x))
}

func (Framing) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a5cbae65d14ae041, []int{0}
}

// A chunk or frame of telemetry data that has been received from a satellite.
type Telemetry struct {
	// The framing of this telemetry data.
	Framing Framing `protobuf:"varint,1,opt,name=framing,proto3,enum=stellarstation.api.v1.Framing" json:"framing,omitempty"`
	// The payload of this telemetry.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The actual downlink frequency, in Hz, used when receiving `data`, including adjustments for
	// doppler shift.
	DownlinkFrequencyHz uint64 `protobuf:"varint,3,opt,name=downlink_frequency_hz,json=downlinkFrequencyHz,proto3" json:"downlink_frequency_hz,omitempty"`
	// Timestamp when the first byte of `data` was received.
	TimeFirstByteReceived *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time_first_byte_received,json=timeFirstByteReceived,proto3" json:"time_first_byte_received,omitempty"`
	// Timestamp when the last byte of `data` was received.
	TimeLastByteReceived *timestamp.Timestamp `protobuf:"bytes,5,opt,name=time_last_byte_received,json=timeLastByteReceived,proto3" json:"time_last_byte_received,omitempty"`
	// The binary header of the telemetry frame available for certain framing types.
	//
	// * AX25      - This is either Address + Control, or Address + Control + PID. The checksum is not
	//               returned.
	// * BITSTREAM - Streams for certain protocols such as CCSDS may contain frame headers according
	//               to the applicable standards.
	FrameHeader          []byte   `protobuf:"bytes,6,opt,name=frame_header,json=frameHeader,proto3" json:"frame_header,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Telemetry) Reset()         { *m = Telemetry{} }
func (m *Telemetry) String() string { return proto.CompactTextString(m) }
func (*Telemetry) ProtoMessage()    {}
func (*Telemetry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5cbae65d14ae041, []int{0}
}

func (m *Telemetry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Telemetry.Unmarshal(m, b)
}
func (m *Telemetry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Telemetry.Marshal(b, m, deterministic)
}
func (m *Telemetry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Telemetry.Merge(m, src)
}
func (m *Telemetry) XXX_Size() int {
	return xxx_messageInfo_Telemetry.Size(m)
}
func (m *Telemetry) XXX_DiscardUnknown() {
	xxx_messageInfo_Telemetry.DiscardUnknown(m)
}

var xxx_messageInfo_Telemetry proto.InternalMessageInfo

func (m *Telemetry) GetFraming() Framing {
	if m != nil {
		return m.Framing
	}
	return Framing_BITSTREAM
}

func (m *Telemetry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Telemetry) GetDownlinkFrequencyHz() uint64 {
	if m != nil {
		return m.DownlinkFrequencyHz
	}
	return 0
}

func (m *Telemetry) GetTimeFirstByteReceived() *timestamp.Timestamp {
	if m != nil {
		return m.TimeFirstByteReceived
	}
	return nil
}

func (m *Telemetry) GetTimeLastByteReceived() *timestamp.Timestamp {
	if m != nil {
		return m.TimeLastByteReceived
	}
	return nil
}

func (m *Telemetry) GetFrameHeader() []byte {
	if m != nil {
		return m.FrameHeader
	}
	return nil
}

// An event that occurred while processing the stream. A `StreamEvent` will have one of several
// types of event payloads corresponding to event types. Many of these payloads will be empty,
// depending on the context of an event, but are still returned as messages to allow future
// extension.
type StreamEvent struct {
	// The ID of the request this event corresponds to, copied from
	// `SatelliteStreamRequest.request_id` when present. If the event doesn't correspond to a request,
	// this is always empty.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Timestamp of the event occurrence
	Timestamp *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// A stream event payload.
	//
	// Types that are valid to be assigned to Event:
	//	*StreamEvent_CommandSent
	//	*StreamEvent_PlanMonitoringEvent
	Event                isStreamEvent_Event `protobuf_oneof:"Event"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StreamEvent) Reset()         { *m = StreamEvent{} }
func (m *StreamEvent) String() string { return proto.CompactTextString(m) }
func (*StreamEvent) ProtoMessage()    {}
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5cbae65d14ae041, []int{1}
}

func (m *StreamEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamEvent.Unmarshal(m, b)
}
func (m *StreamEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamEvent.Marshal(b, m, deterministic)
}
func (m *StreamEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamEvent.Merge(m, src)
}
func (m *StreamEvent) XXX_Size() int {
	return xxx_messageInfo_StreamEvent.Size(m)
}
func (m *StreamEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StreamEvent proto.InternalMessageInfo

func (m *StreamEvent) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *StreamEvent) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_CommandSent struct {
	CommandSent *StreamEvent_CommandSentFromGroundStation `protobuf:"bytes,2,opt,name=command_sent,json=commandSent,proto3,oneof"`
}

type StreamEvent_PlanMonitoringEvent struct {
	PlanMonitoringEvent *PlanMonitoringEvent `protobuf:"bytes,3,opt,name=plan_monitoring_event,json=planMonitoringEvent,proto3,oneof"`
}

func (*StreamEvent_CommandSent) isStreamEvent_Event() {}

func (*StreamEvent_PlanMonitoringEvent) isStreamEvent_Event() {}

func (m *StreamEvent) GetEvent() isStreamEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StreamEvent) GetCommandSent() *StreamEvent_CommandSentFromGroundStation {
	if x, ok := m.GetEvent().(*StreamEvent_CommandSent); ok {
		return x.CommandSent
	}
	return nil
}

func (m *StreamEvent) GetPlanMonitoringEvent() *PlanMonitoringEvent {
	if x, ok := m.GetEvent().(*StreamEvent_PlanMonitoringEvent); ok {
		return x.PlanMonitoringEvent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StreamEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StreamEvent_CommandSent)(nil),
		(*StreamEvent_PlanMonitoringEvent)(nil),
	}
}

// An event indicating the commands in the request were sent by the ground station through its
// radio.
type StreamEvent_CommandSentFromGroundStation struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamEvent_CommandSentFromGroundStation) Reset() {
	*m = StreamEvent_CommandSentFromGroundStation{}
}
func (m *StreamEvent_CommandSentFromGroundStation) String() string { return proto.CompactTextString(m) }
func (*StreamEvent_CommandSentFromGroundStation) ProtoMessage()    {}
func (*StreamEvent_CommandSentFromGroundStation) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5cbae65d14ae041, []int{1, 0}
}

func (m *StreamEvent_CommandSentFromGroundStation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamEvent_CommandSentFromGroundStation.Unmarshal(m, b)
}
func (m *StreamEvent_CommandSentFromGroundStation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamEvent_CommandSentFromGroundStation.Marshal(b, m, deterministic)
}
func (m *StreamEvent_CommandSentFromGroundStation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamEvent_CommandSentFromGroundStation.Merge(m, src)
}
func (m *StreamEvent_CommandSentFromGroundStation) XXX_Size() int {
	return xxx_messageInfo_StreamEvent_CommandSentFromGroundStation.Size(m)
}
func (m *StreamEvent_CommandSentFromGroundStation) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamEvent_CommandSentFromGroundStation.DiscardUnknown(m)
}

var xxx_messageInfo_StreamEvent_CommandSentFromGroundStation proto.InternalMessageInfo

// A monitoring event that occurred during the execution of the plan. Information about the current
// configuration of the ground station and state of components is returned to provide information
// that can help to troubleshoot issues with the plan.
type PlanMonitoringEvent struct {
	// The ID of the plan being monitored.
	PlanId string `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	// Channel set ID
	ChannelSetId string `protobuf:"bytes,5,opt,name=channel_set_id,json=channelSetId,proto3" json:"channel_set_id,omitempty"`
	// Types that are valid to be assigned to Info:
	//	*PlanMonitoringEvent_GroundStationConfiguration
	//	*PlanMonitoringEvent_GroundStationState
	//	*PlanMonitoringEvent_GroundStationEvent
	Info                 isPlanMonitoringEvent_Info `protobuf_oneof:"Info"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PlanMonitoringEvent) Reset()         { *m = PlanMonitoringEvent{} }
func (m *PlanMonitoringEvent) String() string { return proto.CompactTextString(m) }
func (*PlanMonitoringEvent) ProtoMessage()    {}
func (*PlanMonitoringEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5cbae65d14ae041, []int{2}
}

func (m *PlanMonitoringEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanMonitoringEvent.Unmarshal(m, b)
}
func (m *PlanMonitoringEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanMonitoringEvent.Marshal(b, m, deterministic)
}
func (m *PlanMonitoringEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanMonitoringEvent.Merge(m, src)
}
func (m *PlanMonitoringEvent) XXX_Size() int {
	return xxx_messageInfo_PlanMonitoringEvent.Size(m)
}
func (m *PlanMonitoringEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanMonitoringEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PlanMonitoringEvent proto.InternalMessageInfo

func (m *PlanMonitoringEvent) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

func (m *PlanMonitoringEvent) GetChannelSetId() string {
	if m != nil {
		return m.ChannelSetId
	}
	return ""
}

type isPlanMonitoringEvent_Info interface {
	isPlanMonitoringEvent_Info()
}

type PlanMonitoringEvent_GroundStationConfiguration struct {
	GroundStationConfiguration *monitoring.GroundStationConfiguration `protobuf:"bytes,2,opt,name=ground_station_configuration,json=groundStationConfiguration,proto3,oneof"`
}

type PlanMonitoringEvent_GroundStationState struct {
	GroundStationState *monitoring.GroundStationState `protobuf:"bytes,3,opt,name=ground_station_state,json=groundStationState,proto3,oneof"`
}

type PlanMonitoringEvent_GroundStationEvent struct {
	GroundStationEvent *monitoring.GroundStationEvent `protobuf:"bytes,4,opt,name=ground_station_event,json=groundStationEvent,proto3,oneof"`
}

func (*PlanMonitoringEvent_GroundStationConfiguration) isPlanMonitoringEvent_Info() {}

func (*PlanMonitoringEvent_GroundStationState) isPlanMonitoringEvent_Info() {}

func (*PlanMonitoringEvent_GroundStationEvent) isPlanMonitoringEvent_Info() {}

func (m *PlanMonitoringEvent) GetInfo() isPlanMonitoringEvent_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PlanMonitoringEvent) GetGroundStationConfiguration() *monitoring.GroundStationConfiguration {
	if x, ok := m.GetInfo().(*PlanMonitoringEvent_GroundStationConfiguration); ok {
		return x.GroundStationConfiguration
	}
	return nil
}

func (m *PlanMonitoringEvent) GetGroundStationState() *monitoring.GroundStationState {
	if x, ok := m.GetInfo().(*PlanMonitoringEvent_GroundStationState); ok {
		return x.GroundStationState
	}
	return nil
}

func (m *PlanMonitoringEvent) GetGroundStationEvent() *monitoring.GroundStationEvent {
	if x, ok := m.GetInfo().(*PlanMonitoringEvent_GroundStationEvent); ok {
		return x.GroundStationEvent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PlanMonitoringEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PlanMonitoringEvent_GroundStationConfiguration)(nil),
		(*PlanMonitoringEvent_GroundStationState)(nil),
		(*PlanMonitoringEvent_GroundStationEvent)(nil),
	}
}

func init() {
	proto.RegisterEnum("stellarstation.api.v1.Framing", Framing_name, Framing_value)
	proto.RegisterType((*Telemetry)(nil), "stellarstation.api.v1.Telemetry")
	proto.RegisterType((*StreamEvent)(nil), "stellarstation.api.v1.StreamEvent")
	proto.RegisterType((*StreamEvent_CommandSentFromGroundStation)(nil), "stellarstation.api.v1.StreamEvent.CommandSentFromGroundStation")
	proto.RegisterType((*PlanMonitoringEvent)(nil), "stellarstation.api.v1.PlanMonitoringEvent")
}

func init() {
	proto.RegisterFile("stellarstation/api/v1/transport.proto", fileDescriptor_a5cbae65d14ae041)
}

var fileDescriptor_a5cbae65d14ae041 = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0xda, 0x48,
	0x14, 0xc5, 0x84, 0x8f, 0xe5, 0xc2, 0x22, 0x34, 0x09, 0x0a, 0x8b, 0xb2, 0x59, 0x36, 0xda, 0x95,
	0x50, 0xa4, 0x35, 0x0a, 0xbb, 0x2b, 0xe5, 0x61, 0xa5, 0x15, 0x44, 0xe6, 0xa3, 0x4a, 0x2a, 0x62,
	0x5c, 0x35, 0xea, 0xcb, 0x74, 0xb0, 0x07, 0x63, 0xd5, 0x9e, 0xa1, 0xe3, 0x81, 0x8a, 0x3c, 0xf5,
	0x3f, 0xf5, 0xc7, 0xb4, 0x3f, 0xa7, 0xf2, 0xd8, 0x24, 0x24, 0x81, 0x7e, 0x3d, 0xe1, 0xb9, 0xf7,
	0x9e, 0x73, 0xef, 0x39, 0x97, 0x19, 0xf8, 0x33, 0x94, 0xd4, 0xf7, 0x89, 0x08, 0x25, 0x91, 0x1e,
	0x67, 0x2d, 0x32, 0xf7, 0x5a, 0xcb, 0xb3, 0x96, 0x14, 0x84, 0x85, 0x73, 0x2e, 0xa4, 0x3e, 0x17,
	0x5c, 0x72, 0x54, 0x7d, 0x58, 0xa6, 0x93, 0xb9, 0xa7, 0x2f, 0xcf, 0xea, 0xbf, 0xb9, 0x9c, 0xbb,
	0x3e, 0x6d, 0xa9, 0xa2, 0xc9, 0x62, 0xda, 0x92, 0x5e, 0x40, 0x43, 0x49, 0x82, 0x79, 0x8c, 0xab,
	0x9f, 0x6d, 0xa7, 0x0f, 0x38, 0xf3, 0x24, 0x17, 0x1e, 0x73, 0x37, 0x3e, 0x63, 0xc8, 0xc9, 0xa7,
	0x34, 0x14, 0x2c, 0xea, 0xd3, 0x80, 0x4a, 0xb1, 0x42, 0xe7, 0x90, 0x9f, 0x0a, 0x12, 0x78, 0xcc,
	0xad, 0x69, 0x0d, 0xad, 0x59, 0x6e, 0x1f, 0xeb, 0x5b, 0x47, 0xd1, 0x7b, 0x71, 0x95, 0xb9, 0x2e,
	0x47, 0x08, 0x32, 0x0e, 0x91, 0xa4, 0x96, 0x6e, 0x68, 0xcd, 0x92, 0xa9, 0xbe, 0x51, 0x1b, 0xaa,
	0x0e, 0x7f, 0xc7, 0x7c, 0x8f, 0xbd, 0xc1, 0x53, 0x41, 0xdf, 0x2e, 0x28, 0xb3, 0x57, 0x78, 0x76,
	0x5b, 0xdb, 0x6b, 0x68, 0xcd, 0x8c, 0xb9, 0xbf, 0x4e, 0xf6, 0xd6, 0xb9, 0xc1, 0x2d, 0x1a, 0x43,
	0x2d, 0x52, 0x85, 0xa7, 0x9e, 0x08, 0x25, 0x9e, 0xac, 0x24, 0xc5, 0x82, 0xda, 0xd4, 0x5b, 0x52,
	0xa7, 0x96, 0x69, 0x68, 0xcd, 0x62, 0xbb, 0xae, 0xc7, 0x36, 0xe8, 0x6b, 0x1b, 0x74, 0x6b, 0x6d,
	0x83, 0x59, 0x8d, 0xb0, 0xbd, 0x08, 0xda, 0x5d, 0x49, 0x6a, 0x26, 0x40, 0x74, 0x0d, 0x87, 0x8a,
	0xd4, 0x27, 0x4f, 0x38, 0xb3, 0x5f, 0xe5, 0x3c, 0x88, 0xa0, 0x97, 0xe4, 0x11, 0xe5, 0xef, 0x50,
	0x8a, 0xa4, 0x53, 0x3c, 0xa3, 0xc4, 0xa1, 0xa2, 0x96, 0x53, 0xba, 0x8b, 0x2a, 0x36, 0x50, 0xa1,
	0x93, 0x8f, 0x69, 0x28, 0x8e, 0xa5, 0xa0, 0x24, 0x30, 0x96, 0x94, 0x49, 0xf4, 0x2b, 0x80, 0x12,
	0x1a, 0x4a, 0xec, 0x39, 0xca, 0xdf, 0x82, 0x59, 0x48, 0x22, 0x43, 0x07, 0x9d, 0x43, 0xe1, 0x6e,
	0x9f, 0xdf, 0x20, 0xf5, 0xbe, 0x18, 0x39, 0x50, 0xb2, 0x79, 0x10, 0x10, 0xe6, 0xe0, 0x90, 0x32,
	0xa9, 0x76, 0x50, 0x6c, 0xff, 0xbf, 0x63, 0x75, 0x1b, 0x23, 0xe9, 0x17, 0x31, 0x6c, 0x4c, 0x99,
	0xec, 0x09, 0x1e, 0xf4, 0x05, 0x5f, 0x30, 0x67, 0x1c, 0xd7, 0x0f, 0x52, 0x66, 0xd1, 0xbe, 0xcf,
	0xa3, 0xd7, 0x50, 0x9d, 0xfb, 0x84, 0xe1, 0xfb, 0xbf, 0x10, 0xa6, 0x11, 0x89, 0xda, 0x66, 0xb1,
	0x7d, 0xba, 0xa3, 0xdd, 0xc8, 0x27, 0xec, 0xea, 0x0e, 0xa2, 0xda, 0x0e, 0x52, 0xe6, 0xfe, 0xfc,
	0x69, 0xb8, 0x7e, 0x0c, 0x47, 0x5f, 0x1a, 0xa8, 0x9b, 0x87, 0xac, 0x2a, 0x3c, 0xf9, 0xb0, 0x07,
	0xfb, 0x5b, 0x78, 0xd1, 0x21, 0xe4, 0xd5, 0x88, 0x77, 0xf6, 0xe6, 0xa2, 0xe3, 0xd0, 0x41, 0x7f,
	0x40, 0xd9, 0x9e, 0x11, 0xc6, 0xa8, 0x8f, 0x43, 0xaa, 0xec, 0xcf, 0xaa, 0x7c, 0x29, 0x89, 0x8e,
	0x69, 0xb4, 0x81, 0xf7, 0x1a, 0x1c, 0xb9, 0xaa, 0x23, 0x4e, 0x44, 0x60, 0x9b, 0xb3, 0xa9, 0xe7,
	0x2e, 0x84, 0x3a, 0x25, 0xc6, 0xfe, 0xb7, 0x43, 0xe9, 0xc6, 0xdd, 0x7a, 0x30, 0xf7, 0xc5, 0x26,
	0xc7, 0x20, 0x65, 0xd6, 0xdd, 0x9d, 0x59, 0x34, 0x83, 0x83, 0x47, 0x13, 0x44, 0xbf, 0x34, 0xf1,
	0xf8, 0x9f, 0xef, 0xec, 0x1c, 0xfd, 0xd0, 0x41, 0xca, 0x44, 0xee, 0x93, 0xe8, 0x96, 0x4e, 0xf1,
	0x36, 0x33, 0x3f, 0xd4, 0x69, 0xbd, 0xd7, 0x87, 0x9d, 0x54, 0xb4, 0x9b, 0x83, 0xcc, 0x90, 0x4d,
	0xf9, 0xa9, 0x0f, 0xf9, 0xe4, 0xd9, 0x40, 0x3f, 0x43, 0xa1, 0x3b, 0xb4, 0xc6, 0x96, 0x69, 0x74,
	0xae, 0x2a, 0x29, 0xf4, 0x13, 0x64, 0x3a, 0x37, 0xed, 0x7f, 0x2b, 0x1a, 0xca, 0x41, 0x7a, 0x78,
	0x5d, 0x49, 0x47, 0x05, 0xc3, 0xab, 0x4e, 0xdf, 0xc0, 0xa3, 0xe7, 0xfd, 0xca, 0x1e, 0x2a, 0x03,
	0xc4, 0xc7, 0x67, 0x23, 0xa3, 0x5f, 0xc9, 0x20, 0x04, 0xe5, 0x9e, 0x69, 0x18, 0xd8, 0x32, 0x6e,
	0x2c, 0xfc, 0xc2, 0xea, 0x9d, 0x57, 0xb2, 0x11, 0xe4, 0x65, 0xc7, 0x32, 0xcc, 0x5e, 0xe7, 0xf2,
	0xb2, 0x92, 0xeb, 0x12, 0xf8, 0xc5, 0xe6, 0xc1, 0x76, 0x19, 0xdd, 0xb2, 0xb5, 0x7e, 0x71, 0x47,
	0xd1, 0xcd, 0x1a, 0x69, 0xaf, 0xda, 0xae, 0x27, 0x67, 0x8b, 0x89, 0x6e, 0xf3, 0xa0, 0xe5, 0xb1,
	0x29, 0x4f, 0x70, 0x1e, 0xb3, 0x5b, 0x2e, 0xff, 0x6b, 0xeb, 0xbb, 0x3a, 0xc9, 0xa9, 0x6b, 0xf9,
	0xf7, 0xe7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xe4, 0x3b, 0x3c, 0xd6, 0x05, 0x00, 0x00,
}
