// Copyright 2020 Infostellar, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: stellarstation/api/v1/groundstation/groundstation.proto

package groundstation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroundStationService_AddUnavailabilityWindow_FullMethodName    = "/stellarstation.api.v1.groundstation.GroundStationService/AddUnavailabilityWindow"
	GroundStationService_CancelPlan_FullMethodName                 = "/stellarstation.api.v1.groundstation.GroundStationService/CancelPlan"
	GroundStationService_DeleteUnavailabilityWindow_FullMethodName = "/stellarstation.api.v1.groundstation.GroundStationService/DeleteUnavailabilityWindow"
	GroundStationService_ListPlans_FullMethodName                  = "/stellarstation.api.v1.groundstation.GroundStationService/ListPlans"
	GroundStationService_ListUnavailabilityWindows_FullMethodName  = "/stellarstation.api.v1.groundstation.GroundStationService/ListUnavailabilityWindows"
	GroundStationService_OpenGroundStationStream_FullMethodName    = "/stellarstation.api.v1.groundstation.GroundStationService/OpenGroundStationStream"
	GroundStationService_GetCurrentPlan_FullMethodName             = "/stellarstation.api.v1.groundstation.GroundStationService/GetCurrentPlan"
)

// GroundStationServiceClient is the client API for GroundStationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The public API of StellarStation for use by ground station operators integrating with the
// StellarStation ground network. It is invalid to specify ground station IDs that the operator
// does not own. Only using IDs shown on the StellarStation Console or returned in API responses
// will ensure all inputs are valid.
//
// A pass is a time range where an ground station and satellite can communicate with each other, i.e.,
// the period between Acquisition of Signal (AOS) and Loss of Signal (LOS) of the ground station and
// satellite pair.
//
// A plan is a scheduled pass that will be executed to send and receive data between the ground
// station and satellite during the time range.
type GroundStationServiceClient interface {
	// Adds a new unavailability window to the requested ground station.
	//
	// Existing plans that overlap the unavailability window will not be canceled and the request will
	// be closed with a 'FAILED_PRECONDITION' status. In this case you will need to list any existing
	// plans with ListPlans and then cancel the plans with CancelPlan.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `ground_station_id`,
	// `start_time`, or `end_time` are missing, or 'end_time' is not after 'start_time'.
	AddUnavailabilityWindow(ctx context.Context, in *AddUnavailabilityWindowRequest, opts ...grpc.CallOption) (*AddUnavailabilityWindowResponse, error)
	// Cancel a previously reserved upcoming plan. Cancelling the plan will cause it to not be
	// executed. This action cannot be undone, but it is still possible for the pass to be reserved
	// again. The plan cannot be cancelled less than ten minutes before AOS.
	//
	// Canceling a plan may incur a charge based on the time left to AOS. See our cancellation policy
	// for details.
	//
	// If the plan is not found, the request will return a `NOT_FOUND` error.
	//
	// If the plan has already been canceled or is less than ten minutes away from its AOS, the
	// request will return a `FAILED_PRECONDITION` error.
	//
	// If the plan is ongoing or has already finished executing, the request will return a
	// `OUT_OF_RANGE` error.
	CancelPlan(ctx context.Context, in *CancelPlanRequest, opts ...grpc.CallOption) (*CancelPlanResponse, error)
	// Deletes an existing unavailability window of the requested ground station.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `window_id` is missing
	// or invalid.
	DeleteUnavailabilityWindow(ctx context.Context, in *DeleteUnavailabilityWindowRequest, opts ...grpc.CallOption) (*DeleteUnavailabilityWindowResponse, error)
	// Lists the plans for a particular ground station.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `ground_station_id`,
	// `aos_after`, or `aos_before` are missing, or the duration between the two times is longer than
	// 31 days.
	ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (*ListPlansResponse, error)
	// Returns a list of unavailability windows for the requested ground station.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `ground_station_id`,
	// `start_time`, or `end_time` are missing, or 'end_time' is not after 'start_time'.
	ListUnavailabilityWindows(ctx context.Context, in *ListUnavailabilityWindowsRequest, opts ...grpc.CallOption) (*ListUnavailabilityWindowsResponse, error)
	// Open a stream from a ground station. The returned stream is bi-directional - it is used by
	// the ground station to send telemetry received from a satellite and receive commands to send to
	// the satellite. The ground station must keep this stream open while it is connected to the
	// StellarStation network for use in executing plans - if the stream is cut, it must be
	// reconnected with exponential backoff.
	//
	// The first `GroundStationStreamRequest` sent on the stream is used for configuring the stream.
	// Unless otherwise specified, all configuration is taken from the first request and configuration
	// values in subsequent requests will be ignored.
	//
	// There is no restriction on the number of active streams from a ground station (i.e., streams
	// opened with the same `ground_station_id`). Most ground stations will issue a single stream to
	// receive commands and send telemetry, but in certain cases, such as if uplink and downlink are
	// handled by different computers, it can be appropriate to have multiple processes with their
	// own stream. If opening multiple streams for a single ground station, it is the client's
	// responsibility to handle the streams appropriately, for example by ensuring only one stream
	// sends commands so they are not duplicated.
	//
	// If the ground station is not found or the API client is not authorized for it, the stream will
	// be closed with a `NOT_FOUND` error.
	//
	// Status: ALPHA This API is under development and may not work correctly or be changed in backwards
	//
	//	incompatible ways in the future.
	OpenGroundStationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GroundStationStreamRequest, GroundStationStreamResponse], error)
	// For internal use only - retrieve current plan
	GetCurrentPlan(ctx context.Context, in *GetCurrentPlanRequest, opts ...grpc.CallOption) (*GetCurrentPlanResponse, error)
}

type groundStationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroundStationServiceClient(cc grpc.ClientConnInterface) GroundStationServiceClient {
	return &groundStationServiceClient{cc}
}

func (c *groundStationServiceClient) AddUnavailabilityWindow(ctx context.Context, in *AddUnavailabilityWindowRequest, opts ...grpc.CallOption) (*AddUnavailabilityWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUnavailabilityWindowResponse)
	err := c.cc.Invoke(ctx, GroundStationService_AddUnavailabilityWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groundStationServiceClient) CancelPlan(ctx context.Context, in *CancelPlanRequest, opts ...grpc.CallOption) (*CancelPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPlanResponse)
	err := c.cc.Invoke(ctx, GroundStationService_CancelPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groundStationServiceClient) DeleteUnavailabilityWindow(ctx context.Context, in *DeleteUnavailabilityWindowRequest, opts ...grpc.CallOption) (*DeleteUnavailabilityWindowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUnavailabilityWindowResponse)
	err := c.cc.Invoke(ctx, GroundStationService_DeleteUnavailabilityWindow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groundStationServiceClient) ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (*ListPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlansResponse)
	err := c.cc.Invoke(ctx, GroundStationService_ListPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groundStationServiceClient) ListUnavailabilityWindows(ctx context.Context, in *ListUnavailabilityWindowsRequest, opts ...grpc.CallOption) (*ListUnavailabilityWindowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUnavailabilityWindowsResponse)
	err := c.cc.Invoke(ctx, GroundStationService_ListUnavailabilityWindows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groundStationServiceClient) OpenGroundStationStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GroundStationStreamRequest, GroundStationStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GroundStationService_ServiceDesc.Streams[0], GroundStationService_OpenGroundStationStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GroundStationStreamRequest, GroundStationStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroundStationService_OpenGroundStationStreamClient = grpc.BidiStreamingClient[GroundStationStreamRequest, GroundStationStreamResponse]

func (c *groundStationServiceClient) GetCurrentPlan(ctx context.Context, in *GetCurrentPlanRequest, opts ...grpc.CallOption) (*GetCurrentPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentPlanResponse)
	err := c.cc.Invoke(ctx, GroundStationService_GetCurrentPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroundStationServiceServer is the server API for GroundStationService service.
// All implementations must embed UnimplementedGroundStationServiceServer
// for forward compatibility.
//
// The public API of StellarStation for use by ground station operators integrating with the
// StellarStation ground network. It is invalid to specify ground station IDs that the operator
// does not own. Only using IDs shown on the StellarStation Console or returned in API responses
// will ensure all inputs are valid.
//
// A pass is a time range where an ground station and satellite can communicate with each other, i.e.,
// the period between Acquisition of Signal (AOS) and Loss of Signal (LOS) of the ground station and
// satellite pair.
//
// A plan is a scheduled pass that will be executed to send and receive data between the ground
// station and satellite during the time range.
type GroundStationServiceServer interface {
	// Adds a new unavailability window to the requested ground station.
	//
	// Existing plans that overlap the unavailability window will not be canceled and the request will
	// be closed with a 'FAILED_PRECONDITION' status. In this case you will need to list any existing
	// plans with ListPlans and then cancel the plans with CancelPlan.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `ground_station_id`,
	// `start_time`, or `end_time` are missing, or 'end_time' is not after 'start_time'.
	AddUnavailabilityWindow(context.Context, *AddUnavailabilityWindowRequest) (*AddUnavailabilityWindowResponse, error)
	// Cancel a previously reserved upcoming plan. Cancelling the plan will cause it to not be
	// executed. This action cannot be undone, but it is still possible for the pass to be reserved
	// again. The plan cannot be cancelled less than ten minutes before AOS.
	//
	// Canceling a plan may incur a charge based on the time left to AOS. See our cancellation policy
	// for details.
	//
	// If the plan is not found, the request will return a `NOT_FOUND` error.
	//
	// If the plan has already been canceled or is less than ten minutes away from its AOS, the
	// request will return a `FAILED_PRECONDITION` error.
	//
	// If the plan is ongoing or has already finished executing, the request will return a
	// `OUT_OF_RANGE` error.
	CancelPlan(context.Context, *CancelPlanRequest) (*CancelPlanResponse, error)
	// Deletes an existing unavailability window of the requested ground station.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `window_id` is missing
	// or invalid.
	DeleteUnavailabilityWindow(context.Context, *DeleteUnavailabilityWindowRequest) (*DeleteUnavailabilityWindowResponse, error)
	// Lists the plans for a particular ground station.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `ground_station_id`,
	// `aos_after`, or `aos_before` are missing, or the duration between the two times is longer than
	// 31 days.
	ListPlans(context.Context, *ListPlansRequest) (*ListPlansResponse, error)
	// Returns a list of unavailability windows for the requested ground station.
	//
	// The request will be closed with an `INVALID_ARGUMENT` status if `ground_station_id`,
	// `start_time`, or `end_time` are missing, or 'end_time' is not after 'start_time'.
	ListUnavailabilityWindows(context.Context, *ListUnavailabilityWindowsRequest) (*ListUnavailabilityWindowsResponse, error)
	// Open a stream from a ground station. The returned stream is bi-directional - it is used by
	// the ground station to send telemetry received from a satellite and receive commands to send to
	// the satellite. The ground station must keep this stream open while it is connected to the
	// StellarStation network for use in executing plans - if the stream is cut, it must be
	// reconnected with exponential backoff.
	//
	// The first `GroundStationStreamRequest` sent on the stream is used for configuring the stream.
	// Unless otherwise specified, all configuration is taken from the first request and configuration
	// values in subsequent requests will be ignored.
	//
	// There is no restriction on the number of active streams from a ground station (i.e., streams
	// opened with the same `ground_station_id`). Most ground stations will issue a single stream to
	// receive commands and send telemetry, but in certain cases, such as if uplink and downlink are
	// handled by different computers, it can be appropriate to have multiple processes with their
	// own stream. If opening multiple streams for a single ground station, it is the client's
	// responsibility to handle the streams appropriately, for example by ensuring only one stream
	// sends commands so they are not duplicated.
	//
	// If the ground station is not found or the API client is not authorized for it, the stream will
	// be closed with a `NOT_FOUND` error.
	//
	// Status: ALPHA This API is under development and may not work correctly or be changed in backwards
	//
	//	incompatible ways in the future.
	OpenGroundStationStream(grpc.BidiStreamingServer[GroundStationStreamRequest, GroundStationStreamResponse]) error
	// For internal use only - retrieve current plan
	GetCurrentPlan(context.Context, *GetCurrentPlanRequest) (*GetCurrentPlanResponse, error)
	mustEmbedUnimplementedGroundStationServiceServer()
}

// UnimplementedGroundStationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroundStationServiceServer struct{}

func (UnimplementedGroundStationServiceServer) AddUnavailabilityWindow(context.Context, *AddUnavailabilityWindowRequest) (*AddUnavailabilityWindowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUnavailabilityWindow not implemented")
}
func (UnimplementedGroundStationServiceServer) CancelPlan(context.Context, *CancelPlanRequest) (*CancelPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPlan not implemented")
}
func (UnimplementedGroundStationServiceServer) DeleteUnavailabilityWindow(context.Context, *DeleteUnavailabilityWindowRequest) (*DeleteUnavailabilityWindowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUnavailabilityWindow not implemented")
}
func (UnimplementedGroundStationServiceServer) ListPlans(context.Context, *ListPlansRequest) (*ListPlansResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlans not implemented")
}
func (UnimplementedGroundStationServiceServer) ListUnavailabilityWindows(context.Context, *ListUnavailabilityWindowsRequest) (*ListUnavailabilityWindowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUnavailabilityWindows not implemented")
}
func (UnimplementedGroundStationServiceServer) OpenGroundStationStream(grpc.BidiStreamingServer[GroundStationStreamRequest, GroundStationStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method OpenGroundStationStream not implemented")
}
func (UnimplementedGroundStationServiceServer) GetCurrentPlan(context.Context, *GetCurrentPlanRequest) (*GetCurrentPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentPlan not implemented")
}
func (UnimplementedGroundStationServiceServer) mustEmbedUnimplementedGroundStationServiceServer() {}
func (UnimplementedGroundStationServiceServer) testEmbeddedByValue()                              {}

// UnsafeGroundStationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroundStationServiceServer will
// result in compilation errors.
type UnsafeGroundStationServiceServer interface {
	mustEmbedUnimplementedGroundStationServiceServer()
}

func RegisterGroundStationServiceServer(s grpc.ServiceRegistrar, srv GroundStationServiceServer) {
	// If the following call pancis, it indicates UnimplementedGroundStationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroundStationService_ServiceDesc, srv)
}

func _GroundStationService_AddUnavailabilityWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUnavailabilityWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroundStationServiceServer).AddUnavailabilityWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroundStationService_AddUnavailabilityWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroundStationServiceServer).AddUnavailabilityWindow(ctx, req.(*AddUnavailabilityWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroundStationService_CancelPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroundStationServiceServer).CancelPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroundStationService_CancelPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroundStationServiceServer).CancelPlan(ctx, req.(*CancelPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroundStationService_DeleteUnavailabilityWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUnavailabilityWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroundStationServiceServer).DeleteUnavailabilityWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroundStationService_DeleteUnavailabilityWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroundStationServiceServer).DeleteUnavailabilityWindow(ctx, req.(*DeleteUnavailabilityWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroundStationService_ListPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroundStationServiceServer).ListPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroundStationService_ListPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroundStationServiceServer).ListPlans(ctx, req.(*ListPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroundStationService_ListUnavailabilityWindows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUnavailabilityWindowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroundStationServiceServer).ListUnavailabilityWindows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroundStationService_ListUnavailabilityWindows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroundStationServiceServer).ListUnavailabilityWindows(ctx, req.(*ListUnavailabilityWindowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroundStationService_OpenGroundStationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GroundStationServiceServer).OpenGroundStationStream(&grpc.GenericServerStream[GroundStationStreamRequest, GroundStationStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GroundStationService_OpenGroundStationStreamServer = grpc.BidiStreamingServer[GroundStationStreamRequest, GroundStationStreamResponse]

func _GroundStationService_GetCurrentPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroundStationServiceServer).GetCurrentPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroundStationService_GetCurrentPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroundStationServiceServer).GetCurrentPlan(ctx, req.(*GetCurrentPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroundStationService_ServiceDesc is the grpc.ServiceDesc for GroundStationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroundStationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stellarstation.api.v1.groundstation.GroundStationService",
	HandlerType: (*GroundStationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUnavailabilityWindow",
			Handler:    _GroundStationService_AddUnavailabilityWindow_Handler,
		},
		{
			MethodName: "CancelPlan",
			Handler:    _GroundStationService_CancelPlan_Handler,
		},
		{
			MethodName: "DeleteUnavailabilityWindow",
			Handler:    _GroundStationService_DeleteUnavailabilityWindow_Handler,
		},
		{
			MethodName: "ListPlans",
			Handler:    _GroundStationService_ListPlans_Handler,
		},
		{
			MethodName: "ListUnavailabilityWindows",
			Handler:    _GroundStationService_ListUnavailabilityWindows_Handler,
		},
		{
			MethodName: "GetCurrentPlan",
			Handler:    _GroundStationService_GetCurrentPlan_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenGroundStationStream",
			Handler:       _GroundStationService_OpenGroundStationStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "stellarstation/api/v1/groundstation/groundstation.proto",
}
