// Copyright 2020 Infostellar, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: stellarstation/api/v1/antenna/antenna.proto

package antenna

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The polarization of an antenna.
// https://en.wikipedia.org/wiki/Antenna_(radio)#Polarization
type AntennaPolarization int32

const (
	// Horizontal polarization.
	AntennaPolarization_HORIZONTAL AntennaPolarization = 0
	// Vertical polarization.
	AntennaPolarization_VERTICAL AntennaPolarization = 1
	// Left-handed circular polarization.
	AntennaPolarization_LHCP AntennaPolarization = 2
	// Right-handed circular polarization.
	AntennaPolarization_RHCP AntennaPolarization = 3
)

// Enum value maps for AntennaPolarization.
var (
	AntennaPolarization_name = map[int32]string{
		0: "HORIZONTAL",
		1: "VERTICAL",
		2: "LHCP",
		3: "RHCP",
	}
	AntennaPolarization_value = map[string]int32{
		"HORIZONTAL": 0,
		"VERTICAL":   1,
		"LHCP":       2,
		"RHCP":       3,
	}
)

func (x AntennaPolarization) Enum() *AntennaPolarization {
	p := new(AntennaPolarization)
	*p = x
	return p
}

func (x AntennaPolarization) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AntennaPolarization) Descriptor() protoreflect.EnumDescriptor {
	return file_stellarstation_api_v1_antenna_antenna_proto_enumTypes[0].Descriptor()
}

func (AntennaPolarization) Type() protoreflect.EnumType {
	return &file_stellarstation_api_v1_antenna_antenna_proto_enumTypes[0]
}

func (x AntennaPolarization) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AntennaPolarization.Descriptor instead.
func (AntennaPolarization) EnumDescriptor() ([]byte, []int) {
	return file_stellarstation_api_v1_antenna_antenna_proto_rawDescGZIP(), []int{0}
}

// The static configuration of an antenna. These are the physical parameters of the antenna.
type AntennaConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The latitude of the antenna, in degrees.
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// The longitude of the antenna, in degrees.
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// The altitude of the antenna above mean sea level, in meters.
	AltitudeMeters float64 `protobuf:"fixed64,3,opt,name=altitude_meters,json=altitudeMeters,proto3" json:"altitude_meters,omitempty"`
	// The beamwidth, in degrees.
	// https://en.wikipedia.org/wiki/Beamwidth
	BeamwidthDegrees float64 `protobuf:"fixed64,4,opt,name=beamwidth_degrees,json=beamwidthDegrees,proto3" json:"beamwidth_degrees,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AntennaConfiguration) Reset() {
	*x = AntennaConfiguration{}
	mi := &file_stellarstation_api_v1_antenna_antenna_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaConfiguration) ProtoMessage() {}

func (x *AntennaConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_stellarstation_api_v1_antenna_antenna_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaConfiguration.ProtoReflect.Descriptor instead.
func (*AntennaConfiguration) Descriptor() ([]byte, []int) {
	return file_stellarstation_api_v1_antenna_antenna_proto_rawDescGZIP(), []int{0}
}

func (x *AntennaConfiguration) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AntennaConfiguration) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AntennaConfiguration) GetAltitudeMeters() float64 {
	if x != nil {
		return x.AltitudeMeters
	}
	return 0
}

func (x *AntennaConfiguration) GetBeamwidthDegrees() float64 {
	if x != nil {
		return x.BeamwidthDegrees
	}
	return 0
}

var File_stellarstation_api_v1_antenna_antenna_proto protoreflect.FileDescriptor

const file_stellarstation_api_v1_antenna_antenna_proto_rawDesc = "" +
	"\n" +
	"+stellarstation/api/v1/antenna/antenna.proto\x12\x1dstellarstation.api.v1.antenna\"\xa6\x01\n" +
	"\x14AntennaConfiguration\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12'\n" +
	"\x0faltitude_meters\x18\x03 \x01(\x01R\x0ealtitudeMeters\x12+\n" +
	"\x11beamwidth_degrees\x18\x04 \x01(\x01R\x10beamwidthDegrees*G\n" +
	"\x13AntennaPolarization\x12\x0e\n" +
	"\n" +
	"HORIZONTAL\x10\x00\x12\f\n" +
	"\bVERTICAL\x10\x01\x12\b\n" +
	"\x04LHCP\x10\x02\x12\b\n" +
	"\x04RHCP\x10\x03Bo\n" +
	"!com.stellarstation.api.v1.antennaB\fAntennaProtoP\x01Z:github.com/infostellarinc/go-stellarstation/api/v1/antennab\x06proto3"

var (
	file_stellarstation_api_v1_antenna_antenna_proto_rawDescOnce sync.Once
	file_stellarstation_api_v1_antenna_antenna_proto_rawDescData []byte
)

func file_stellarstation_api_v1_antenna_antenna_proto_rawDescGZIP() []byte {
	file_stellarstation_api_v1_antenna_antenna_proto_rawDescOnce.Do(func() {
		file_stellarstation_api_v1_antenna_antenna_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stellarstation_api_v1_antenna_antenna_proto_rawDesc), len(file_stellarstation_api_v1_antenna_antenna_proto_rawDesc)))
	})
	return file_stellarstation_api_v1_antenna_antenna_proto_rawDescData
}

var file_stellarstation_api_v1_antenna_antenna_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stellarstation_api_v1_antenna_antenna_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stellarstation_api_v1_antenna_antenna_proto_goTypes = []any{
	(AntennaPolarization)(0),     // 0: stellarstation.api.v1.antenna.AntennaPolarization
	(*AntennaConfiguration)(nil), // 1: stellarstation.api.v1.antenna.AntennaConfiguration
}
var file_stellarstation_api_v1_antenna_antenna_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stellarstation_api_v1_antenna_antenna_proto_init() }
func file_stellarstation_api_v1_antenna_antenna_proto_init() {
	if File_stellarstation_api_v1_antenna_antenna_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stellarstation_api_v1_antenna_antenna_proto_rawDesc), len(file_stellarstation_api_v1_antenna_antenna_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stellarstation_api_v1_antenna_antenna_proto_goTypes,
		DependencyIndexes: file_stellarstation_api_v1_antenna_antenna_proto_depIdxs,
		EnumInfos:         file_stellarstation_api_v1_antenna_antenna_proto_enumTypes,
		MessageInfos:      file_stellarstation_api_v1_antenna_antenna_proto_msgTypes,
	}.Build()
	File_stellarstation_api_v1_antenna_antenna_proto = out.File
	file_stellarstation_api_v1_antenna_antenna_proto_goTypes = nil
	file_stellarstation_api_v1_antenna_antenna_proto_depIdxs = nil
}
