// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stellarstation/api/v1/monitoring/monitoring.proto

package monitoring

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	antenna "github.com/infostellarinc/go-stellarstation/api/v1/antenna"
	common "github.com/infostellarinc/go-stellarstation/api/v1/common"
	orbit "github.com/infostellarinc/go-stellarstation/api/v1/orbit"
	radio "github.com/infostellarinc/go-stellarstation/api/v1/radio"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// A current status of convolutional coding.
type ConvolutionalCodingStatus int32

const (
	// Not locked on.
	ConvolutionalCodingStatus_UNLOCKED ConvolutionalCodingStatus = 0
	// Locked onto the in-phase signal.
	ConvolutionalCodingStatus_I_LOCKED ConvolutionalCodingStatus = 1
	// Locked onto the quadrature signal.
	ConvolutionalCodingStatus_Q_LOCKED ConvolutionalCodingStatus = 2
	// Locked onto both in-phase and quadrature signal.
	ConvolutionalCodingStatus_LOCKED ConvolutionalCodingStatus = 3
)

var ConvolutionalCodingStatus_name = map[int32]string{
	0: "UNLOCKED",
	1: "I_LOCKED",
	2: "Q_LOCKED",
	3: "LOCKED",
}

var ConvolutionalCodingStatus_value = map[string]int32{
	"UNLOCKED": 0,
	"I_LOCKED": 1,
	"Q_LOCKED": 2,
	"LOCKED":   3,
}

func (x ConvolutionalCodingStatus) String() string {
	return proto.EnumName(ConvolutionalCodingStatus_name, int32(x))
}

func (ConvolutionalCodingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{0}
}

type ReedSolomonStatus_Status int32

const (
	// Indicates Reed-Solomon coding is functioning.
	ReedSolomonStatus_OK ReedSolomonStatus_Status = 0
	// Indicates Reed-Solomon coding encountered an interleave error.
	ReedSolomonStatus_INTERLEAVE_ERROR ReedSolomonStatus_Status = 1
	// Indicates Reed-Solomon coding exceeded its correction capacity.
	ReedSolomonStatus_CORRECTION_CAPACITY_EXCEEDED ReedSolomonStatus_Status = 2
)

var ReedSolomonStatus_Status_name = map[int32]string{
	0: "OK",
	1: "INTERLEAVE_ERROR",
	2: "CORRECTION_CAPACITY_EXCEEDED",
}

var ReedSolomonStatus_Status_value = map[string]int32{
	"OK":                           0,
	"INTERLEAVE_ERROR":             1,
	"CORRECTION_CAPACITY_EXCEEDED": 2,
}

func (x ReedSolomonStatus_Status) String() string {
	return proto.EnumName(ReedSolomonStatus_Status_name, int32(x))
}

func (ReedSolomonStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{5, 0}
}

// A description of the plan status.
type PlanLifecycleEvent_Status int32

const (
	PlanLifecycleEvent_UNKNOWN PlanLifecycleEvent_Status = 0
	// Plan preparation has started. This status is sent when the ground station starts preparing
	// for plan execution.
	PlanLifecycleEvent_PREPARING PlanLifecycleEvent_Status = 1
	// Plan execution has started. This status is sent when passing the AOS time of the plan.
	PlanLifecycleEvent_EXECUTING PlanLifecycleEvent_Status = 2
	// Plan execution is complete. This status is sent when the ground station has finished
	// executing the plan and uploading all data.
	PlanLifecycleEvent_COMPLETED PlanLifecycleEvent_Status = 3
	// Plan execution failed. This status is sent when the plan cannot be completed for some
	// reason.
	PlanLifecycleEvent_FAILED PlanLifecycleEvent_Status = 4
)

var PlanLifecycleEvent_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "PREPARING",
	2: "EXECUTING",
	3: "COMPLETED",
	4: "FAILED",
}

var PlanLifecycleEvent_Status_value = map[string]int32{
	"UNKNOWN":   0,
	"PREPARING": 1,
	"EXECUTING": 2,
	"COMPLETED": 3,
	"FAILED":    4,
}

func (x PlanLifecycleEvent_Status) String() string {
	return proto.EnumName(PlanLifecycleEvent_Status_name, int32(x))
}

func (PlanLifecycleEvent_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{9, 0}
}

// A description of the cause of the failure.
type PlanLifecycleEvent_FailureDetails_Cause int32

const (
	PlanLifecycleEvent_FailureDetails_UNKNOWN PlanLifecycleEvent_FailureDetails_Cause = 0
)

var PlanLifecycleEvent_FailureDetails_Cause_name = map[int32]string{
	0: "UNKNOWN",
}

var PlanLifecycleEvent_FailureDetails_Cause_value = map[string]int32{
	"UNKNOWN": 0,
}

func (x PlanLifecycleEvent_FailureDetails_Cause) String() string {
	return proto.EnumName(PlanLifecycleEvent_FailureDetails_Cause_name, int32(x))
}

func (PlanLifecycleEvent_FailureDetails_Cause) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{9, 0, 0}
}

// The current configuration of a transmitter.
//
// A transmitter takes a bitstream and applies signal processing to create the final waveform sent
// to a satellite.
type TransmitterConfiguration struct {
	// The modulation type of the transmitter.
	Modulation radio.Modulation `protobuf:"varint,1,opt,name=modulation,proto3,enum=stellarstation.api.v1.radio.Modulation" json:"modulation,omitempty"`
	// Whether the carrier is enabled.
	IsCarrierEnabled bool `protobuf:"varint,2,opt,name=is_carrier_enabled,json=isCarrierEnabled,proto3" json:"is_carrier_enabled,omitempty"`
	// The bitrate of the transmitter.
	Bitrate uint64 `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// The line coding of the transmitter.
	LineCoding radio.LineCoding `protobuf:"varint,4,opt,name=line_coding,json=lineCoding,proto3,enum=stellarstation.api.v1.radio.LineCoding" json:"line_coding,omitempty"`
	// The bandwidth of the filter.
	FilterBandwidthHz uint64 `protobuf:"varint,5,opt,name=filter_bandwidth_hz,json=filterBandwidthHz,proto3" json:"filter_bandwidth_hz,omitempty"`
	// The sampling frequency.
	SamplingFrequencyHz  uint64   `protobuf:"varint,6,opt,name=sampling_frequency_hz,json=samplingFrequencyHz,proto3" json:"sampling_frequency_hz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransmitterConfiguration) Reset()         { *m = TransmitterConfiguration{} }
func (m *TransmitterConfiguration) String() string { return proto.CompactTextString(m) }
func (*TransmitterConfiguration) ProtoMessage()    {}
func (*TransmitterConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{0}
}

func (m *TransmitterConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitterConfiguration.Unmarshal(m, b)
}
func (m *TransmitterConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitterConfiguration.Marshal(b, m, deterministic)
}
func (m *TransmitterConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitterConfiguration.Merge(m, src)
}
func (m *TransmitterConfiguration) XXX_Size() int {
	return xxx_messageInfo_TransmitterConfiguration.Size(m)
}
func (m *TransmitterConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitterConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitterConfiguration proto.InternalMessageInfo

func (m *TransmitterConfiguration) GetModulation() radio.Modulation {
	if m != nil {
		return m.Modulation
	}
	return radio.Modulation_DISABLED
}

func (m *TransmitterConfiguration) GetIsCarrierEnabled() bool {
	if m != nil {
		return m.IsCarrierEnabled
	}
	return false
}

func (m *TransmitterConfiguration) GetBitrate() uint64 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *TransmitterConfiguration) GetLineCoding() radio.LineCoding {
	if m != nil {
		return m.LineCoding
	}
	return radio.LineCoding_NRZ_L
}

func (m *TransmitterConfiguration) GetFilterBandwidthHz() uint64 {
	if m != nil {
		return m.FilterBandwidthHz
	}
	return 0
}

func (m *TransmitterConfiguration) GetSamplingFrequencyHz() uint64 {
	if m != nil {
		return m.SamplingFrequencyHz
	}
	return 0
}

// The current configuration of a receiver.
//
// A receiver takes a waveform from a satellite and applies signal processing to produce a
// bitstream.
type ReceiverConfiguration struct {
	// The modulation type of the receiver.
	Modulation radio.Modulation `protobuf:"varint,1,opt,name=modulation,proto3,enum=stellarstation.api.v1.radio.Modulation" json:"modulation,omitempty"`
	// The bandwidth, in Hz.
	BandwidthHz uint64 `protobuf:"varint,2,opt,name=bandwidth_hz,json=bandwidthHz,proto3" json:"bandwidth_hz,omitempty"`
	// The sampling frequency.
	SamplingFrequencyHz uint64 `protobuf:"varint,3,opt,name=sampling_frequency_hz,json=samplingFrequencyHz,proto3" json:"sampling_frequency_hz,omitempty"`
	// The bitrate of the receiver.
	Bitrate uint64 `protobuf:"varint,4,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// The line coding of the receiver.
	LineCoding radio.LineCoding `protobuf:"varint,5,opt,name=line_coding,json=lineCoding,proto3,enum=stellarstation.api.v1.radio.LineCoding" json:"line_coding,omitempty"`
	// The frame synchronization word being used. Unset if frame synchronization is disabled.
	SynchronizationWord *common.Bits `protobuf:"bytes,6,opt,name=synchronization_word,json=synchronizationWord,proto3" json:"synchronization_word,omitempty"`
	// Whether convolutional code descrambling is enabled.
	IsConvolutionalCodeDescrambling bool `protobuf:"varint,7,opt,name=is_convolutional_code_descrambling,json=isConvolutionalCodeDescrambling,proto3" json:"is_convolutional_code_descrambling,omitempty"`
	// Whether convolutional code decoding is enabled.
	IsConvolutionalCodeDecoding bool `protobuf:"varint,8,opt,name=is_convolutional_code_decoding,json=isConvolutionalCodeDecoding,proto3" json:"is_convolutional_code_decoding,omitempty"`
	// Whether convolutional codes are inverted.
	// No meaning if `is_convolutional_code_decoding` is not enabled.
	IsConvolutionalCodeInverted bool `protobuf:"varint,9,opt,name=is_convolutional_code_inverted,json=isConvolutionalCodeInverted,proto3" json:"is_convolutional_code_inverted,omitempty"`
	// Whether reed solomon coding is being used.
	IsReedSolomonEnabled bool `protobuf:"varint,10,opt,name=is_reed_solomon_enabled,json=isReedSolomonEnabled,proto3" json:"is_reed_solomon_enabled,omitempty"`
	// The size of a frame, in bits.
	FrameSize uint32 `protobuf:"varint,11,opt,name=frame_size,json=frameSize,proto3" json:"frame_size,omitempty"`
	// Whether frame checking is enabled.
	IsFrameCheckingEnabled bool     `protobuf:"varint,12,opt,name=is_frame_checking_enabled,json=isFrameCheckingEnabled,proto3" json:"is_frame_checking_enabled,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *ReceiverConfiguration) Reset()         { *m = ReceiverConfiguration{} }
func (m *ReceiverConfiguration) String() string { return proto.CompactTextString(m) }
func (*ReceiverConfiguration) ProtoMessage()    {}
func (*ReceiverConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{1}
}

func (m *ReceiverConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiverConfiguration.Unmarshal(m, b)
}
func (m *ReceiverConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiverConfiguration.Marshal(b, m, deterministic)
}
func (m *ReceiverConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiverConfiguration.Merge(m, src)
}
func (m *ReceiverConfiguration) XXX_Size() int {
	return xxx_messageInfo_ReceiverConfiguration.Size(m)
}
func (m *ReceiverConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiverConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiverConfiguration proto.InternalMessageInfo

func (m *ReceiverConfiguration) GetModulation() radio.Modulation {
	if m != nil {
		return m.Modulation
	}
	return radio.Modulation_DISABLED
}

func (m *ReceiverConfiguration) GetBandwidthHz() uint64 {
	if m != nil {
		return m.BandwidthHz
	}
	return 0
}

func (m *ReceiverConfiguration) GetSamplingFrequencyHz() uint64 {
	if m != nil {
		return m.SamplingFrequencyHz
	}
	return 0
}

func (m *ReceiverConfiguration) GetBitrate() uint64 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *ReceiverConfiguration) GetLineCoding() radio.LineCoding {
	if m != nil {
		return m.LineCoding
	}
	return radio.LineCoding_NRZ_L
}

func (m *ReceiverConfiguration) GetSynchronizationWord() *common.Bits {
	if m != nil {
		return m.SynchronizationWord
	}
	return nil
}

func (m *ReceiverConfiguration) GetIsConvolutionalCodeDescrambling() bool {
	if m != nil {
		return m.IsConvolutionalCodeDescrambling
	}
	return false
}

func (m *ReceiverConfiguration) GetIsConvolutionalCodeDecoding() bool {
	if m != nil {
		return m.IsConvolutionalCodeDecoding
	}
	return false
}

func (m *ReceiverConfiguration) GetIsConvolutionalCodeInverted() bool {
	if m != nil {
		return m.IsConvolutionalCodeInverted
	}
	return false
}

func (m *ReceiverConfiguration) GetIsReedSolomonEnabled() bool {
	if m != nil {
		return m.IsReedSolomonEnabled
	}
	return false
}

func (m *ReceiverConfiguration) GetFrameSize() uint32 {
	if m != nil {
		return m.FrameSize
	}
	return 0
}

func (m *ReceiverConfiguration) GetIsFrameCheckingEnabled() bool {
	if m != nil {
		return m.IsFrameCheckingEnabled
	}
	return false
}

// The configuration of the currently executing plan.
type PlanConfiguration struct {
	// The TLE for the satellite in this plan.
	Tle                  *orbit.Tle `protobuf:"bytes,1,opt,name=tle,proto3" json:"tle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlanConfiguration) Reset()         { *m = PlanConfiguration{} }
func (m *PlanConfiguration) String() string { return proto.CompactTextString(m) }
func (*PlanConfiguration) ProtoMessage()    {}
func (*PlanConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{2}
}

func (m *PlanConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanConfiguration.Unmarshal(m, b)
}
func (m *PlanConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanConfiguration.Marshal(b, m, deterministic)
}
func (m *PlanConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanConfiguration.Merge(m, src)
}
func (m *PlanConfiguration) XXX_Size() int {
	return xxx_messageInfo_PlanConfiguration.Size(m)
}
func (m *PlanConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_PlanConfiguration proto.InternalMessageInfo

func (m *PlanConfiguration) GetTle() *orbit.Tle {
	if m != nil {
		return m.Tle
	}
	return nil
}

// The current configuration of a ground station. This is controlled by the parameters of a pass,
// based on the configuration of the satellite it will communicate with. When debugging issues with
// a pass, it is good to first confirm that the actual reported configuration matches the expected
// settings.
//
// Status: ALPHA This API is under development and may not work correctly or be changed in backwards
//         incompatible ways in the future.
type GroundStationConfiguration struct {
	// The current configuration of the transmitter in use by the ground station. This configuration
	// should match the parameters of the executing plan. When debugging issues with data
	// transmission (e.g., no response from satellite), it can be useful to confirm these values match
	// the expected configuration of the transmitter.
	Transmitter *TransmitterConfiguration `protobuf:"bytes,1,opt,name=transmitter,proto3" json:"transmitter,omitempty"`
	// The current configuration of the receiver in use by the ground station. This configuration
	// should match the parameters of the executing plan. When debugging issues with data
	// reception (e.g., can't decode signal), it can be useful to confirm these values match
	// the expected configuration of the receiver.
	Receiver *ReceiverConfiguration `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// The current configuration of the antenna used by the ground station. These are the physical
	// parameters of an antenna and in practice should never change, even across passes. But natural
	// events such as earthquakes can cause small changes in these values. When debugging issues with
	// tracking a satellite (e.g., getting no signal at all), it can be useful to confirm these values
	// match the expected configuration of the antenna.
	Antenna *antenna.AntennaConfiguration `protobuf:"bytes,3,opt,name=antenna,proto3" json:"antenna,omitempty"`
	// The current configuration of the plan being executed by the ground station.
	Plan                 *PlanConfiguration `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GroundStationConfiguration) Reset()         { *m = GroundStationConfiguration{} }
func (m *GroundStationConfiguration) String() string { return proto.CompactTextString(m) }
func (*GroundStationConfiguration) ProtoMessage()    {}
func (*GroundStationConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{3}
}

func (m *GroundStationConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroundStationConfiguration.Unmarshal(m, b)
}
func (m *GroundStationConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroundStationConfiguration.Marshal(b, m, deterministic)
}
func (m *GroundStationConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroundStationConfiguration.Merge(m, src)
}
func (m *GroundStationConfiguration) XXX_Size() int {
	return xxx_messageInfo_GroundStationConfiguration.Size(m)
}
func (m *GroundStationConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_GroundStationConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_GroundStationConfiguration proto.InternalMessageInfo

func (m *GroundStationConfiguration) GetTransmitter() *TransmitterConfiguration {
	if m != nil {
		return m.Transmitter
	}
	return nil
}

func (m *GroundStationConfiguration) GetReceiver() *ReceiverConfiguration {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *GroundStationConfiguration) GetAntenna() *antenna.AntennaConfiguration {
	if m != nil {
		return m.Antenna
	}
	return nil
}

func (m *GroundStationConfiguration) GetPlan() *PlanConfiguration {
	if m != nil {
		return m.Plan
	}
	return nil
}

// The current state of the ground station's transmitter during the operation of a pass.
// Next ID: 9
type TransmitterState struct {
	// The current center frequency of the transmitter, taking into account e.g., Doppler correction.
	CenterFrequencyHz uint64 `protobuf:"varint,1,opt,name=center_frequency_hz,json=centerFrequencyHz,proto3" json:"center_frequency_hz,omitempty"`
	// The current level of the carrier signal, in dBm (decibal-milliwatts).
	CarrierLevelDbm float64 `protobuf:"fixed64,2,opt,name=carrier_level_dbm,json=carrierLevelDbm,proto3" json:"carrier_level_dbm,omitempty"`
	// Whether modulation is enabled.
	IsModulationEnabled *wrappers.BoolValue `protobuf:"bytes,3,opt,name=is_modulation_enabled,json=isModulationEnabled,proto3" json:"is_modulation_enabled,omitempty"`
	// Whether the carrier is enabled.
	IsCarrierEnabled *wrappers.BoolValue `protobuf:"bytes,4,opt,name=is_carrier_enabled,json=isCarrierEnabled,proto3" json:"is_carrier_enabled,omitempty"`
	// Whether IF sweeping is enabled.
	IsIfSweepEnabled *wrappers.BoolValue `protobuf:"bytes,5,opt,name=is_if_sweep_enabled,json=isIfSweepEnabled,proto3" json:"is_if_sweep_enabled,omitempty"`
	// Whether transmitting idle pattern is enabled.
	IsIdlePatternEnabled *wrappers.BoolValue `protobuf:"bytes,6,opt,name=is_idle_pattern_enabled,json=isIdlePatternEnabled,proto3" json:"is_idle_pattern_enabled,omitempty"`
	// The current bitrate of the transmitter
	Bitrate *wrappers.FloatValue `protobuf:"bytes,7,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// Offset from the expected carrier frequency.
	CarrierOffset        *wrappers.FloatValue `protobuf:"bytes,8,opt,name=carrier_offset,json=carrierOffset,proto3" json:"carrier_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TransmitterState) Reset()         { *m = TransmitterState{} }
func (m *TransmitterState) String() string { return proto.CompactTextString(m) }
func (*TransmitterState) ProtoMessage()    {}
func (*TransmitterState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{4}
}

func (m *TransmitterState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransmitterState.Unmarshal(m, b)
}
func (m *TransmitterState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransmitterState.Marshal(b, m, deterministic)
}
func (m *TransmitterState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransmitterState.Merge(m, src)
}
func (m *TransmitterState) XXX_Size() int {
	return xxx_messageInfo_TransmitterState.Size(m)
}
func (m *TransmitterState) XXX_DiscardUnknown() {
	xxx_messageInfo_TransmitterState.DiscardUnknown(m)
}

var xxx_messageInfo_TransmitterState proto.InternalMessageInfo

func (m *TransmitterState) GetCenterFrequencyHz() uint64 {
	if m != nil {
		return m.CenterFrequencyHz
	}
	return 0
}

func (m *TransmitterState) GetCarrierLevelDbm() float64 {
	if m != nil {
		return m.CarrierLevelDbm
	}
	return 0
}

func (m *TransmitterState) GetIsModulationEnabled() *wrappers.BoolValue {
	if m != nil {
		return m.IsModulationEnabled
	}
	return nil
}

func (m *TransmitterState) GetIsCarrierEnabled() *wrappers.BoolValue {
	if m != nil {
		return m.IsCarrierEnabled
	}
	return nil
}

func (m *TransmitterState) GetIsIfSweepEnabled() *wrappers.BoolValue {
	if m != nil {
		return m.IsIfSweepEnabled
	}
	return nil
}

func (m *TransmitterState) GetIsIdlePatternEnabled() *wrappers.BoolValue {
	if m != nil {
		return m.IsIdlePatternEnabled
	}
	return nil
}

func (m *TransmitterState) GetBitrate() *wrappers.FloatValue {
	if m != nil {
		return m.Bitrate
	}
	return nil
}

func (m *TransmitterState) GetCarrierOffset() *wrappers.FloatValue {
	if m != nil {
		return m.CarrierOffset
	}
	return nil
}

// The status of Reed-Solomon coding.
// Next ID: 5
type ReedSolomonStatus struct {
	// Current status of Reed-Solomon coding.
	Status ReedSolomonStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=stellarstation.api.v1.monitoring.ReedSolomonStatus_Status" json:"status,omitempty"`
	// The number of Reed-Solomon corrected signals. Only set is `status` == `OK`.
	NumCorrectedSignals uint32 `protobuf:"varint,2,opt,name=num_corrected_signals,json=numCorrectedSignals,proto3" json:"num_corrected_signals,omitempty"`
	// Number of good transfer frames.
	NumGoodFrames *wrappers.Int64Value `protobuf:"bytes,3,opt,name=num_good_frames,json=numGoodFrames,proto3" json:"num_good_frames,omitempty"`
	// Number of bad transfer frames
	NumBadFrames         *wrappers.Int64Value `protobuf:"bytes,4,opt,name=num_bad_frames,json=numBadFrames,proto3" json:"num_bad_frames,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReedSolomonStatus) Reset()         { *m = ReedSolomonStatus{} }
func (m *ReedSolomonStatus) String() string { return proto.CompactTextString(m) }
func (*ReedSolomonStatus) ProtoMessage()    {}
func (*ReedSolomonStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{5}
}

func (m *ReedSolomonStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReedSolomonStatus.Unmarshal(m, b)
}
func (m *ReedSolomonStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReedSolomonStatus.Marshal(b, m, deterministic)
}
func (m *ReedSolomonStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReedSolomonStatus.Merge(m, src)
}
func (m *ReedSolomonStatus) XXX_Size() int {
	return xxx_messageInfo_ReedSolomonStatus.Size(m)
}
func (m *ReedSolomonStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReedSolomonStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReedSolomonStatus proto.InternalMessageInfo

func (m *ReedSolomonStatus) GetStatus() ReedSolomonStatus_Status {
	if m != nil {
		return m.Status
	}
	return ReedSolomonStatus_OK
}

func (m *ReedSolomonStatus) GetNumCorrectedSignals() uint32 {
	if m != nil {
		return m.NumCorrectedSignals
	}
	return 0
}

func (m *ReedSolomonStatus) GetNumGoodFrames() *wrappers.Int64Value {
	if m != nil {
		return m.NumGoodFrames
	}
	return nil
}

func (m *ReedSolomonStatus) GetNumBadFrames() *wrappers.Int64Value {
	if m != nil {
		return m.NumBadFrames
	}
	return nil
}

// The current state of the ground station's receiver during the operation of a pass.
// Next ID: 12
type ReceiverState struct {
	// The current center frequency of the receiver, taking into account e.g., Doppler correction.
	CenterFrequencyHz uint64 `protobuf:"varint,1,opt,name=center_frequency_hz,json=centerFrequencyHz,proto3" json:"center_frequency_hz,omitempty"`
	// The current level of the carrier signal, in dBm (decibal-milliwatts).
	CarrierLevelDbm float64 `protobuf:"fixed64,2,opt,name=carrier_level_dbm,json=carrierLevelDbm,proto3" json:"carrier_level_dbm,omitempty"`
	// Whether the receiver is phase-locked onto a signal.
	IsPhaseLocked bool `protobuf:"varint,3,opt,name=is_phase_locked,json=isPhaseLocked,proto3" json:"is_phase_locked,omitempty"`
	// Whether the bit synchronizer is locked onto a signal.
	IsBitSynchronizerLocked bool `protobuf:"varint,4,opt,name=is_bit_synchronizer_locked,json=isBitSynchronizerLocked,proto3" json:"is_bit_synchronizer_locked,omitempty"`
	// The signal-to-noise ratio per bit, e.g., Eb/N0.
	// https://en.wikipedia.org/wiki/Eb/N0
	NormalizedSnr float64 `protobuf:"fixed64,5,opt,name=normalized_snr,json=normalizedSnr,proto3" json:"normalized_snr,omitempty"`
	// Whether the frame synchronizer is locked onto a signal.
	IsFrameSynchronizerLocked bool `protobuf:"varint,6,opt,name=is_frame_synchronizer_locked,json=isFrameSynchronizerLocked,proto3" json:"is_frame_synchronizer_locked,omitempty"`
	// The current status of convolutional coding.
	ConvolutionalCodingStatus ConvolutionalCodingStatus `protobuf:"varint,7,opt,name=convolutional_coding_status,json=convolutionalCodingStatus,proto3,enum=stellarstation.api.v1.monitoring.ConvolutionalCodingStatus" json:"convolutional_coding_status,omitempty"`
	// The bit error rate of convolutional coding.
	ConvolutionalCodingBitErrorRate float64 `protobuf:"fixed64,8,opt,name=convolutional_coding_bit_error_rate,json=convolutionalCodingBitErrorRate,proto3" json:"convolutional_coding_bit_error_rate,omitempty"`
	// The status of Reed-Solomon coding.
	ReedSolomonStatus *ReedSolomonStatus `protobuf:"bytes,9,opt,name=reed_solomon_status,json=reedSolomonStatus,proto3" json:"reed_solomon_status,omitempty"`
	// The current bitrate of the receiver
	Bitrate *wrappers.FloatValue `protobuf:"bytes,10,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// Offset from the expected carrier frequency.
	CarrierOffset        *wrappers.FloatValue `protobuf:"bytes,11,opt,name=carrier_offset,json=carrierOffset,proto3" json:"carrier_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReceiverState) Reset()         { *m = ReceiverState{} }
func (m *ReceiverState) String() string { return proto.CompactTextString(m) }
func (*ReceiverState) ProtoMessage()    {}
func (*ReceiverState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{6}
}

func (m *ReceiverState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiverState.Unmarshal(m, b)
}
func (m *ReceiverState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiverState.Marshal(b, m, deterministic)
}
func (m *ReceiverState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiverState.Merge(m, src)
}
func (m *ReceiverState) XXX_Size() int {
	return xxx_messageInfo_ReceiverState.Size(m)
}
func (m *ReceiverState) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiverState.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiverState proto.InternalMessageInfo

func (m *ReceiverState) GetCenterFrequencyHz() uint64 {
	if m != nil {
		return m.CenterFrequencyHz
	}
	return 0
}

func (m *ReceiverState) GetCarrierLevelDbm() float64 {
	if m != nil {
		return m.CarrierLevelDbm
	}
	return 0
}

func (m *ReceiverState) GetIsPhaseLocked() bool {
	if m != nil {
		return m.IsPhaseLocked
	}
	return false
}

func (m *ReceiverState) GetIsBitSynchronizerLocked() bool {
	if m != nil {
		return m.IsBitSynchronizerLocked
	}
	return false
}

func (m *ReceiverState) GetNormalizedSnr() float64 {
	if m != nil {
		return m.NormalizedSnr
	}
	return 0
}

func (m *ReceiverState) GetIsFrameSynchronizerLocked() bool {
	if m != nil {
		return m.IsFrameSynchronizerLocked
	}
	return false
}

func (m *ReceiverState) GetConvolutionalCodingStatus() ConvolutionalCodingStatus {
	if m != nil {
		return m.ConvolutionalCodingStatus
	}
	return ConvolutionalCodingStatus_UNLOCKED
}

func (m *ReceiverState) GetConvolutionalCodingBitErrorRate() float64 {
	if m != nil {
		return m.ConvolutionalCodingBitErrorRate
	}
	return 0
}

func (m *ReceiverState) GetReedSolomonStatus() *ReedSolomonStatus {
	if m != nil {
		return m.ReedSolomonStatus
	}
	return nil
}

func (m *ReceiverState) GetBitrate() *wrappers.FloatValue {
	if m != nil {
		return m.Bitrate
	}
	return nil
}

func (m *ReceiverState) GetCarrierOffset() *wrappers.FloatValue {
	if m != nil {
		return m.CarrierOffset
	}
	return nil
}

// The current state of the ground station's antenna during the operation of a pass.
// Next ID: 4
type AntennaState struct {
	// The current state of the antenna's azimuth (horizontal angle).
	Azimuth *AntennaState_Angle `protobuf:"bytes,1,opt,name=azimuth,proto3" json:"azimuth,omitempty"`
	// The current state of the antenna's elevation (vertical angle).
	Elevation *AntennaState_Angle `protobuf:"bytes,2,opt,name=elevation,proto3" json:"elevation,omitempty"`
	// The current polarization of the antenna.
	Polarization         antenna.AntennaPolarization `protobuf:"varint,3,opt,name=polarization,proto3,enum=stellarstation.api.v1.antenna.AntennaPolarization" json:"polarization,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AntennaState) Reset()         { *m = AntennaState{} }
func (m *AntennaState) String() string { return proto.CompactTextString(m) }
func (*AntennaState) ProtoMessage()    {}
func (*AntennaState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{7}
}

func (m *AntennaState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AntennaState.Unmarshal(m, b)
}
func (m *AntennaState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AntennaState.Marshal(b, m, deterministic)
}
func (m *AntennaState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AntennaState.Merge(m, src)
}
func (m *AntennaState) XXX_Size() int {
	return xxx_messageInfo_AntennaState.Size(m)
}
func (m *AntennaState) XXX_DiscardUnknown() {
	xxx_messageInfo_AntennaState.DiscardUnknown(m)
}

var xxx_messageInfo_AntennaState proto.InternalMessageInfo

func (m *AntennaState) GetAzimuth() *AntennaState_Angle {
	if m != nil {
		return m.Azimuth
	}
	return nil
}

func (m *AntennaState) GetElevation() *AntennaState_Angle {
	if m != nil {
		return m.Elevation
	}
	return nil
}

func (m *AntennaState) GetPolarization() antenna.AntennaPolarization {
	if m != nil {
		return m.Polarization
	}
	return antenna.AntennaPolarization_HORIZONTAL
}

// The state of an antenna angle.
type AntennaState_Angle struct {
	// The angle that was specified for the antenna. When the antenna is functioning properly,
	// there should be nearly no difference between this and `measured`.
	Command float64 `protobuf:"fixed64,1,opt,name=command,proto3" json:"command,omitempty"`
	// The actual angle physically measured from the antenna. When the antenna is functioning
	// properly, there should be nearly no difference between this and `command`.
	Measured             float64  `protobuf:"fixed64,2,opt,name=measured,proto3" json:"measured,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AntennaState_Angle) Reset()         { *m = AntennaState_Angle{} }
func (m *AntennaState_Angle) String() string { return proto.CompactTextString(m) }
func (*AntennaState_Angle) ProtoMessage()    {}
func (*AntennaState_Angle) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{7, 0}
}

func (m *AntennaState_Angle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AntennaState_Angle.Unmarshal(m, b)
}
func (m *AntennaState_Angle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AntennaState_Angle.Marshal(b, m, deterministic)
}
func (m *AntennaState_Angle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AntennaState_Angle.Merge(m, src)
}
func (m *AntennaState_Angle) XXX_Size() int {
	return xxx_messageInfo_AntennaState_Angle.Size(m)
}
func (m *AntennaState_Angle) XXX_DiscardUnknown() {
	xxx_messageInfo_AntennaState_Angle.DiscardUnknown(m)
}

var xxx_messageInfo_AntennaState_Angle proto.InternalMessageInfo

func (m *AntennaState_Angle) GetCommand() float64 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *AntennaState_Angle) GetMeasured() float64 {
	if m != nil {
		return m.Measured
	}
	return 0
}

// The current state of a ground station during the operation of a pass.
//
// State that can be monitored will vary by the specifications of the ground station that executes
// the pass. Any information that cannot be monitored for the current ground station will not be
// filled.
type GroundStationState struct {
	// The current state of the transmitter in use during a pass. When debugging issues with data
	// transmission (e.g., no response from a satellite), it can be good to verify the metrics for
	// the transmitter are within expected or acceptable values.
	Transmitter *TransmitterState `protobuf:"bytes,1,opt,name=transmitter,proto3" json:"transmitter,omitempty"`
	// The current state of the receiver in use during a pass. When debugging issues with data
	// reception (e.g., can't decode signal), it can be good to verify the metrics for the receiver
	// are within expected or acceptable values.
	Receiver *ReceiverState `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// The current state of the antenna being used for the pass. When debugging issues with tracking
	// a satellite (e.g., getting no signal at all), it can be useful to ensure the physically
	// measured values are within expected or acceptable values.
	Antenna              *AntennaState `protobuf:"bytes,3,opt,name=antenna,proto3" json:"antenna,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GroundStationState) Reset()         { *m = GroundStationState{} }
func (m *GroundStationState) String() string { return proto.CompactTextString(m) }
func (*GroundStationState) ProtoMessage()    {}
func (*GroundStationState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{8}
}

func (m *GroundStationState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroundStationState.Unmarshal(m, b)
}
func (m *GroundStationState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroundStationState.Marshal(b, m, deterministic)
}
func (m *GroundStationState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroundStationState.Merge(m, src)
}
func (m *GroundStationState) XXX_Size() int {
	return xxx_messageInfo_GroundStationState.Size(m)
}
func (m *GroundStationState) XXX_DiscardUnknown() {
	xxx_messageInfo_GroundStationState.DiscardUnknown(m)
}

var xxx_messageInfo_GroundStationState proto.InternalMessageInfo

func (m *GroundStationState) GetTransmitter() *TransmitterState {
	if m != nil {
		return m.Transmitter
	}
	return nil
}

func (m *GroundStationState) GetReceiver() *ReceiverState {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *GroundStationState) GetAntenna() *AntennaState {
	if m != nil {
		return m.Antenna
	}
	return nil
}

// An event that describes the status of the plan being executed by the ground station.
type PlanLifecycleEvent struct {
	// The status of the plan.
	Status PlanLifecycleEvent_Status `protobuf:"varint,1,opt,name=status,proto3,enum=stellarstation.api.v1.monitoring.PlanLifecycleEvent_Status" json:"status,omitempty"`
	// Types that are valid to be assigned to Details:
	//	*PlanLifecycleEvent_Failure
	Details              isPlanLifecycleEvent_Details `protobuf_oneof:"Details"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *PlanLifecycleEvent) Reset()         { *m = PlanLifecycleEvent{} }
func (m *PlanLifecycleEvent) String() string { return proto.CompactTextString(m) }
func (*PlanLifecycleEvent) ProtoMessage()    {}
func (*PlanLifecycleEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{9}
}

func (m *PlanLifecycleEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanLifecycleEvent.Unmarshal(m, b)
}
func (m *PlanLifecycleEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanLifecycleEvent.Marshal(b, m, deterministic)
}
func (m *PlanLifecycleEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanLifecycleEvent.Merge(m, src)
}
func (m *PlanLifecycleEvent) XXX_Size() int {
	return xxx_messageInfo_PlanLifecycleEvent.Size(m)
}
func (m *PlanLifecycleEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanLifecycleEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PlanLifecycleEvent proto.InternalMessageInfo

func (m *PlanLifecycleEvent) GetStatus() PlanLifecycleEvent_Status {
	if m != nil {
		return m.Status
	}
	return PlanLifecycleEvent_UNKNOWN
}

type isPlanLifecycleEvent_Details interface {
	isPlanLifecycleEvent_Details()
}

type PlanLifecycleEvent_Failure struct {
	Failure *PlanLifecycleEvent_FailureDetails `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*PlanLifecycleEvent_Failure) isPlanLifecycleEvent_Details() {}

func (m *PlanLifecycleEvent) GetDetails() isPlanLifecycleEvent_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *PlanLifecycleEvent) GetFailure() *PlanLifecycleEvent_FailureDetails {
	if x, ok := m.GetDetails().(*PlanLifecycleEvent_Failure); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PlanLifecycleEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PlanLifecycleEvent_Failure)(nil),
	}
}

// If a plan fails, this message describes the cause of the failure.
type PlanLifecycleEvent_FailureDetails struct {
	// The cause of the failure.
	Cause                PlanLifecycleEvent_FailureDetails_Cause `protobuf:"varint,1,opt,name=cause,proto3,enum=stellarstation.api.v1.monitoring.PlanLifecycleEvent_FailureDetails_Cause" json:"cause,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *PlanLifecycleEvent_FailureDetails) Reset()         { *m = PlanLifecycleEvent_FailureDetails{} }
func (m *PlanLifecycleEvent_FailureDetails) String() string { return proto.CompactTextString(m) }
func (*PlanLifecycleEvent_FailureDetails) ProtoMessage()    {}
func (*PlanLifecycleEvent_FailureDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{9, 0}
}

func (m *PlanLifecycleEvent_FailureDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlanLifecycleEvent_FailureDetails.Unmarshal(m, b)
}
func (m *PlanLifecycleEvent_FailureDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlanLifecycleEvent_FailureDetails.Marshal(b, m, deterministic)
}
func (m *PlanLifecycleEvent_FailureDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanLifecycleEvent_FailureDetails.Merge(m, src)
}
func (m *PlanLifecycleEvent_FailureDetails) XXX_Size() int {
	return xxx_messageInfo_PlanLifecycleEvent_FailureDetails.Size(m)
}
func (m *PlanLifecycleEvent_FailureDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanLifecycleEvent_FailureDetails.DiscardUnknown(m)
}

var xxx_messageInfo_PlanLifecycleEvent_FailureDetails proto.InternalMessageInfo

func (m *PlanLifecycleEvent_FailureDetails) GetCause() PlanLifecycleEvent_FailureDetails_Cause {
	if m != nil {
		return m.Cause
	}
	return PlanLifecycleEvent_FailureDetails_UNKNOWN
}

// Events generated by a ground station during the operation of a pass.
//
// Status: ALPHA This API is under development and may not work correctly or be changed in backwards
//         incompatible ways in the future.
type GroundStationEvent struct {
	// An event related to the plan being executed.
	Plan                 *PlanLifecycleEvent `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GroundStationEvent) Reset()         { *m = GroundStationEvent{} }
func (m *GroundStationEvent) String() string { return proto.CompactTextString(m) }
func (*GroundStationEvent) ProtoMessage()    {}
func (*GroundStationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c57de69b506f3ba, []int{10}
}

func (m *GroundStationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroundStationEvent.Unmarshal(m, b)
}
func (m *GroundStationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroundStationEvent.Marshal(b, m, deterministic)
}
func (m *GroundStationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroundStationEvent.Merge(m, src)
}
func (m *GroundStationEvent) XXX_Size() int {
	return xxx_messageInfo_GroundStationEvent.Size(m)
}
func (m *GroundStationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_GroundStationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_GroundStationEvent proto.InternalMessageInfo

func (m *GroundStationEvent) GetPlan() *PlanLifecycleEvent {
	if m != nil {
		return m.Plan
	}
	return nil
}

func init() {
	proto.RegisterEnum("stellarstation.api.v1.monitoring.ConvolutionalCodingStatus", ConvolutionalCodingStatus_name, ConvolutionalCodingStatus_value)
	proto.RegisterEnum("stellarstation.api.v1.monitoring.ReedSolomonStatus_Status", ReedSolomonStatus_Status_name, ReedSolomonStatus_Status_value)
	proto.RegisterEnum("stellarstation.api.v1.monitoring.PlanLifecycleEvent_Status", PlanLifecycleEvent_Status_name, PlanLifecycleEvent_Status_value)
	proto.RegisterEnum("stellarstation.api.v1.monitoring.PlanLifecycleEvent_FailureDetails_Cause", PlanLifecycleEvent_FailureDetails_Cause_name, PlanLifecycleEvent_FailureDetails_Cause_value)
	proto.RegisterType((*TransmitterConfiguration)(nil), "stellarstation.api.v1.monitoring.TransmitterConfiguration")
	proto.RegisterType((*ReceiverConfiguration)(nil), "stellarstation.api.v1.monitoring.ReceiverConfiguration")
	proto.RegisterType((*PlanConfiguration)(nil), "stellarstation.api.v1.monitoring.PlanConfiguration")
	proto.RegisterType((*GroundStationConfiguration)(nil), "stellarstation.api.v1.monitoring.GroundStationConfiguration")
	proto.RegisterType((*TransmitterState)(nil), "stellarstation.api.v1.monitoring.TransmitterState")
	proto.RegisterType((*ReedSolomonStatus)(nil), "stellarstation.api.v1.monitoring.ReedSolomonStatus")
	proto.RegisterType((*ReceiverState)(nil), "stellarstation.api.v1.monitoring.ReceiverState")
	proto.RegisterType((*AntennaState)(nil), "stellarstation.api.v1.monitoring.AntennaState")
	proto.RegisterType((*AntennaState_Angle)(nil), "stellarstation.api.v1.monitoring.AntennaState.Angle")
	proto.RegisterType((*GroundStationState)(nil), "stellarstation.api.v1.monitoring.GroundStationState")
	proto.RegisterType((*PlanLifecycleEvent)(nil), "stellarstation.api.v1.monitoring.PlanLifecycleEvent")
	proto.RegisterType((*PlanLifecycleEvent_FailureDetails)(nil), "stellarstation.api.v1.monitoring.PlanLifecycleEvent.FailureDetails")
	proto.RegisterType((*GroundStationEvent)(nil), "stellarstation.api.v1.monitoring.GroundStationEvent")
}

func init() {
	proto.RegisterFile("stellarstation/api/v1/monitoring/monitoring.proto", fileDescriptor_8c57de69b506f3ba)
}

var fileDescriptor_8c57de69b506f3ba = []byte{
	// 1639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x5f, 0x73, 0x1b, 0xb7,
	0x11, 0x37, 0x29, 0x4a, 0x94, 0x96, 0x92, 0x4c, 0x41, 0x72, 0x43, 0xcb, 0x69, 0xa2, 0xb2, 0x7f,
	0xe2, 0xa6, 0x2d, 0x35, 0x66, 0x9c, 0x76, 0x1a, 0x4f, 0xa6, 0x23, 0x9e, 0x4e, 0x12, 0x47, 0x34,
	0x45, 0x83, 0xb2, 0x93, 0x76, 0x3a, 0xbd, 0x01, 0xef, 0x40, 0x0a, 0x93, 0x3b, 0x80, 0x05, 0xee,
	0xe4, 0x5a, 0x7d, 0xea, 0x53, 0x3f, 0x47, 0x3f, 0x41, 0x3f, 0x47, 0x3f, 0x42, 0xfb, 0xda, 0x87,
	0x3e, 0xf5, 0x3b, 0x74, 0x80, 0xc3, 0xf1, 0x8f, 0x44, 0x86, 0xb4, 0x53, 0xbf, 0xe8, 0x00, 0xec,
	0xee, 0x0f, 0xc0, 0x62, 0xf7, 0xb7, 0x4b, 0xc1, 0x13, 0x15, 0xd3, 0x30, 0x24, 0x52, 0xc5, 0x24,
	0x66, 0x82, 0x1f, 0x92, 0x21, 0x3b, 0xbc, 0x7e, 0x72, 0x18, 0x09, 0xce, 0x62, 0x21, 0x19, 0x1f,
	0x4c, 0x0c, 0x6b, 0x43, 0x29, 0x62, 0x81, 0x0e, 0xa6, 0x4d, 0x6a, 0x64, 0xc8, 0x6a, 0xd7, 0x4f,
	0x6a, 0x63, 0xbd, 0xfd, 0x8f, 0x06, 0x42, 0x0c, 0x42, 0x7a, 0x68, 0xf4, 0x7b, 0x49, 0xff, 0xf0,
	0xb5, 0x24, 0xc3, 0x21, 0x95, 0x2a, 0x45, 0xd8, 0xff, 0xd9, 0xec, 0x4d, 0x09, 0x8f, 0x29, 0xe7,
	0x24, 0xfb, 0x5a, 0xe5, 0x9f, 0xce, 0x56, 0xf6, 0x45, 0x14, 0x09, 0x6e, 0x3f, 0x56, 0xf5, 0x93,
	0xd9, 0xaa, 0x42, 0xf6, 0x58, 0x9c, 0xfe, 0xfd, 0x76, 0x45, 0x49, 0x02, 0x26, 0xd2, 0xbf, 0xa9,
	0x62, 0xf5, 0x9f, 0x79, 0xa8, 0x5c, 0x4a, 0xc2, 0x55, 0xc4, 0xe2, 0x98, 0x4a, 0x47, 0xf0, 0x3e,
	0x1b, 0x24, 0xd2, 0x58, 0xa1, 0x53, 0x80, 0x48, 0x04, 0x49, 0x68, 0x66, 0x95, 0xdc, 0x41, 0xee,
	0xf1, 0x76, 0xfd, 0x93, 0xda, 0x6c, 0xef, 0xa4, 0xa0, 0xcf, 0x47, 0xea, 0x78, 0xc2, 0x14, 0xfd,
	0x1c, 0x10, 0x53, 0x9e, 0x4f, 0xa4, 0x64, 0x54, 0x7a, 0x94, 0x93, 0x5e, 0x48, 0x83, 0x4a, 0xfe,
	0x20, 0xf7, 0x78, 0x1d, 0x97, 0x99, 0x72, 0x52, 0x81, 0x9b, 0xae, 0xa3, 0x0a, 0x14, 0x7b, 0x2c,
	0x96, 0x24, 0xa6, 0x95, 0x95, 0x83, 0xdc, 0xe3, 0x02, 0xce, 0xa6, 0xe8, 0x0c, 0x4a, 0x21, 0xe3,
	0xd4, 0xf3, 0x45, 0xc0, 0xf8, 0xa0, 0x52, 0x58, 0xe2, 0x44, 0x2d, 0xc6, 0xa9, 0x63, 0xd4, 0x31,
	0x84, 0xa3, 0x31, 0xaa, 0xc1, 0x6e, 0x9f, 0x85, 0x31, 0x95, 0x5e, 0x8f, 0xf0, 0xe0, 0x35, 0x0b,
	0xe2, 0x2b, 0xef, 0xea, 0xa6, 0xb2, 0x6a, 0xf6, 0xdb, 0x49, 0x45, 0x8d, 0x4c, 0x72, 0x76, 0x83,
	0xea, 0xf0, 0x40, 0x91, 0x68, 0x18, 0x32, 0x3e, 0xf0, 0xfa, 0x92, 0xfe, 0x31, 0xa1, 0xdc, 0x7f,
	0xa3, 0x2d, 0xd6, 0x8c, 0xc5, 0x6e, 0x26, 0x3c, 0xc9, 0x64, 0x67, 0x37, 0xd5, 0x7f, 0xad, 0xc2,
	0x03, 0x4c, 0x7d, 0xca, 0xae, 0xdf, 0x9b, 0x63, 0x7f, 0x00, 0x9b, 0x53, 0xe7, 0xcf, 0x9b, 0xd3,
	0x94, 0x7a, 0xcb, 0x9c, 0x7c, 0x65, 0xee, 0xc9, 0x27, 0x5f, 0xa0, 0xf0, 0xad, 0x2f, 0xb0, 0xfa,
	0xee, 0x2f, 0xf0, 0x12, 0xf6, 0xd4, 0x1b, 0xee, 0x5f, 0x49, 0xc1, 0xd9, 0x8d, 0x31, 0xf3, 0x5e,
	0x0b, 0x19, 0x18, 0x87, 0x96, 0xea, 0xd5, 0x39, 0x90, 0x36, 0x1d, 0x1a, 0x2c, 0x56, 0x78, 0xf7,
	0x96, 0xfd, 0x57, 0x42, 0x06, 0xe8, 0x1c, 0xaa, 0x3a, 0xd4, 0x04, 0xbf, 0x16, 0x61, 0xa2, 0x57,
	0x49, 0xa8, 0x0f, 0x4b, 0xbd, 0x80, 0x2a, 0x5f, 0x92, 0xa8, 0xa7, 0xef, 0x5a, 0x29, 0x9a, 0xd0,
	0xfb, 0x98, 0x29, 0x67, 0x52, 0xd1, 0x11, 0x01, 0x3d, 0x9e, 0x50, 0x43, 0x0e, 0x7c, 0x34, 0x0f,
	0xcc, 0x3a, 0x60, 0xdd, 0x00, 0x3d, 0x9a, 0x09, 0x94, 0xaa, 0xcc, 0x07, 0x61, 0xfc, 0x9a, 0xca,
	0x98, 0x06, 0x95, 0x8d, 0xb9, 0x20, 0x4d, 0xab, 0x82, 0x3e, 0x87, 0x0f, 0x98, 0xf2, 0x24, 0xa5,
	0x81, 0xa7, 0x44, 0x28, 0x22, 0xc1, 0x47, 0x69, 0x04, 0xc6, 0x7a, 0x8f, 0x29, 0x4c, 0x69, 0xd0,
	0x4d, 0x85, 0x59, 0x2a, 0x7d, 0x1f, 0xa0, 0x2f, 0x49, 0x44, 0x3d, 0xc5, 0x6e, 0x68, 0xa5, 0x74,
	0x90, 0x7b, 0xbc, 0x85, 0x37, 0xcc, 0x4a, 0x97, 0xdd, 0x50, 0xf4, 0x6b, 0x78, 0xc8, 0x94, 0x97,
	0x6a, 0xf8, 0x57, 0xd4, 0xff, 0x46, 0x07, 0x49, 0x86, 0xbb, 0x69, 0x70, 0xbf, 0xc7, 0xd4, 0x89,
	0x96, 0x3b, 0x56, 0x6c, 0x91, 0xab, 0xa7, 0xb0, 0xd3, 0x09, 0x09, 0x9f, 0x8e, 0xeb, 0x3a, 0xac,
	0xc4, 0x21, 0x35, 0x01, 0x5d, 0xaa, 0x1f, 0xcc, 0x79, 0xc2, 0x94, 0xa7, 0x2e, 0x43, 0x8a, 0xb5,
	0x72, 0xf5, 0x3f, 0x79, 0xd8, 0x3f, 0x95, 0x22, 0xe1, 0x41, 0x37, 0xd5, 0x9b, 0x86, 0xfc, 0x3d,
	0x94, 0xe2, 0x31, 0x3f, 0x59, 0xe8, 0x2f, 0x6a, 0x8b, 0x28, 0xba, 0x36, 0x8f, 0xd4, 0xf0, 0x24,
	0x1c, 0xea, 0xc2, 0xba, 0xb4, 0x19, 0x6a, 0x72, 0xa7, 0x54, 0xff, 0xd5, 0x62, 0xe8, 0x99, 0x39,
	0x8d, 0x47, 0x40, 0xe8, 0x39, 0x14, 0x2d, 0xc3, 0x9b, 0x1c, 0x2b, 0xd5, 0x3f, 0x9b, 0x83, 0x99,
	0xd5, 0x81, 0xa3, 0xf4, 0x3b, 0x8d, 0x97, 0x61, 0xa0, 0x53, 0x28, 0x0c, 0x43, 0xc2, 0x4d, 0x26,
	0xce, 0xc7, 0x9a, 0x38, 0xdf, 0x9d, 0x77, 0xc1, 0x06, 0xa0, 0xfa, 0xb7, 0x02, 0x94, 0x27, 0xdc,
	0xa2, 0xdd, 0x4d, 0x35, 0x11, 0xfa, 0x94, 0x6b, 0x22, 0x9c, 0x22, 0x87, 0x5c, 0x4a, 0x84, 0xa9,
	0x68, 0x92, 0x1a, 0x3e, 0x85, 0x9d, 0x8c, 0xc7, 0x43, 0x7a, 0x4d, 0x43, 0x2f, 0xe8, 0x45, 0xc6,
	0x75, 0x39, 0x7c, 0xdf, 0x0a, 0x5a, 0x7a, 0xfd, 0xb8, 0x17, 0xa1, 0x36, 0x3c, 0x60, 0xca, 0x1b,
	0xd3, 0xd5, 0x28, 0xb4, 0x52, 0xb7, 0xec, 0xd7, 0xd2, 0x32, 0x5a, 0xcb, 0xca, 0x68, 0xad, 0x21,
	0x44, 0xf8, 0x8a, 0x84, 0x09, 0xc5, 0xbb, 0x4c, 0x8d, 0x29, 0x2f, 0x8b, 0xe6, 0xb3, 0x99, 0x65,
	0xa4, 0xb0, 0x10, 0xec, 0x6e, 0x89, 0x69, 0xc2, 0x2e, 0x53, 0x1e, 0xeb, 0x7b, 0xea, 0x35, 0xa5,
	0xc3, 0x11, 0xd4, 0xea, 0x32, 0x50, 0xcd, 0x7e, 0x57, 0x1b, 0x65, 0x50, 0x2f, 0x4c, 0x66, 0xb2,
	0x20, 0xa4, 0xde, 0x90, 0x68, 0xbf, 0x8e, 0xaf, 0xb9, 0xb6, 0x10, 0x6e, 0x8f, 0xa9, 0x66, 0x10,
	0xd2, 0x4e, 0x6a, 0x98, 0x41, 0x7e, 0x3e, 0xa6, 0xdf, 0xa2, 0x81, 0x78, 0x74, 0x07, 0xe2, 0x24,
	0x14, 0x24, 0x4e, 0x31, 0x46, 0xdc, 0xdc, 0x80, 0xed, 0xcc, 0x37, 0xa2, 0xdf, 0x57, 0x34, 0x36,
	0xec, 0xb4, 0xc0, 0x7a, 0xcb, 0x9a, 0x5c, 0x18, 0x8b, 0xea, 0x7f, 0xf3, 0xb0, 0x33, 0xc1, 0x23,
	0x3a, 0x46, 0x12, 0x85, 0x30, 0xac, 0x29, 0x33, 0xb2, 0xb5, 0xea, 0x8b, 0x65, 0x92, 0xe4, 0x16,
	0x48, 0x2d, 0xfd, 0x60, 0x8b, 0xa4, 0xeb, 0x12, 0x4f, 0x22, 0xcf, 0x17, 0x52, 0x52, 0x3f, 0xd6,
	0xbc, 0xc6, 0x06, 0x9c, 0x84, 0xca, 0x04, 0xd3, 0x16, 0xde, 0xe5, 0x49, 0xe4, 0x64, 0xb2, 0x6e,
	0x2a, 0x42, 0x0e, 0xdc, 0xd7, 0x36, 0x03, 0x21, 0x82, 0x94, 0xb5, 0x94, 0x0d, 0xa5, 0xbb, 0x57,
	0x6c, 0xf2, 0xf8, 0x97, 0x4f, 0xed, 0x15, 0x79, 0x12, 0x9d, 0x0a, 0x11, 0x18, 0x1e, 0x53, 0xe8,
	0x08, 0xb6, 0x35, 0x48, 0x8f, 0x8c, 0x30, 0x0a, 0x8b, 0x31, 0x36, 0x79, 0x12, 0x35, 0x88, 0x85,
	0xa8, 0x9e, 0xc1, 0x9a, 0xf5, 0xcc, 0x1a, 0xe4, 0x2f, 0xce, 0xcb, 0xf7, 0xd0, 0x1e, 0x94, 0x9b,
	0xed, 0x4b, 0x17, 0xb7, 0xdc, 0xa3, 0x57, 0xae, 0xe7, 0x62, 0x7c, 0x81, 0xcb, 0x39, 0x74, 0x00,
	0x1f, 0x3a, 0x17, 0x18, 0xbb, 0xce, 0x65, 0xf3, 0xa2, 0xed, 0x39, 0x47, 0x9d, 0x23, 0xa7, 0x79,
	0xf9, 0x5b, 0xcf, 0xfd, 0xda, 0x71, 0xdd, 0x63, 0xf7, 0xb8, 0x9c, 0xaf, 0xfe, 0x7b, 0x15, 0xb6,
	0x32, 0x3e, 0x79, 0xff, 0x09, 0xf9, 0x13, 0xb8, 0xcf, 0x94, 0x37, 0xbc, 0x22, 0x8a, 0x7a, 0xa1,
	0xf0, 0xbf, 0xb1, 0xa9, 0xb8, 0x8e, 0xb7, 0x98, 0xea, 0xe8, 0xd5, 0x96, 0x59, 0x44, 0xcf, 0x60,
	0x9f, 0x29, 0xaf, 0xc7, 0x62, 0x6f, 0x5c, 0x62, 0x35, 0x7e, 0x6a, 0x52, 0x30, 0x26, 0x1f, 0x30,
	0xd5, 0x60, 0x71, 0x77, 0x42, 0x6e, 0x8d, 0x7f, 0x0c, 0xdb, 0x5c, 0xc8, 0x88, 0x84, 0xec, 0x46,
	0xbf, 0x2a, 0x97, 0x26, 0xad, 0x72, 0x78, 0x6b, 0xbc, 0xda, 0xe5, 0x12, 0xfd, 0x06, 0x3e, 0x1c,
	0xd5, 0x9e, 0x59, 0xbb, 0xac, 0x99, 0x5d, 0x1e, 0xda, 0xf2, 0x33, 0x63, 0x9f, 0x3f, 0xc3, 0xa3,
	0x3b, 0x45, 0x55, 0xd7, 0x2f, 0x1b, 0xa9, 0x45, 0x13, 0xa9, 0xcf, 0x16, 0x47, 0xea, 0xed, 0xa2,
	0xcb, 0xf8, 0xc0, 0x86, 0xea, 0x43, 0x7f, 0x9e, 0x08, 0xb5, 0xe0, 0x87, 0x33, 0x37, 0xd7, 0x3e,
	0xa3, 0x52, 0x0a, 0xe9, 0x99, 0xf4, 0x5d, 0x37, 0x37, 0xff, 0x78, 0x06, 0x4e, 0x83, 0xc5, 0xae,
	0xd6, 0xc3, 0xfa, 0xcd, 0x7d, 0xd8, 0x9d, 0x2a, 0xed, 0xf6, 0x0a, 0x1b, 0xcb, 0x32, 0xfe, 0x9d,
	0x64, 0xc3, 0x3b, 0xf2, 0x4e, 0x12, 0x4f, 0xb0, 0x0a, 0x7c, 0x27, 0x56, 0x29, 0xbd, 0x35, 0xab,
	0xfc, 0x23, 0x0f, 0x9b, 0xb6, 0xc8, 0xa5, 0x41, 0xde, 0x86, 0x22, 0xb9, 0x61, 0x51, 0x12, 0x5f,
	0xd9, 0x8a, 0xfe, 0x74, 0xf1, 0x25, 0x27, 0x01, 0x6a, 0x47, 0x7c, 0x10, 0x52, 0x9c, 0x81, 0x20,
	0x0c, 0x1b, 0x34, 0xa4, 0xd7, 0x69, 0x3f, 0x9d, 0xff, 0x0e, 0x88, 0x63, 0x18, 0xf4, 0x0a, 0x36,
	0x87, 0x22, 0x24, 0xd2, 0x76, 0x97, 0x26, 0x53, 0xb6, 0xeb, 0xf5, 0xe5, 0x6a, 0x79, 0x67, 0xc2,
	0x12, 0x4f, 0xe1, 0xec, 0x7f, 0x09, 0xab, 0x66, 0x2f, 0xdd, 0x65, 0xeb, 0x76, 0x96, 0xf0, 0xc0,
	0x38, 0x21, 0x87, 0xb3, 0x29, 0xda, 0x87, 0xf5, 0x88, 0x12, 0x95, 0x48, 0xfb, 0x2b, 0x29, 0x87,
	0x47, 0xf3, 0xea, 0x5f, 0xf2, 0x80, 0xa6, 0xfa, 0xa5, 0xd4, 0xa3, 0x97, 0xb3, 0xfa, 0xa4, 0xfa,
	0x5b, 0xf5, 0x49, 0x06, 0x68, 0xba, 0x3f, 0x3a, 0xbf, 0xd3, 0x1f, 0x1d, 0x2e, 0xdf, 0x1f, 0xa5,
	0x78, 0xe3, 0xbe, 0xe8, 0xec, 0x76, 0x5f, 0x54, 0x7b, 0xbb, 0x27, 0x1a, 0xb5, 0x44, 0xd5, 0xbf,
	0xaf, 0x00, 0xd2, 0x5d, 0x4e, 0x8b, 0xf5, 0xa9, 0xff, 0xc6, 0x0f, 0xa9, 0x7b, 0x4d, 0x79, 0x8c,
	0xba, 0xb7, 0xca, 0xd4, 0xb3, 0xe5, 0x7a, 0xa5, 0x69, 0x94, 0xdb, 0x75, 0xca, 0x83, 0x62, 0x9f,
	0xb0, 0x30, 0x91, 0xd4, 0x7a, 0xc0, 0x79, 0x27, 0xd4, 0x93, 0x14, 0xe3, 0x98, 0xc6, 0x84, 0x85,
	0xea, 0xec, 0x1e, 0xce, 0x50, 0xf7, 0xff, 0x9a, 0x83, 0xed, 0x69, 0x29, 0xf2, 0x60, 0xd5, 0x27,
	0x89, 0xa2, 0xf6, 0x1e, 0xcd, 0xff, 0xc3, 0x8e, 0x35, 0x47, 0x03, 0xe2, 0x14, 0xb7, 0xba, 0x07,
	0xab, 0x66, 0x8e, 0x4a, 0x50, 0x7c, 0xd9, 0x3e, 0x6f, 0x5f, 0x7c, 0xd5, 0x2e, 0xdf, 0xab, 0xb6,
	0x47, 0x65, 0x6d, 0x72, 0x19, 0x6d, 0xc1, 0x46, 0x07, 0xbb, 0x9d, 0x23, 0xdc, 0x6c, 0x9f, 0x96,
	0x73, 0x7a, 0xea, 0x7e, 0xed, 0x3a, 0x2f, 0x2f, 0xf5, 0x34, 0xaf, 0xa7, 0xce, 0xc5, 0xf3, 0x4e,
	0xcb, 0xbd, 0x74, 0x8f, 0xcb, 0x2b, 0x08, 0x60, 0xed, 0xe4, 0xa8, 0xd9, 0x72, 0x8f, 0xcb, 0x85,
	0xc6, 0x06, 0x14, 0xed, 0xee, 0xd5, 0x3f, 0xdc, 0x0a, 0xda, 0xf4, 0xc1, 0xce, 0xa6, 0x5a, 0xdb,
	0xa7, 0xef, 0x72, 0xcd, 0xb4, 0xb7, 0xfd, 0xf4, 0x05, 0x3c, 0x9c, 0xcb, 0xe3, 0x68, 0x13, 0xd6,
	0x5f, 0xb6, 0x5b, 0x17, 0xce, 0xb9, 0x7b, 0x5c, 0xbe, 0xa7, 0x67, 0x4d, 0xcf, 0xce, 0x72, 0x7a,
	0xf6, 0x22, 0x9b, 0xe5, 0xf5, 0xe9, 0xed, 0x78, 0xa5, 0xf1, 0x27, 0xf8, 0x91, 0x2f, 0xa2, 0x85,
	0x67, 0x6a, 0xdc, 0x7f, 0x3e, 0x1a, 0x77, 0x34, 0x15, 0x76, 0x72, 0xbf, 0xfb, 0x72, 0xc0, 0xe2,
	0xab, 0xa4, 0xa7, 0x7f, 0xad, 0x1e, 0x32, 0xde, 0x17, 0x16, 0x83, 0x71, 0xff, 0x70, 0x20, 0x7e,
	0xb1, 0xe8, 0x3f, 0x52, 0xbd, 0x35, 0x43, 0xa9, 0x9f, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xc1,
	0xc2, 0x8d, 0x5f, 0xbc, 0x12, 0x00, 0x00,
}
